### ISSUE TITLE
Command for crossing restrictions

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#10]
Issuing descent/speed instructions relative to a fix on an aircraft's flightplan is commonplace. For example:

>"AAL482, maintain 190 knots to FINKA"
>"UAL3185, cross LENDY at Flight Level 190 at 250 knots"

Adding a command that would allow for these types of instructions would do a lot for the enroute side of the simulation, whenever that comes along, and will still be very useful in the current version of the sim (especially in very large "super-TRACONs").

Closely related to #11.
Originally reported in zlsa/atc#315.

### Altitude crossing restrictions already completed in #1080.

**Comment by n8rzz** [comment]
this feels like we can simply update a WaypointModel's `_altitudeRestriction` or `_speedResctriction` property.  we would have add some new commands, but based on the examples posted here, that should be fairly trivial.

**Comment by erikquinn** [comment]
Correct. We would enter a new altitude/speed restriction at the appropriate waypoint, and then set the mcp altitude to the procedure's bottom altitude, and activate VNAV. All stuff that _magically works because we've set things up to emulate reality_. Awesome stuff!!

**Comment by indianbhaji** [comment]
From what I've witnessed before, cross doesn't imply direct - if you want someone to direct, you say something along the lines of "DAL36, direct LENDY, descend to reach FL190 at LENDY"

**Comment by erikquinn** [comment]
Not direct. Stay on the route and be at that altitude by the time you pass the specified fix.

**Comment by JPmAn24** [comment]
I think I could make this work. An idea I had was to split the `cross`/`cr` command in two:
`cra`: Cross at a specific altitude
`crs`: Cross at a specific speed
Would this be okay with everyone?

**Comment by erikquinn** [comment]
No, they should be parsed from the arguments of the same command (cross/cr). We should also add `X` to the aliases (stealing from taxi).

```
x hoggs a180
x irokt a90
x essso a100 s250
x dylin s210
```

**Comment by j-651** [comment]
Would there be any conflict with x being used for "expedite"?

**Comment by erikquinn** [comment]
@j-651 Should be fine. The command parser pays attention to the context of where the x is within the user's entry, and it should actually be able to tell the difference easily iirc.

**Comment by erikquinn** [comment]
Speeds implemented, completing this issue:
- secondary issue created for reference number for the second half of this work: #1624.
- work originally from PR #1603.
- moved that PR to a new one of the right branch: #1625.
- merged to develop.

Closing this issue as complete.
