### ISSUE TITLE
Remove support for WIP airports

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#1001]
WIP airports are no longer allowed, and some old stuff relating to them should be removed:
- `wip` property of `AirportModel`
- `wip` from all airport files and documentation
- `Include WIP airports` from settings menu

**Comment by indianbhaji** [comment]
There's no point in setting it to WIP. WIP was for airports that did not
meet the requirements of the 'new' standards, so there's no need for those
anymore as all new airports or redevelopments **must** reach the standards
set out in the documentation before entering the sim.
