### ISSUE TITLE
[KSEA] Aircraft leaving airspace without proper clearance

### ISSUE THREAD

**Issue by Marcel510** [openscope/openscope#1018]
Airport: KSEA

Aircraft spawned with the route: "KSEA16L.HAROB6.FEPOT" are causing a "leaving airspace without proper clearance" error because FEPOT is still within the airspace boundary

**Comment by Fechulo** [comment]
This is an easy fix, the route just needs to be extended; KSEA has airways implemented too so it should be even easier
