### ISSUE TITLE
Add stats 

### ISSUE THREAD

**Issue by Marcel510** [openscope/openscope#1021]
Some simple stats would be helpful, for example a counter with arrivals/departures handled, operational errors, etc. Most of this is already in place with events, we would just need to provide a way for users to see this data in a non-ugly way.

Related: #1020

**Comment by internetbird** [comment]
Hi @erikquinn . Do you plan to implement this? If so, I can take this task on me

**Comment by erikquinn** [comment]
@internetbird you're welcome to it, absolutely! Look for the GAME_EVENTS or EVENTS constants, thats what events we are recording already, just need a way to show that stuff to the users. :)
