### ISSUE TITLE
Options dropdowns have wrong background color

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#1030]
In Chrome, the background color of the dropdowns in the options menu have a white background and white text. Looks like it was set up to inherit the background color of the parent element, but for whatever reason it looks like a `select` does not do that.

![image](https://user-images.githubusercontent.com/5103735/43167543-0ff6d02e-8f68-11e8-8b3c-659370dae9f5.png)

**Comment by n8rzz** [comment]
I don’t recall if we’ve attempted to create a completely custom drop down or simply provide a styled closed state. 

We should aim for the later either way. 

Styling selects is natoriously difficult across browsers. Our time would be better spent elsewhere.

**Comment by erikquinn** [comment]
It's a normal `<select>` as far as I can tell. Applying color to it directly does resolve the issue (in #1031).

**Comment by n8rzz** [comment]
Does it behave the same way in Chrome, IE, Firefox and safari?

**Comment by erikquinn** [comment]
Same before and after in Chrome, IE11, Edge, and Firefox. Unable to test Safari due to my mac-less-ness. Deployed a review app for anyone with safari to check out: https://openscope-dev-pr-1031.herokuapp.com/
