### ISSUE TITLE
Waypoint time-to-turn calculations are slightly off

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#1034]
Discovered during the work on #937, the calculations (which could never be figured out because they're old and without labels/explanations) turned out to actually be slightly off. They should be reworked and better documented so we can clearly see how the calculations work.

**Comment by felixscheffer** [comment]
@erikquinn I tried your new implementation and it causes aircrafts to overshoot waypoints
![waypoint-overshoot](https://user-images.githubusercontent.com/1678164/44794723-5cd3b080-aba9-11e8-8c94-dd1f4cc9af34.PNG)

So I tried to figure out what real pilots do and found:
http://code7700.com/pdfs/icao_doc_9905.pdf (3.2.4 - page 23)


> The turn anticipation distance (DTA) is the distance measured from the turn fix to the start and end points  of a fly-by turn. 
>
> DTA = r tan (A/2)
>
> where:
> r = radius of turn for the TAS for the fastest aircraft speed category for which the procedure is designed, at the turn altitude and at ISA+15
> A = turn angle 

... which is more or less the current implementation
