### ISSUE TITLE
Aircraft wrongfully level out for AOA and AOB restrictions

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#1040]
```
/// AircraftModel._calculateTargetedAltitudeVnav()
const nextAltitudeMaximumWaypoint = this.fms.findNextWaypointWithMaximumAltitudeAtOrBelow(this.altitude);
const nextAltitudeMinimumWaypoint = this.fms.findNextWaypointWithMinimumAltitudeAtOrAbove(this.altitude);
const maximumAltitudeExists = !_isNil(nextAltitudeMaximumWaypoint);
const minimumAltitudeExists = !_isNil(nextAltitudeMinimumWaypoint);
```

This falls through whenever the aircraft is spawned _already in compliance with an ranged altitude restriction_, because it thinks the next restriction is no factor, and it doesn't look further than that.

Example of an affected airport is KAUS, ELOEL2 SID at WLMRT (`A50+`), where a/c climb to 5000 and then stop, when they should be climbing higher. Also in EDDL, `A06+` are causing aircraft to level out at 600ft.

**Comment by n8rzz** [comment]
@felixscheffer could you verify this one too?  Looks like the related PR was merged some time ago.

**Comment by felixscheffer** [comment]
@n8rzz I'll check that tomorrow.

**Comment by felixscheffer** [comment]
Looks like this issue got worse. I tried `KAUS, ELOEL2 SID` and the aircraft does not turn towards WLMRT  and remains at 5000ft. I'll dig deeper tomorrow and hopefully, we can come up with a fix for the upcoming 6.8.0 release.

**Comment by JPmAn24** [comment]
It’s supposed to be like that. Ask @indianbhaji as he reviewed the #990 PR. Also, the chart for the ELOEL2 Departure has the controller provide directions to WLMRT. Usually, I make the aircraft turn west right off the runway, then once it hits 3000ft, procede direct WLMRT.

**Comment by erikquinn** [comment]
Right, they do get vectors to `WLMRT`. Maybe it needs to be told to climb via sid in order for the VNAV climb mode to engage?

To test the theory, after takeoff, give them `pd wlmrt cvs`, and they might actually climb to cruise in compliance with the SID? Who knows!

**Comment by JPmAn24** [comment]
I usually put “caf cvs pd wlmrt” as the last command

**Comment by JPmAn24** [comment]
Then it still levels off at 5000

**Comment by JPmAn24** [comment]
I’ll take a video and put it on the slack.

**Comment by felixscheffer** [comment]
> Maybe it needs to be told to climb via sid in order for the VNAV climb mode to engage?

It does.

**Comment by felixscheffer** [comment]
Sorry guys for the confusion. I checked the prod version of openScope which does not include #1063 yet. 

On http://dev.openscope.co/ the aircraft climbs to the assigned altitude as expected.

Closed as fixed.
