### ISSUE TITLE
Strange behaviour after landing

### ISSUE THREAD

**Issue by Fechulo** [openscope/openscope#1044]
Browser: Chrome

Airport: KBOS

#### Issue Description
After landing aircraft will decelerate very slowly causing them to overrun the runway. They also seem to be touching down well above the runway height.
![runway overrun](https://user-images.githubusercontent.com/13125311/43717641-137a74e0-9980-11e8-8a57-b6a177ee24b5.PNG)
In the picture above, UAL6608 landed on runway 27, but we can see it far past the terminals still going at 110kts and at 50ft (despite airport elevation being 19ft)
VIR123 landed on runway 22L and also overran the runway, currently in the water at 70kts

#### Steps to reproduce
- Land an aircraft and observe touchdown

**Comment by fscheffer** [comment]
Same behavior on EDDF runway 25R. 

The aircrafts also seem to drift off the centerline. 

![eddf-3](https://user-images.githubusercontent.com/1678164/44298437-6e80a280-a2e3-11e8-8fcf-32d07edf2721.PNG)

**Comment by fscheffer** [comment]
For some reason the aircraft is drifting off the centerline during final approach. As a result `isEstablishedOnCourse()` in `_calculateTargetedAltitudeToInterceptGlidepath()` returns false causing the aircraft to gain height. Once the aircraft reaches the runway it will start to descend again until it reaches the ground.
