### ISSUE TITLE
Update flight strips view by separating arrival and departure strips

### ISSUE THREAD

**Issue by tdawe** [openscope/openscope#1077]
Currently, all arrival and departure strips are combined in the same list. It would be nice to seperate them into Arrivals and Departures lists for easier management.

If this feature is agreed to be added, I currently have it working in a private branch. If I can be added to this repo org, I can push it to a branch here.

Related: #1088.

**Comment by erikquinn** [comment]
Done! Check email for invite. And you can also come up on our slack if you like, it's quite active.

slack.openscope.co

**Comment by tdawe** [comment]
Thanks @erikquinn! I joined the slack channel a few days ago, so I'll be active on there too.
