### ISSUE TITLE
P28A Climb rate

### ISSUE THREAD

**Issue by DanielePancottini** [openscope/openscope#1086]
Issue to request change the CR of P28A FM 2000ft/m TO 700ft/m as PR openscope/openscope#1082

**Comment by erikquinn** [comment]
2000fpm for a P28A does seem quite wrong, doesn't it? We should find a better value and include proof of that value's validity.

**Comment by DanielePancottini** [comment]
@erikquinn Usually, a P28A 160hp has got 700/1000ft/m...Instead, a P28A 180hp, take usually 1000/1200ft/m as rate of climb. To close, if you want, you can approve my pull request with the changes committed. PR #1082

**Comment by felixscheffer** [comment]
https://en.wikipedia.org/wiki/Piper_PA-28_Cherokee

> Rate of climb: 660 ft/min (3.4 m/s)

**Comment by Marcel510** [comment]
@erikquinn Since our preferred source for climb and descent rates is the Eurocontrol Aircraft Performance Database: https://contentzone.eurocontrol.int/aircraftperformance/details.aspx?ICAO=P28A
700 fpm should be fine.
