### ISSUE TITLE
Vector waypoints cause console error

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#1101]
Console error appears for most airports (including KSEA) in the latest v6.6.0-BETA build when aircraft approach a vector waypoint, because a recent refactor expects all waypoints to have a position, and vector waypoints do not. Will need to add a logical branch to return the vector waypoint's heading early if the waypoint _is_ a vector waypoint to keep everything working properly.

![image](https://user-images.githubusercontent.com/5103735/46266584-308bb680-c4fe-11e8-9f5d-fa91a1f49576.png)

**Comment by Marcel510** [comment]
Resolved by #1102, closing.
