### ISSUE TITLE
Console warnings for removing StripViewModel which doesn't exist

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#1104]
Console warnings appear regarding attempts to remove a `StripViewModel` from the `StripViewCollection`.

`Attempted to remove a StripViewModel for QXE7954 that does not exist. This is likely not a fatal problem, but if you are seeing this, please let somebody know.`

Comes from `StripViewController.removeStripView()`.

![image](https://user-images.githubusercontent.com/5103735/46374934-02be8300-c660-11e8-921b-3ff99bc84f7b.png)

**Comment by felixscheffer** [comment]
I can reproduce this when switching from one airport to another. Before loading the new airport, we are iterating over all the existing flights and try to remove their flight strips. Aircrafts that are outside of our sector don't have strips yet and cause this warning.

**Comment by erikquinn** [comment]
@felixscheffer interesting. that is probably a duplicated effort, as I would assume the strips would be removed as part of removing the aircraft (which happens during the airport change process).

**Comment by felixscheffer** [comment]
I think there is another case for this warning:

```
// Clean up the screen from aircraft that are too far
if (!this.isAircraftVisible(aircraftModel, 2) && !aircraftModel.isControllable && aircraftModel.isRemovable) {
     this.aircraft_remove(aircraftModel);
}
```

The aircraft is not controllable but `aircraft_remove `will try to remove the (non-existing) flight strip.
