### ISSUE TITLE
Show airport guide in-game

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#1105]
An option to show the airport guide in game would be helpful. We would want it to be toggled on and off, and have the markdown file rendered into html. I know nothing about doing this, but came across "showdown" in a few minutes of half-baked research:

https://github.com/showdownjs/showdown

We have the guides, we just need to make them more accessible to the users!

Related: openscope/openscope#804 (same thing for the changelog)

**Comment by JPmAn24** [comment]
I'll be doing some experimentation with this for the time being. Will report back with results.
