### ISSUE TITLE
Draw STARs on canvas

### ISSUE THREAD

**Issue by indianbhaji** [openscope/openscope#111]
@willfrd mentioned in zlsa/atc#781    that STARs aren't drawn.

@n8rzz said this is something that he'd like to work on, so here's the issue!

It would be nice to see the STAR lines just like how it is already done with the SID lines.

Related: #1093.

**Comment by willfrd** [comment]
Just wondering, with this new repository the original zlsa/atc repository will be completely closed? Future projects will have to be uploaded into here? Do we know how much the "moving" will take? Thanks

**Comment by erikquinn** [comment]
@willfrd Correct, all future work will be done here.
