### ISSUE TITLE
Readme - Airport Documentation link is broken

### ISSUE THREAD

**Issue by TheBear44** [openscope/openscope#1114]
In contributing section, the Airport Documentation link points to https://github.com/openscope/openscope/wiki/Airport.json which doesn't exist.

Should we point it to some file in [documentation](https://github.com/openscope/openscope/tree/d6c55c753b1bcecf20efce5b8e110545ed638daa/documentation)?

---
Related to #1115

**Comment by Marcel510** [comment]
When the github wiki was moved to the in-repo wiki many links weren't updated, I'll take care of this.

**Comment by erikquinn** [comment]
Covered by #1115. Closing.
