### ISSUE TITLE
Openscope repo vs. ZLSA ATC vs n8rzz/ATC

### ISSUE THREAD

**Issue by panther2** [openscope/openscope#112]
Sorry if this is not the right place to ask, but I did not find a better place...

So - being quite new to this - I understood that 

- ZLSA  ATC appears to be the "productive" repo
- n8rzz ATC appears to be the "development" repo

Watching many content having been moved over from those repos to this openscope repo during the last days, I am wondering about the position of "openscope" in this context... 

Also - is there content planned for www.openscope.co ?

Thanks a lot.

**Comment by indianbhaji** [comment]
I'll let the others explain (@n8rzz and @erikquinn) but at the moment, I
believe new issues should ideally be made in openscope instead of here or
@n8rzz's fork. I believe @n8rzz is moving everything to openscope after he
finishes 3.9.0 and 4.0.0, but don't quote me on that.

Personally, I've already moved to openscope.

**Comment by n8rzz** [comment]
We haven't made a formal announcement on the repo yet, but in the very near future we will be moving both projects to this repo.  We will be working on _only_ this repo for development, which means no more forks.  

- This will allow us to keep all issues in a single place and give us greater flexibility in maintaining the project.  

- You will have also noticed that this is no longer a personal repo, `openscope` is an official github organization.  That will give greater flexibility to the admins and allow for easier collaboration amongst contributors.

- We will have (Travis CI)[https://travis-ci.org/] connected to the repo.  So any pull request will automatically run our testing suite, which continues to grow in coverage.  The status of those tests will be viewable in every PR.

- We will be moving away from github pages as the primary deployment vehicle in favor of a node app deployed to Heroku.  Specifically, we have multiple environments for `develop`, `release` and `production`, along with (review apps)[https://devcenter.heroku.com/articles/github-integration-review-apps] and a few other dev-ops things.  Heroku is setup to deploy on push, and deploys to a specific environment for specific branches.  So a push to develop will run the tests and, as long as all the tests pass, then deploy to Heroku. 

As you can see, lots of changes are coming!  Most of the bullet points above we have been doing/using on my fork with great success.  Review apps is a favorite of mine, along with the testing integrations.

There will be formal announcement coming soon.

**Comment by n8rzz** [comment]
And yes, my fork is currently finishing up with release v3.3.0 which will contain many breaking changes.  So after that is finished and pushed, we will then be on v4.0.0 and moving over to this repo full time.

**Comment by panther2** [comment]
Very interesting, Looking forward to it. Thanks for the background information!
