### ISSUE TITLE
Update project dependencies

### ISSUE THREAD

**Issue by n8rzz** [openscope/openscope#1137]
Its been some time since we've updated our libraries, which is like a lifetime in JS.

Things we should update/add:
- [x] node reference in `package.json`
- [x] npm reference in `package.json`
- [x] babel and supporting babel plugins
- [x] eslint and supporting packages
- [x] create `.nvmrc` file for current node version
- [x] update to `node@11.3.0` and current npm
- [x] upgrade to babel 7
- [x] update babelrc
- [x] upgrade to `gulp@4.0.0`
- [x] refactor gulp tasks to use v4 api
- [x] remove/replace `gulp.util` things

Work here will very likely expose new issues with upgraded packages.  Those should all be addressed as part of this issue.  it could be a big chunk of work.

**Comment by felixscheffer** [comment]
gulp-util is deprecated and needs to be replaced.

https://www.npmjs.com/package/gulp-util

**Comment by felixscheffer** [comment]
gulp-minify-css is deprecated. Please use gulp-clean-css.

https://www.npmjs.com/package/gulp-minify-css

**Comment by n8rzz** [comment]
@erikquinn you want me to merge this one or wait till next month?

**Comment by n8rzz** [comment]
hmm, never mind, I answered my own question.  going to swing for the fences on this one and upgrade `gulp` and move our `node` dependency all the way to modern with `11.3.0`.  

Moving back to WIP
