### ISSUE TITLE
Implied holding in route strings

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#114]
When parsing a route string, allow for use a specific character to indicate that the specified fix is one over which the aircraft should *hold*.

Use case: European STARs usually begin with a hold at the fix for which they are named, and are then assigned a transition. We can achieve the former by having the `spawnPattern`'s `route` be something like `LOGAN.BIG.BIG@`, or similar, which causes the last waypoint generated to be a holding waypoint.

**Comment by n8rzz** [comment]
I think that would be doable.  With the `routeBuilder` stuff, I think we would be able to create a holding waypoint from a `routeString`.

see: [n8rzz#256](https://github.com/n8rzz/atc/issues/256) and [n8rzz#262](https://github.com/n8rzz/atc/issues/262)

**Comment by n8rzz** [comment]
done under openscope/openscope#139

**Comment by erikquinn** [comment]
Rolled into #139.
