### ISSUE TITLE
Time warp toggle should reset when window regains focus

### ISSUE THREAD

**Issue by Fechulo** [openscope/openscope#1148]
Also see #1335.

#### Issue Description
If the window loses focus while time warp is enabled, the simulation is paused and time warp is set back to 1 (as desired). When the window regains focus, the time warp toggle displays time warp still enabled.

Reported by darren on Slack

#### Steps to reproduce
- Set time warp to 5 (button will be red)
- Switch to another window
- Switch back to openScope
- Time warp button will remain red, despite time warp being disabled

**Comment by erikquinn** [comment]
Absorbed into #1335. Closing.
