### ISSUE TITLE
GameClockView crashes sim in Firefox

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#1152]
Browser: Firefox

Looks like the sim is not running on Firefox as of the latest build on staging. It works fine on Chrome, which is strange.

![image](https://user-images.githubusercontent.com/5103735/47688507-135d0d00-dbbc-11e8-8980-044fc1fb18f3.png)

**Comment by felixscheffer** [comment]
Wild guess: It's a chain reaction caused by

InputController: Line 113
`this.$body.addEventListener('contextmenu', event.preventDefault());`

event is defined in Chrome but undefined in Firefox.

**Comment by n8rzz** [comment]
😦 how did I miss that.  good find!

**Comment by erikquinn** [comment]
I was confused by the solution because that could only mean that it's been broken like this for... a long time? At least a month? Who knew! :joy:

**Comment by felixscheffer** [comment]
The bug was introduced by #1134 which is part of the 6.7.0 release.

**Comment by erikquinn** [comment]
that makes a lot more sense :relieved:
