### ISSUE TITLE
Firefox strip bay not hiding the scrollbars

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#1158]
The scrollbars in the strip bay are supposed to be styled nicely, and hidden when not needed. In Firefox (61.0.1), they appear at all times anyway, and are icky looking.

![image](https://user-images.githubusercontent.com/5103735/47755647-6b0b7f00-dc75-11e8-9f9e-f4a8c3e0f64e.png)

**Comment by felixscheffer** [comment]
As far as I am aware Firefox does NOT support scrollbar styling.
https://stackoverflow.com/questions/6165472/custom-css-scrollbar-for-firefox

**Comment by n8rzz** [comment]
We should avoid styling scrollbars at all costs. They are grossly inconsistent or unavailable across browsers. 

In my opinion; it looks nice but it’s a waste of time

**Comment by felixscheffer** [comment]
![image](https://user-images.githubusercontent.com/1678164/47758132-f0108b80-dca9-11e8-853b-a2dc38a015e9.png)

I tried to figure out why the scrollbar is not hiding in Firefox.  `overflow-y: auto;` should do the trick but it doesn't. With `overflow-y: auto;`  the scrollbar wont show up even when it should.

**Comment by erikquinn** [comment]
@felixscheffer @n8rzz 
What are the alternatives then?

**Comment by felixscheffer** [comment]
To make things worse, I just noticed that one can not scroll the flight strips in Firefox.

**Comment by felixscheffer** [comment]
Bug in Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1042151

With `flex-direction: column` everything works fine. With `flex-direction: column-reverse` scrolling is broken in Firefox.

**Comment by kmartino2168** [comment]
🎵🎵 I can see clearly now, my flight strips scroll 🎵🎵
