### ISSUE TITLE
2nm range rings? 

### ISSUE THREAD

**Issue by Fltchk31** [openscope/openscope#1170]
Browser:safari

Airport:all

Approximate play time before issue:0

#### Issue Description
_please include any console errors and/or screenshots_ 
Enhancement suggestion. Would it be possible to have 2nm range rings in addition to the current 5nm range rings?  Would reflect better scope flexibility in real world. 

#### Steps to reproduce
-

**Comment by Marcel510** [comment]
For which situation exactly would you need 2nm rings?

**Comment by felixscheffer** [comment]
duplicate of #1032
