### ISSUE TITLE
unable to take off, we never received an IFR clearance

### ISSUE THREAD

**Issue by vecersi** [openscope/openscope#1175]

**Comment by Marcel510** [comment]
Hello, have you tried to clear the aircraft as filed? ("caf")
See: https://github.com/openscope/openscope/blob/develop/documentation/aircraft-commands.md#cleared-as-filed

**Comment by vecersi** [comment]
yes, but still dont working all airport

**Comment by vecersi** [comment]
How can i repair it? what am i doing wrong???

**Comment by Fechulo** [comment]
Hey @vecersi If you join our [slack ](http://slack.openscope.co/)we can talk the issue through better and find a solution faster

**Comment by Marcel510** [comment]
@vecersi Were you able to solve the problem on your own or do you still need help?

**Comment by vecersi** [comment]
Hello i have this problem, i try 3 PC and this problem is on all the PC still, i absolutely dont know what to do with it. Please help, Thank you

**Comment by Fechulo** [comment]
@vecersi We'll be able to solve the issue faster if you join our slack here: http://slack.openscope.co/

**Comment by felixscheffer** [comment]
Closing, as I can't see a bug here. If there is actually a bug, feel to reopen or open a new issue. For questions and support, please use slack.
