### ISSUE TITLE
Comments in UiController.js are duplicate

### ISSUE THREAD

**Issue by JPmAn24** [openscope/openscope#1176]
In src/assets/scripts/client/UiController.js, the comments for some methods are not correct

**Comment by erikquinn** [comment]
@JPmAn24 this probably doesn't require its own issue, as it's such a tiny change. If there's something you're working on where you are making changes to the UiController when you noticed this mistake, you can just fix it there and close this.

**Comment by erikquinn** [comment]
To be included in #1105. Closing.
