### ISSUE TITLE
Arrivals can not be selected

### ISSUE THREAD

**Issue by marksarnold** [openscope/openscope#1181]
Browser: Chromium on Linux

Airport: Hamburg and Portland (the only two I tried)

Approximate play time before issue:20 minutes

#### Issue Description
Departures working fine. Arrivals initially worked fine as well.
At some point after the last arriving plane had landed, new arrivals/overflights showed on the map, but "Arrivals / Overflights" box is empty and I can not select planes by clicking them either.
I managed to make them show up by manually typing the call sign and querying airspeed. The plane responded and then it did show up in the box.
Even switching airports and reloading the entire browser window did not fix the issue.

#### Steps to reproduce
Not sure

**Comment by felixscheffer** [comment]
Wild guess: the aircrafts are too high, i.e above your sector.

**Comment by erikquinn** [comment]
Waiting will fix it. They have to be inside your airspace before you can select them. Keep in mind they will also have to descend into the altitudes you control.

**Comment by erikquinn** [comment]
If that doesn't fix it, we can reopen this. Closing for now!
