### ISSUE TITLE
Changing theme should trigger a deepRender() within CanvasController

### ISSUE THREAD

**Issue by n8rzz** [openscope/openscope#1183]
found in #1182, though likely not related to changes there.

moving from default -> classic
<img width="444" alt="screen shot 2018-11-10 at 12 38 12 pm" src="https://user-images.githubusercontent.com/3325985/48304817-e1b24300-e4e5-11e8-8e20-aa3adae8eea6.png">
 
moving from classic -> default
<img width="304" alt="screen shot 2018-11-10 at 12 38 25 pm" src="https://user-images.githubusercontent.com/3325985/48304825-f42c7c80-e4e5-11e8-971f-bdf0e96b69e4.png">

At a high level, when this game option changes an event should be triggered that results in `CanvasController.deepRender()` being called immediately afterward.  

The app renders the terrain only as often as it needs to.  Which means if there is no pan or zoom change the terrain will not re-render, which is why we see this issue here.

**Comment by felixscheffer** [comment]
changing the theme _should_ trigger `EVENT.SET_THEME`. The canvas controller is already subscribing to it, so it shouldn't be to hard...
