### ISSUE TITLE
unable to take off, we never received an IFR clearance

### ISSUE THREAD

**Issue by vecersi** [openscope/openscope#1186]
Hello, i have got this problem

ENGM airport, but i have got this problem on many other airport

1. select airplane, and write-caf
2. write-cvs
3. write-w 01L
4. airplane is on the runway and, i write to and it write unable to take off,.......

Please help, i like this game very much

**Comment by Marcel510** [comment]
I have exactly followed your reproduction instructions and and it works perfectly no errors or anything.
As already said if you have problems it's definitely recommended to reach out to us on Slack.

**Comment by vecersi** [comment]
I am using Opera and i have problem, my friend using google chrome and he has got this problem too, please help.

**Comment by erikquinn** [comment]
@vecersi For any of the aircraft that have this issue, what was their flight plan route? When the aircraft is selected, the flight strip (on the right side of the screen will be offset).

If we know what the route is, that may help to figure out why this is happening.

**Comment by erikquinn** [comment]
@vecersi?

**Comment by Marcel510** [comment]
@erikquinn If I understood his description on Slack correctly, this doesn't
look like a sim bug, that's why I already closed it once.

Am So., 18. Nov. 2018, 02:10 hat Erik Quinn <notifications@github.com>
geschrieben:

**Comment by n8rzz** [comment]
@erikquinn I remember this conversation on slack.  pretty sure this can be closed.
