### ISSUE TITLE
Consolidate command bar buttons

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#1191]
We are accumulating a lot of buttons in the command bar, and they should be consolidated into groups so they take up less room, are more organized, and more intuitive to figure out what the icons are supposed to represent because you have additional context.

```
Scope --> [SIDs, STARs, terrain, video map, navaids, restricted, range rings]
Settings
Help --> [Tutorial, GitHub link, YouTube link, Slack link, Command Reference link, Airport Guide link]
```

**Comment by felixscheffer** [comment]
Can someone create/find/suggest an icon for "scope"?

@Marcel510

**Comment by erikquinn** [comment]
I can vectorize this one real quick...

http://chittagongit.com/icon/radar-icon-vector-22.html
![image](https://user-images.githubusercontent.com/5103735/48664589-0a4eb580-ea6f-11e8-9e96-82d18d987eaa.png)

**Comment by felixscheffer** [comment]
Looks awesome! 👍

**Comment by erikquinn** [comment]
All done!

![image](https://user-images.githubusercontent.com/5103735/48664748-5995e580-ea71-11e8-9efa-76c4d99547ef.png)


[scope.zip](https://github.com/openscope/openscope/files/2592150/scope.zip)

**Comment by Fechulo** [comment]
It would be good to eventually have a link to the youtube channel and maybe even twitter or reddit

**Comment by JPmAn24** [comment]
Possibly an icon for the help section?
