### ISSUE TITLE
Remove "WIP" flags from the airport's "name"

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#121]
_From @erikquinn on December 15, 2016 4:57_

The little WIP flags should at least be removed from the name of the airport files. Instead, let's make it a property, `wip: true`, and check `if(airport.wip)`, and from there determine whether or not to *append* the flag symbol to the name when writing it to the list within the airport selection dialog.

The issue here is that we shouldn't have the flag showing up in the console and other places; for example, if you use the `star` command, it shows this:
![image](https://cloud.githubusercontent.com/assets/5103735/21212262/fd71359e-c258-11e6-82df-b7ea86337815.png)

_Copied from original issue: n8rzz/atc#205_

**Comment by n8rzz** [comment]
fixed under [n8rzz#181](https://github.com/n8rzz/atc/issues/181)
