### ISSUE TITLE
aircraft that collide are not properly removed

### ISSUE THREAD

**Issue by n8rzz** [openscope/openscope#1218]
After an aircraft collides with terrain or another aircraft, they are not properly removed from the sim.

<img width="168" alt="screen shot 2018-11-23 at 2 02 39 pm" src="https://user-images.githubusercontent.com/3325985/48959073-af163a80-ef28-11e8-9e2b-5f1cbd37e7fe.png">

This is an example of an aircraft that collided with another aircraft, 5 mins prior to this screenshot.

**Comment by kmartino2168** [comment]
I'm taking a shot at this.  I can't make any guarantees since this is my first ticket and I'm not that familiar with the codebase, but hey, it's worth a try.

**Comment by kmartino2168** [comment]
I'm going to remove myself from this-- there are people far more qualified to figure this out than I, and my time could be more efficiently spent working on things that are within my currently knowledge of the codebase.
