### ISSUE TITLE
Rerouting uncleared aircraft onto SID fails

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#122]
_From @erikquinn on December 15, 2016 6:37_

Say you have an aircraft on the ground at the airport, and they filed for sid A. If you don't want them to fly that one, you will not use `caf`, and you will instead reroute them, perhaps via `rr kiad.jcoby3.swann..mxe`. This will fail due to an erroneous condition check that references the state of a variable that does not exist.

See `Leg.js:184`.

Simply removing the `pairs.length > 0` contingency seems to provide the expected results.

_Copied from original issue: n8rzz/atc#207_

**Comment by n8rzz** [comment]
possibly fixed under [n8rzz#243](https://github.com/n8rzz/atc/issues/243)

**Comment by n8rzz** [comment]
@erikquinn this goes away after openscope/openscope#193
