### ISSUE TITLE
Add command to insert scratchpad text

### ISSUE THREAD

**Issue by felixscheffer** [openscope/openscope#1220]
After @n8rzz  finishes his work on #604, we should a command to change the scratchpad text.

Proposed format: `scratchpad [text] [CID or callsign]`

inspired by #1217

**Comment by erikquinn** [comment]
I swear this already works? Change to scope commands, and then type `i8r` or something and click the airplane, it should change the `._scratchpadText` value. Perhaps I'm mistaken, but I was pretty sure all we were missing was showing the scratchpad, which Nate's recent pull request will fix.

**Comment by felixscheffer** [comment]
Interesting. You are right. You can type in whatever you want and as long it's not a scope command we will consider it scratchpad text.
