### ISSUE TITLE
Using "fix" command yields legs with lower case route

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#123]
_From @erikquinn on December 15, 2016 6:49_

![image](https://cloud.githubusercontent.com/assets/5103735/21214422/aab56b30-c268-11e6-961b-fddc4d4953b3.png)

The casing should be consistent throughout all legs. And that which is printed to the ui log *must* be upper case.

_Copied from original issue: n8rzz/atc#208_

**Comment by n8rzz** [comment]
@erikquinn this goes away now that the `fix` command is gone, yes?

**Comment by n8rzz** [comment]
`fix` command removed as part of openscope/openscope#139
