### ISSUE TITLE
upgrade herkou stack (docker/docker-compose?)

### ISSUE THREAD

**Issue by n8rzz** [openscope/openscope#1230]
I'm starting to see the following in build logs of review apps:

```
 !   Warning: You are running on a deprecated stack.
 !   Please upgrade to the latest stack by following the instructions on:
 !   https://devcenter.heroku.com/articles/upgrading-to-the-latest-stack
```
This suggests we need to upgrade some things.  And if we're going to upgrade some things we might as well modernize a few things too with docker and/or docker compose.

see:
- https://devcenter.heroku.com/articles/container-registry-and-runtime
- https://devcenter.heroku.com/articles/local-development-with-docker-compose
- https://stackoverflow.com/questions/46904060/how-to-push-docker-containers-managed-by-docker-compose-to-heroku
- https://docs.travis-ci.com/user/docker/#Pushing-a-Docker-Image-to-a-Registry

**Comment by felixscheffer** [comment]
So we are basically talking about running openScope on Heroku in a docker container? If that's the case, that should be super easy to do.

**Comment by n8rzz** [comment]
Yep. Made even easier because in production we use nginx to serve static files.

This task will likely require some updates to our ci build process, but those look pretty straightforward too.

**Comment by n8rzz** [comment]
Current nginx config is used via heroku-static-buildpack, which is a wrapper for nginx 😷.  Our current attempts at configuration can be found in [`static.json`](https://github.com/openscope/openscope/blob/develop/static.json).

The error above calls out a deprecated stack.  according to `heroku apps:info`, we are currently running on `cedar-14`.  yikes, way old.

**Comment by n8rzz** [comment]
this might also be an option (https://github.com/beanieboi/nginx-buildpack).  It at least gets us closer to a real nginx configuration
