### ISSUE TITLE
Airport Revival: Washington Dulles International Airport (IAD) (KIAD)

### ISSUE THREAD

**Issue by doofus** [openscope/openscope#1236]
Update KIAD to playable configuration.

**Comment by doofus** [comment]
TODO: 

- [ ] Add rest of STARs
- [ ] get traffic data from script once fixed (https://github.com/indianbhaji/flightradar24)
- [ ] Add spawning for all STARS
- [ ] Add Spawning for all SIDS

**Comment by j-651** [comment]
All SIDs + STARs have been added.

Most STARs have aircraftSpawns now, however, due to conflicts on spawn, not all could be added.
