### ISSUE TITLE
Comma in between commands is not accepted

### ISSUE THREAD

**Issue by blane1257** [openscope/openscope#1239]
Commas placed in between commands should be accepted (they currently are not)

Example:
"[callsign] caf, to" responds with say again
it should be equivalent to "[callsign] caf to"

**Comment by n8rzz** [comment]
That is very much on purpose, commas are not allowed as part of a command string.  I'm not sure why you would want them?  If you can make the case, we can certainly discuss it, but this is currently working as designed.

**Comment by blane1257** [comment]
I frequently accidentally put commas inbetween commands and it doesn't make much sense for them to not be allowed.

**Comment by erikquinn** [comment]
Hi @blane1257! I agree with @n8rzz-- truth be told, it does sound simple enough to say that a comma shouldn't wreck the whole command, but the reality is that it is already a very complicated system that allows us to chain multiple commands together like this: `a 50 x t r 250 - 290 pd hoggs`. The simple fact of the matter is that, at this stage, it would not be worth the moderate addition of complexity in the logic to get it to successfully ignore commas. The most likely result of that change would just be more and more bugs, so I can't see a good reason to move in that direction.

Nonetheless, we appreciate the input. Often times these ideas take us to good places, but this change in particular is not one we ought to pursue.

Closing.
