### ISSUE TITLE
Timewarp with 2 spaces breaks everything

### ISSUE THREAD

**Issue by Fechulo** [openscope/openscope#1249]
Browser: Chrome

Airport: Any

#### Steps to reproduce
- Run `timewarp  5` (2 spaces between the command and the value)
- Observe everything break

**Comment by felixscheffer** [comment]
It's a feature, not a bug 😂

**Comment by felixscheffer** [comment]
The second space is converted to a number. The result is `NaN`.

**Comment by cake-pie** [comment]
The other system command that takes an argument is `airport`, and it also doesn't like extra spaces. Fails silently and harmlessly though.

Both could be made tolerant of extra spaces, which is how aircraft commands behave.

**Comment by JonasCir** [comment]
While testing the parser, I also noticed similar issues, I got this now on my list for my refactoring @cake-pie :D
