### ISSUE TITLE
Update the tutorial

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#1271]
The content of the tutorial could be improved. To the extent possible, we should make it faster to get through, while providing information which is more up to date with the current simulator version. It's been improved recently, but is still quite old in some parts.

Also:
- tutorial does taxi before caf, should swap these around

Continuation of #727.

**Comment by Marcel510** [comment]
![Screenshot_327](https://user-images.githubusercontent.com/24833249/69834472-e2299300-123a-11ea-9ced-e63999a5a6d9.png)
The tutorial still has an explanation about the wind sock which should be removed as the wind sock is not part of the sim anymore. (Replaced by the airport info #960)
Related: #1478
