### ISSUE TITLE
Add time to build information in html

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#1275]
Related: #1272.

The build information shown in the HTML has only the date of the build, but the time would be handy (say we just pushed a change, and somebody refreshed the app before it finished rebuilding-- when they say "it's still broken", it'd be nice to be able to verify that both the user and developer are running the same build).

![image](https://user-images.githubusercontent.com/5103735/50551292-55eaa680-0c4c-11e9-8cb6-0c63ea4f2b9b.png)

**Comment by n8rzz** [comment]
Easy, peasy...
