### ISSUE TITLE
Altitude commands not processed correctly

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#1279]
Clear somebody to 15000 and you'll see some odd responses. It appears to be that arguments are being improperly passed through the InputController to the AircraftCommander due to some recent change.

![image](https://user-images.githubusercontent.com/5103735/50563587-0cea2f00-0cec-11e9-9859-b3ba469c8824.png)

**Comment by kmartino2168** [comment]
Dropping this here in case it's of any use.
![image](https://user-images.githubusercontent.com/46123896/50566848-d1f3f580-0d03-11e9-9b56-f568ee236dde.png)

You can reproduce this by issuing `c <alt>` or `d <alt>` to any aircraft.  It only happens with altitudes outside your airspace (as demonstrated in the above image)-- if you climb an aircraft to an altitude inside your airspace, it works as it should.  

This happens with both departures _and_ arrivals, both on the ground and in the air.

[https://openscope-staging.herokuapp.com/](https://openscope-staging.herokuapp.com)

**Comment by erikquinn** [comment]
Seems to actually be unrelated to the stuff I posted, and appears to be localized to the altitude command.

**Comment by felixscheffer** [comment]
should be fixed in v6.9.0
