### ISSUE TITLE
Create getter in AircraftInstanceModel to get the current runway

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#129]
_From @n8rzz on December 19, 2016 2:34_

basically this:
```javascript
get activeRunway() {
    return this.rwy_dep 
        ? this.rwy_dep 
        : this.rwy_arr; 
}
```

to alleviate the need for this:
```javascript
const runway = airport.getRunway(this.rwy_dep || this.rwy_arr);
```

_Copied from original issue: n8rzz/atc#225_

**Comment by n8rzz** [comment]
completed as part of openscope/openscope#139

**Comment by erikquinn** [comment]
Rolled into #139.

**Comment by erikquinn** [comment]
Has `AircraftInstanceModel.initialRunwayAssignment`.
