### ISSUE TITLE
Cannot assign altitudes...

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#130]
_From @panther2 on December 19, 2016 15:37_

... to departing planes that have not been cleared by `caf` or `sid` before.

Experienced minutes ago on https://atc-release.herokuapp.com/

On https://zlsa.github.io/atc/
I am allowed to command altitudes even before `w` , `caf` or `sid` .

Is this intentional?

_Copied from original issue: n8rzz/atc#228_

**Comment by erikquinn** [comment]
_From @n8rzz on December 19, 2016 15:38_

@panther2 which airport? and what were the exact commands you used to cause this issue?

**Comment by erikquinn** [comment]
_From @n8rzz on December 19, 2016 15:43_

@erikquinn should it be possible to issue an altitude before a clearance?  It looks to me like this is erroring here:
<img width="686" alt="screen shot 2016-12-19 at 9 42 15 am" src="https://cloud.githubusercontent.com/assets/3325985/21318607/8864608a-c5cf-11e6-9bbf-0e5899ccf7fe.png">

because `fms.altitudeForCurrentWaypoint()` is null, because there is no current waypoint.

**Comment by erikquinn** [comment]
_From @panther2 on December 19, 2016 16:5_

@n8rzz 
I tested it at KSFO and EDDM.

From other simulations I have been kind of used to the possibility to assign the altitude no matter what command sequence before `to` .
This is why I ran into this issue.

I noticed it when using `a` or any other synonym.

1. even before `w`
2. after `w` but before `sid ...` 

When commanded after `w` and `sid ...` it was accepted.

**Comment by erikquinn** [comment]
_From @panther2 on December 19, 2016 16:16_

This is the error message I get:

![altitude_error](https://cloud.githubusercontent.com/assets/20812775/21319772/d4c01930-c60e-11e6-827a-03bfb69ff3d2.png)

Sorry, if this might be redundant...

**Comment by erikquinn** [comment]
There must always be at least one waypoint because otherwise this happens everywhere. Perhaps we could think about adding a console warning whenever the waypoints are removed or something, to help point to the method that cleared and didn't replace them.

**Comment by erikquinn** [comment]
And yes it should be possible

**Comment by n8rzz** [comment]
This needs to be rechecked, it may have been fixed in v4.0.0.

**Comment by erikquinn** [comment]
Issue no longer observed. Closing.
