### ISSUE TITLE
Refer to aircraft by their callsigns

### ISSUE THREAD

**Issue by sam-irl** [openscope/openscope#1300]
An idea I had, not sure if this is how things should work.

Controllers could issue a command:
`BAW123 caf to`
Then, we could use the aircraft's radio callsign instead of the 3-letter ICAO
`Speedbird 123, cleared to destination as filed, wind ${speed} at ${direction}, cleared for takeoff`

**Comment by erikquinn** [comment]
@sam-irl you mean for the textual readback to use "Speedbird" instead of "BAW"?

**Comment by sam-irl** [comment]
Yeah, that was the idea

**Comment by erikquinn** [comment]
Ok, gotcha. We discussed this somewhere I can't remember anymore, but decided against it for a couple reasons (saving space, consistency with the data blocks, no significant advantage, etc). It's a fair suggestion (which we appreciate), though it's one we opted not to go with.

Will close now as wontfix.
