### ISSUE TITLE
Clarify that TimeKeeper and GameController.game_timeout are using seconds (not milliseconds)

### ISSUE THREAD

**Issue by felixscheffer** [openscope/openscope#1308]
ref #762

**Comment by sam-irl** [comment]
unless it's beneficial to use milliseconds? i'm not sure it ends up making much of a difference though

**Comment by n8rzz** [comment]
My preference would be to use milliseconds everywhere because that’s the standard.

**Comment by felixscheffer** [comment]
@n8rzz Agreed but can we do this in a separate issue, please. Changing the `TimeKeeper` will be a tricky task and requires a lot of testing.

**Comment by n8rzz** [comment]
Absolutely. We want to be careful anything TimeKeeper related, as you said.

**Comment by erikquinn** [comment]
Resolved by #1310. Closing.
