### ISSUE TITLE
RDU arrivals

### ISSUE THREAD

**Issue by jonmkj** [openscope/openscope#1312]
Browser: Chrome

Airport: RDU

Approximate play time before issue: 0

#### Issue Description

Arrivals into RDU are often descending and calling up far too late, sometimes over or beyond the airport.

#### Steps to reproduce
-

**Comment by sam-irl** [comment]
Hello, @jonmkj. Thanks for reporting this issue. Unfortunately, I can't seem to reproduce it. Would you mind sharing some screenshots, and reporting which STAR(s) the arrivals were approaching from? thanks
