### ISSUE TITLE
Mark deep render when aircraft is (de)selected

### ISSUE THREAD

**Issue by sam-irl** [openscope/openscope#1316]
Playing v6.10 prod.

The compass around the screen does not appear when selecting an aircraft. Instead, i have to scroll to get it to render. Same goes for de-selecting an aircraft.

**Comment by erikquinn** [comment]
Sounds like we need to mark a deep render whenever the compass needs to be drawn.

**Comment by erikquinn** [comment]
Being fixed a different way in #1422. Closing.
