### ISSUE TITLE
Create SpawnScheduler class

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#133]
_From @n8rzz on December 22, 2016 1:2_

used to register spawns for departures and arrivals created with data from airport json.  

- should be a collection of `setInterval()`s each with some sort of a createAircraft callback
- callback should be called with info defined in departure/arrival section of airport.json
- interval delay is from frequency defined in airport.json
- intervals should be cancelable
- intervals should clear when an airport is changed
- should not create/destroy anything other than intervals
- tests

_Copied from original issue: n8rzz/atc#235_

**Comment by erikquinn** [comment]
_From @n8rzz on January 13, 2017 4:36_

n8rzz/atc#243

**Comment by n8rzz** [comment]
finished here: https://github.com/n8rzz/atc/issues/235
