### ISSUE TITLE
Allow left click to drag

### ISSUE THREAD

**Issue by binaryfunt** [openscope/openscope#1330]
Following [#564](https://github.com/openscope/openscope/issues/564) the behaviour is right-clicking and dragging moves the map. This works ok on a mouse, but on a touchpad it is rather difficult. There should be an option to change it to left-click and drag.

**Comment by erikquinn** [comment]
I can see that. We'll disable by default, but seems like a good addition.

**Comment by sam-irl** [comment]
Oddly enough, we do have a `MOUSE_CLICK_DRAG` defined in the game option constants, so I'd imagine this was an option that was removed. Shouldn't be too difficult to re-add
