### ISSUE TITLE
List openscope on lutris.net (add logo and description)

### ISSUE THREAD

**Issue by stooj** [openscope/openscope#1339]
Hi

I've added a listing for [openscope on lutris](https://lutris.net/games/openscope-air-traffic-control-simulator/). Hopefully it will increase the visibility of the project, which I just discovered while looking for atc tutorials.

The lutris page is missing an official blurb for the game, as well as a logo. Do these things exist yet?

Thanks

**Comment by felixscheffer** [comment]
Thanks.

I think the only logo we have right now is https://github.com/openscope/openscope/blob/develop/assets/images/openscope-radar-sweep.gif

**Comment by stooj** [comment]
Thanks.

I don't think the radar will be illustrative enough (lutris asks that the name of the game be included in the logo) but I'll maybe try and put something together and see if you approve.

**Comment by n8rzz** [comment]
There is also our loading screen?

<img width="552" alt="Screen Shot 2019-03-14 at 4 54 01 PM" src="https://user-images.githubusercontent.com/3325985/54394065-d03a9c80-4679-11e9-9464-f26906d7bb5f.png">

But that isn't an actual logo and is laid out with html and css.  Sorry we can't be more helpful at the moment, we haven't put too much thought into marketing.  Perhaps that's something we should look into in the near future?

**Comment by stooj** [comment]
Thanks n8rzz - I'll submit the loading screen for review.
