### ISSUE TITLE
Include Airline id in airline json file

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#134]
_From @n8rzz on December 23, 2016 4:22_

The only place this `id` (listed as `icao` in `AirlineModel`) comes from is the filename. this id should also exist within the airline json file for easy reference.

_Copied from original issue: n8rzz/atc#242_

**Comment by erikquinn** [comment]
_From @n8rzz on January 13, 2017 4:34_

n8rzz/atc#243

**Comment by n8rzz** [comment]
finished here: https://github.com/n8rzz/atc/issues/243
