### ISSUE TITLE
LSZH (Zurich) Arriving planes not descending

### ISSUE THREAD

**Issue by jayayedee** [openscope/openscope#1355]
Browser: Google Chrome

Airport: LSZH

Approximate play time before issue: As soon as arrivals begin to spawn

Arriving aircraft appear, usually higher than FL200 and enter their assigned holding pattern, but they do not descend. This did not happen on the previous release.

**Comment by Marcel510** [comment]
I checked all the altitude restrictions thus this should be an issue of the descent logic

**Comment by erikquinn** [comment]
May need to finish #952 (bugfix #943) and push it as a hotfix as the fix to this issue. There are almost definitely some unpleasant conflicts between it and a recent set of changes though, so it may be a few days.

**Comment by jayayedee** [comment]
More information - I just tried LROP (Bucharest). Planes entering the airspace at TOSVI say they are cleared to 2,500 ft so I do not issue any command. They stay at their original altitude for a while, descend to 7,000 ft, stay there for a few minutes and then descend to 2,500 ft.

**Comment by erikquinn** [comment]
After some investigating, this is a problem specific to LSZH (at least for now). What needs to happen isn't something the sim is currently capable of doing. I'm not sure at this early point how we could handle it, but here's the situation:

One of the really high arrivals are on the following route: `KOGOL.UL608.KPT.UL856.RAVED.NEGRA1A.LSZH14`. The NEGRA1A arrival has a built-in hold at AMIKI, at or above 7,000. For some reason, aircraft are not descending out of cruise. Obviously, FL260 is "at or above 7000", but the logic should have them descending to the "bottom altitude" (lowest altitude that complies with the restrictions-- more or less).

If need be, we can always just spawn the aircraft at the altitude we want them to enter the airspace at, but further thought is needed to be sure.

**Comment by erikquinn** [comment]
#952 is not fixing this at the moment. Further investigation is needed.

**Comment by erikquinn** [comment]
Another example is aircraft on the BLM2G arrival:

**Comment by erikquinn** [comment]
Discussed with @Fechulo and the only way forward seems to be to amend the STARs. I did so in #952, and documented the changes in the airport guide, under the section "Deviations from Reality".

**Comment by erikquinn** [comment]
#952 has been merged, so this is resolved. Closing.
