### ISSUE TITLE
Aircraft command reference departure sequence

### ISSUE THREAD

**Issue by guyndumais** [openscope/openscope#1356]
The departure sequence in [aircraft command reference](https://github.com/openscope/openscope/blob/develop/documentation/aircraft-commands.md) page is presently CAF-CVS-TO-TAXI. The taxiing of course must happen first.

**Comment by erikquinn** [comment]
The commands are sorted alphabetically, since other sections aren't as easily sorted by "order they happen in". So we'll leave it as is.
