### ISSUE TITLE
Configuring overall or individual route traffic rate to 0 and back up to x leaves queue empty for rest of simulation

### ISSUE THREAD

**Issue by guyndumais** [openscope/openscope#1358]
Browser: Chrome
Airports: KSFO, KDCA, EGCC [openscope-dev-pr-1328
](https://openscope-dev-pr-1328.herokuapp.com/) environment from #1327 . KDCA and EGCC in [prod ](http://www.openscope.co/)environment
Approximate play time before issue: immediate

#### Issue Description
Configuring overall departure rate in traffic dialog from 1 to 0 to 1 leaves departure queue empty for rest of simulation.

#### Steps to reproduce
In traffic rate dialog.
- overall departure rate to 0
- close dialog
- open dialog
- overall departure rate to 1
- timewarp 60
- watch departure queue at it remains empty for rest of simulation

**Comment by guyndumais** [comment]
Any individual/overall arrival or departure rate brought down to zero and then up to any number leaves the arrival/departure queue for route(s) empty for rest of simulation

**Comment by sam-irl** [comment]
Able to reproduce on prod at ksea

**Comment by felixscheffer** [comment]
@erikquinn You have to be more careful with your last second changes...

```
        if (!scheduleId || scheduleId === INVALID_NUMBER) {
            return;
        }
```
will prevent the recreation of the timer.

**Comment by erikquinn** [comment]
Ah, yes this one does look to be my bad. Sorry about that... :grimacing:

**Comment by erikquinn** [comment]
#1359 has been merged. Closing.
