### ISSUE TITLE
Aircraft Not Squawking Assigned Code

### ISSUE THREAD

**Issue by SmartMuffin** [openscope/openscope#1363]
**Browser**: Google Chrome

**Airport**: All airports

**Approximate play time before issue**: Occurs right away

**Problem**:
Many times when I try to assign an aircraft a squawk code (eg. "ABC123 squawk 1607"), it responds with a "command not recognized", "cannot squawk assigned code", or something similar. I know squawk codes don't have any real purpose right now, but it would still be nice for nerds like me.

**To reproduce**:
Just assign an aircraft any non-reserved, valid squawk code.
For example, "DAL8121 squawk 1629" doesn't always work.

**Comment by felixscheffer** [comment]
Thanks for reporting. 

The regex in `_isValidTransponderCode` fails/works every second attempt due to a fancy bug in javascript's regex engine.
 
https://stackoverflow.com/a/3891672/569040
http://blog.stevenlevithan.com/archives/es3-regexes-broken

**Comment by n8rzz** [comment]
I was wondering about that when I looked at your changes.  Good find!
