### ISSUE TITLE
ABQ generates initial traffic that collides

### ISSUE THREAD

**Issue by NathanDJohnson** [openscope/openscope#1366]
Aircraft are generated at the same position and collide at the following airports:
- [x] EGGW
- [x] EGNM
- [x] ENGM
- [x] KABQ
- [x] KATL
- [x] KAUS
- [x] KBOS
- [x] KCVG
- [x] KMCI
- [x] KPIT
- [x] KRDU
- [x] KSTL
- [x] LROP
- [x] LTBA
- [x] OMDB

**Comment by erikquinn** [comment]
😕

There's actually _tons_ of them with conflicting spawn patterns that I didn't fix? Probably I must not have gone back and checked after updating with develop? Not sure, but the list of ones to go through (again) is now longer. Edited issue description to include all affected airports.

**Comment by erikquinn** [comment]
#1366 was merged. Closing.
