### ISSUE TITLE
Create an AppController

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#137]
_From @n8rzz on December 31, 2016 18:10_

We need a class that can act as a conductor between the `App`, with the game loop, and everything else.  This class would be responsible for orchestrating initial data load, airport change as well as providing a launching point for additional view classes that we will need in the future.

Instead of `App` creating all the top level classes, `App` would instantiate this class and it would then create everything else.

- [x] accepts `$element`, `airportLoadList`, `initialAirportIcao` as parameters
- [x] provides facade methods that are run within the `App` game loop
- [x] provides callback method(s) that can be sent to various classes for handling events (ex: airportChange)

_Copied from original issue: n8rzz/atc#252_

**Comment by n8rzz** [comment]
blocked by #483 (this issue contains changes in `App.js` and could cause conflicts with work to be done here)
