### ISSUE TITLE
KBOS Arrivals giving crosswind penalties

### ISSUE THREAD

**Issue by JPmAn24** [openscope/openscope#1378]
Browser: Chrome

Airport: Boston Logan International Airport (KBOS)

Approximate play time before issue: 

#### Issue Description 
When an aircraft on the ROBUC3 arrival is cleared to land on 27 (as they filed), the simulator gives a crosswind alert.

#### Steps to reproduce
- Wait for an aircraft to become on your control from the JFK.ROBUC3.KBOS27 spawnPattern.
- Clear it to land on 27
- Points deducted due to crosswind

Recommended change is to move the wind to 240@18 instead of 230@18.

**Comment by erikquinn** [comment]
https://github.com/openscope/openscope/blob/develop/src/assets/scripts/client/game/ScoreController.js#L173

Currently, it's considered a high crosswind operation if the crosswind component is greater than 10 knots.
