### ISSUE TITLE
KDCA Reagan sim -200 penalty from approach initial conditions of IRONS7

### ISSUE THREAD

**Issue by guyndumais** [openscope/openscope#1389]
Browser: Chrome

Airport: KDCA Reagan

Approximate play time before issue: less than 1 minute

#### Issue Description
Just after starting KDCA simulation, a plane approaching from IRONS7 is at flight level 70, when crosses R-6601 with minimum FL90 gives 200 penalty points.

#### Steps to reproduce
- Start KDCA simulation
- wait 1 min and watch airplane at bottom 7000ft from IRONS7
- when airplane crosses R-6601 border a 200 penalty ensues

Version : 6.12.3

**Comment by guyndumais** [comment]
Singled out IRONS7 approaches at high timewarp. Well over 50% of planes approaching from IRONS7 cross R-6601 under FL90.
![kdca_approach_to_low](https://user-images.githubusercontent.com/41495897/58362585-a4504a00-7e66-11e9-8346-4a5471c78768.jpg)

**Comment by JPmAn24** [comment]
How about adding a height restriction to the STAR?

**Comment by erikquinn** [comment]
Arrivals on the IRONS star would not be at 7000 if R6601B and C were hot. They are hot only by NOTAM, and it's only the R6601A that's hot daily, from the surface to but not including 4,500MSL.

R6601 ceiling should be set to 4500, and renamed to R6601A to resolve the issue.
