### ISSUE TITLE
E135 on the glideslope keeps high speed, then goes around because of it

### ISSUE THREAD

**Issue by Progman2002** [openscope/openscope#1398]
Related: #1228.

Browser: Firefox Quantum 67.0 (64-bit)

Openscope: v6.13.0

Airport: EDDH

Approximate play time before issue: 30 minutes game time

#### Issue Description

The E135 aircraft keeps the high airspeed of about 260kt on the glideslope until about ~1800ft. Then it tries to slow down, but can't slow don't in time an issue a go around. This issue is related to https://github.com/openscope/openscope/issues/1228. Other aircrafts slow down earlier and have enough time to slide down in time and land successfully.

I tried it with different altitudes to intercept the localizer. When I let it intercept at 4000ft it will use the glideslope as expected, but it does not slow down until it is too late. The aircraft should slow down on the glideslope sooner. If I lower the speed manually with something like "CALLSGN - 170" it can land successfully.

#### Steps to reproduce

* Spawn/wait for an E135 aircraft
* Intercept the localizer at different altitudes like 2000ft, 3000ft or 4000ft.
* Watch the aircraft going down the glideslope, keeping about 260kt speed.
* Aircraft goes around at ~1800ft or ~8nm to the runway, going back to 3000ft.

**Comment by Progman2002** [comment]
It looks like the E545 has the same problem.

**Comment by erikquinn** [comment]
@Progman2002 Thanks for the report. Just to clarify, you DO get a red message from these aircraft stating they are going around, right? Just trying to ensure this is a different issue than #1395.

**Comment by Progman2002** [comment]
@erikquinn Yes, I get the red message that the aircraft is going around. The aircraft was long enough on the localizer/glideslope before the go around, so it was not an issue that the airplane turned final too short or too steep. It looks like the aircraft doesn't slow down enough based on its own performance and the glideslope angle. If I babysit the airplane by assigning it a lower airspeed, it can land.

**Comment by erikquinn** [comment]
Got it, thanks for the clarification. Definitely a different issue then. 👍

**Comment by jhgravelle** [comment]
Same issue with the DH8D at Seattle.

**Comment by erikquinn** [comment]
Also SF20

**Comment by railsetc** [comment]
Same issue with DH8D at KPDX, but thank you to Progman2002 for the note on manual speed command.
