### ISSUE TITLE
Automatic GND and TWR control

### ISSUE THREAD

**Issue by jakcharvat** [openscope/openscope#1405]
Try and introduce automatic taxi and takeoff instructions if the user enables the option.

**Comment by JonasCir** [comment]
@erikquinn 
One question: Will there be an option to enable/disable this feature depending on the user's preference :smile: ?

**Comment by erikquinn** [comment]
Yes! Just didn't add it yet. Ran out of time yesterday.

**Comment by MemphisDon17** [comment]
I'm getting conflict notices from my automatic departures.  Is this by design?
![Openscope](https://user-images.githubusercontent.com/66389837/121258797-f2c9b900-c874-11eb-8a50-ef93fca404fb.jpg)
