### ISSUE TITLE
Traffic flow

### ISSUE THREAD

**Issue by Stiker839** [openscope/openscope#1408]
Browser: Chrome

Airport: EGCC

Approximate play time before issue: 5Mins

#### Issue Description

When I set the traffic flow for EGCC to zero to stop / slow down the number of aircraft, the game then swamps my game with on average 45 inbound and outbound aircraft and I cant put them into holds fast enough before they start hitting each other .

#### Steps to reproduce
Set all traffic rates to zero and play on EGCC and after a few mins the traffic flow will shoot up to about 45 aircraft under your control.

![image](https://user-images.githubusercontent.com/43455345/60840808-35397580-a1c8-11e9-9f6e-ba40843cc5ae.png)

**Comment by erikquinn** [comment]
Well that doesn't sound good... :grimacing:

**Comment by Watchdog753** [comment]
Any update on this?

**Comment by cake-pie** [comment]
Unable to reproduce on Chrome, recent version (87).
Sliders working correctly, further spawns stopped when set to zero.

I considered OP might have accidentally bumped the slider to a larger value for a brief moment while adjusting it to zero, but that does not seem to be the likely cause. OP reported 45 aircraft; it takes >1h at 1× spawn rate and 7 min at 10× spawn rate to accumulate that many.

---

### Test 1: traffic rate sliders work correctly
As per #1427 there is an unusually high number of initial spawns and I have 17 arrivals on the way and 3 departures on the apron, but no additional aircraft spawn after the spawn rate is changed.

Steps as follows:
- `airport egcc` to change/reload to Manchester
- open traffic rate window
- bump both arrival and departure sliders from 1 to 0
- timewarp and observe

### Test 2: how quickly do aircraft accumulate?
At 1× spawn rate, after 1 hour of simulation time, accumulated about 40 aircraft in total: 19 initial spawns +20 additional.

Steps as follows:
- `airport egcc` to change/reload to Manchester
- note time at top left info box `1602/XX` and 19 aircraft from initial spawns
- do not adjust traffic rate, do not issue any commands, just to see how quickly aircraft will accumulate
- timewarp until time `1612/XX` i.e. 10 min elapsed
- note 23 aircraft: 5 departures on the ground, 18 arrivals
- timewarp until `1632/XX`. 30 min elapsed, there are now 26 aircraft in total
- timewarp until `1702/XX`. 1 hr elapsed, there are now 39 aircraft in total

Similarly, at 10× spawn rate, it took around 6~7 min simulation time to accumulate 45 aircraft in total: 19 initial spawns +26 additional.
