### ISSUE TITLE
Option to set maximum aircraft under your control 

### ISSUE THREAD

**Issue by caolan753** [openscope/openscope#1409]
Browser: Chrome

Airport: All Airports

Approximate play time before issue: 0

#### Issue Description

It would be nice to set a maximum limit to the maximum aircraft that you control, as EGCC 1 controller would not be controlling 20 simultaneous aircraft as it would be spread over multiple controllers. 

This feature would allow new players not get overwhelmed and would let them play at their speed, and it would also help to make the game more realistic interns of controller work rate.

#### Steps to reproduce
-

**Comment by erikquinn** [comment]
Hi @caolan753! At the moment, this is handled by the ability to change the spawn rate of aircraft as well as deleting them using the `del`/`delete`/`kill` command. It's true it can be too much sometimes but everyone's limits are different and there are already controls in place to help you meter the traffic, so we won't be pursuing this change. Nonetheless, I appreciate the input, and advise of any other changes you think we could use!

Closing.
