### ISSUE TITLE
correct CSS rules

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#141]
_From @n8rzz on January 15, 2017 4:35_

There are un-needed properties in the existing css.  Things like:
```css
position: absolute,
display: inline-block
```

- [x] remove duplicative/irrelevant styles
- [x] correct spacing (4 spaces)
- [x] remove empty lines within rules

_Copied from original issue: n8rzz/atc#258_

**Comment by n8rzz** [comment]
This has been addressed by several other merged PRs
