### ISSUE TITLE
build:scripts:server fails to copy server.js to public/

### ISSUE THREAD

**Issue by n8rzz** [openscope/openscope#1410]
running `npm run build` fails to copy `server/index.js` to the destination directory

**Comment by wrksx** [comment]
Wainting for PR#1410, if anyone needs the fix for this, change tools/tasks/scriptTasks.js:36 to this
```js
const buildServer = () => gulp.src('**/*.js', {cwd: OPTIONS.DIR.SRC_SCRIPTS_SERVER})
```
Instead of
```js
const buildServer = () => gulp.src([path.join(OPTIONS.DIR.SRC_SCRIPTS_SERVER, '**/*.js')])
```
Worked for me on windows 8.1 (using cygwin).
