### ISSUE TITLE
KCVG arrivals colliding

### ISSUE THREAD

**Issue by JPmAn24** [openscope/openscope#1428]
Browser: Google Chrome

Airport: KCVG

Approximate play time before issue: Immediately

#### Issue Description
The arrivals on a few different patterns collide on entry into airspace. For example, the BRUSH3 and GAVNN4 arrivals have aircraft spawn on top of each other.

Suggested fix: Consolidate spawnPatterns on top of eachother into one.

#### Steps to reproduce
- Load KCVG
- Wait for first arrivals to arrive

**Comment by erikquinn** [comment]
See comments on #1429. Closing.
