### ISSUE TITLE
Aircraft exiting hold after entry in beta

### ISSUE THREAD

**Issue by oobayly** [openscope/openscope#1432]
Browser:
Chrome: Version 75.0.3770.100 (Official Build) (64-bit)
OpenScope version: devel (yes I know
Airport:
EGCC, LSZH

Approximate play time before issue:
Immediate

#### Issue Description

Aircraft enter a hold as expected, but never return back to the fix to complete the circuit, and continue on (eventually leaving the area). Holding works as expected in v.6.13
I've noticed that a lot of work regarding wind has been done between v.6.13 and devel, but I haven't found out when the regression was caused as I've only started perusing the code.

#### Steps to reproduce

Allow an aircraft to enter a procedure hold, or explicitly command a hold.

**Comment by wrksx** [comment]
I've been looking at the hold logic lately. If I recall correctly a timer is supposed to trigger the turning back. I didn't look at what starts the timer but I got a feeling that might be related to this issue.

**Comment by wrksx** [comment]
Just took another look and there is this condition that starts the timer, I added a console.log right before the condition:
```
console.log('Outbound heading:', outboundHeading, 'heading:', this.heading);
if (this.heading === outboundHeading && !isTimerSet) {
    currentWaypoint.setHoldTimer(gameTime + holdLegDurationInSeconds);
}
```
Here is the log of the heading and the outboundHeading at the end of the first turn:
```
Outbound heading: 1.88388441870136 Aircraft heading: 1.8216399454119323
Outbound heading: 1.88388441870136 Aircraft heading: 1.8268760530141814
Outbound heading: 1.88388441870136 Aircraft heading: 1.8739997730776619
Outbound heading: 1.88388441870136 Aircraft heading: 1.879235880679911
Outbound heading: 1.88388441870136 Aircraft heading: 1.891802339188227
Outbound heading: 1.88388441870136 Aircraft heading: 1.8980853187710327
```
The heading 'jumps' from 1.87 to 1.89 (radians) and is never strictly equals to the outbound heading, thus the condition is not met and the timer never starts.

I think that trying to match so precisely to a heading is not right, what do you think? Maybe we could have a condition to detect crossing of the `outboundHeading ` based on the direction of the turn, or detect that the `aircraft.heading` is within 0.005 radians (a bit more than a quarter of a degree) of the `outboundHeading`.

I don't know why it stoped working though, maybe the `aircraft.heading` used in this code is affected by the wind...

**Comment by oobayly** [comment]
Good find - it would have taken me a lot longer to find even where to start looking as this is new to me, I wonder if some rounding was done previously. I'll have to checkout v.6.13 and add the logging as you've done in the previous version.

**Comment by wrksx** [comment]
I actually took me a lot of time to find this logic, I delved into it since I'm working on an issue related to holding patterns, issue #1318. I'm glad it's helpful =)
Maybe @erikquinn can help us find out if it's related to latest wind corrections.

**Comment by oobayly** [comment]
Yup, it's the winds. Testing with EGGW - Luton, holding at ABBOT from the ABBOT2B STAR, 10,000ft 220KIAS, I get the following:
```
Version  Outbound                  Heading                        Notes
v.6.13.0 1.3083092129257088 1.3083092129257088
v.6.14.0 1.3083092129257088 1.3141188128138317 Wind 9 kts @ 247°
v.6.14.0 1.3083092129257088 1.3083092129257088 Wind 0kts

I need to delve in a bit deeper to get the actual speeds to accurately work out the vectors, but what is confusing is that a rough estimate of subtracting the vectors means that the wind component is only about 1.6kts which can't be correct (unless I'm making a schoolboy error). Especially if the new version is simulating winds aloft (which is suggested by some commits I've read) as winds should be higher than surface.

Another thing that surprises me is that the equality operator at all worked in the first place. I admit that I'm not au fait with code, so maybe there's some normalisation going on somewhere. Or, perhaps the a/c heading was being taken from the outbound course, so equality worked, but is now broken by the new window routines.

**Comment by n8rzz** [comment]
I'd really love to move away from that amount of precision some day

**Comment by wrksx** [comment]
If I'm correctly understanding your data, you are nearly facing the aircraft so I'm not really surprise

**Comment by oobayly** [comment]
Face palm - I was taking the speed from video map, which of course is to the nearest 10kts. Hence the vector components for the a/c are highly inaccurate. Rubbish in, rubbish out...

So, while updating to dump the actual speeds, I found the `AircraftModel.groundTrack` property.
```
KIAS | TAS | Alt | Heading | Ground Track | Outbound
220 | 255.2 | 10000 | 1.3141188128138317 | 1.3083092129257086  |1.3083092129257088
```

As you can see, the `AircraftModel.groundTrack` is pretty much the same as the outbound heading, but not exactly the same, so I've added a `HOLD_HEADING_THRESHOLD`  constant (currently set to 0.001°, and done the following.

``` diff
diff --git a/src/assets/scripts/client/aircraft/AircraftModel.js b/src/assets/scripts/client/aircraft/AircraftModel.js
index 6b49c05..fa67cb8 100644
--- a/src/assets/scripts/client/aircraft/AircraftModel.js
+++ b/src/assets/scripts/client/aircraft/AircraftModel.js
@@ -89,6 +89,14 @@ const FLIGHT_RULES = {
 };
 
 /**
+ * The allowed threshold when comparing ground track to hold outboundHeading.
+ * @property HOLD_HEADING_THRESHOLD
+ * @type {Number}
+ * @final
+ */
+const HOLD_HEADING_THRESHOLD = (0.001 * Math.PI / 180);
+
+/**
  * Each simulated aircraft in the game. Contains a model, fms, and conflicts.
  *
  * @class AircraftModel
@@ -1983,6 +1991,7 @@ export default class AircraftModel {
 
         const { inboundHeading } = holdParameters;
         const outboundHeading = radians_normalize(inboundHeading + Math.PI);
+        const groundTrack = radians_normalize(this.groundTrack);
         const offset = getOffset(this, waypointRelativePosition, inboundHeading);
         const holdLegDurationInMinutes = holdParameters.legLength.replace('min', '');
         const holdLegDurationInSeconds = holdLegDurationInMinutes * TIME.ONE_MINUTE_IN_SECONDS;
@@ -2001,7 +2010,7 @@ export default class AircraftModel {
 
         let nextTargetHeading = outboundHeading;
 
-        if (this.heading === outboundHeading && !isTimerSet) {
+        if (Math.abs(groundTrack - outboundHeading) < HOLD_HEADING_THRESHOLD && !isTimerSet) {
             currentWaypoint.setHoldTimer(gameTime + holdLegDurationInSeconds);
         }
 
````

Any comments?

**Comment by wrksx** [comment]
- You can use the function `degreesToRadians()` from `src/assets/scripts/client/utilities/unitConverters.js` to define your `HOLD_HEADING_THRESHOLD ` constant.
- It occured to me that most of the constants are defined in the `src/assets/scripts/client/constants/` directory, maybe it would be better to move yours there, not quite sure where though.
- Do you really need to `radians_normalize()` the groundTrack?
- Maybe better to use `abs()` from `src/assets/scripts/client/math/core.js` instead of a direct call to `Math.abs()`, not sure why but it's there for a reason.

**Comment by oobayly** [comment]
Thanks for the suggestions.
* I've moved the const in to `PERFORMANCE.MAXIMUM_ANGLE_CONSIDERED_ESTABLISHED_ON_HOLD_COURSE` to match the naming of other consts, as well as using a literal radians value, with a comment explaining the value (as is done elsewhere).
* Normalizing is necessary as the `AircraftModel.groundTrack` can be negative. As I found out when some holds weren't working.

**Comment by erikquinn** [comment]
Exactly, you guys found it. If you're on develop, you'll have the groundTrack and heading properties correctly calculated. The heading is the direction the aircraft is physically pointed, and the direction of travel is the ground track.

It should be hella accurate comparing the groundTrack with the outboundHeading, only off by floating point error levels (you can use Number.EPSILON). I'd be surprised if it was any more than that.

**Comment by oobayly** [comment]
@erikquinn I've just tried using Number.EPSILON as suggested, started up EGCC and created holds at a variated of fixes along procedures. Unfortunately I have already had a _"escapees"_. Some of the a/c hold successfully, but others don't do their turn. Looking at the abs() result, I'm also getting values of 2 * Number.EPISLON, possibly because I'm having to pass groundTrack through radians_normalize.

So the question is what multiple of Number.EPSILON to test against...

**Comment by wrksx** [comment]
Not fluent in floating point math, but I think the subtration `groundTrack - outboundHeading` might generate additional rounding error (due to the subtraction).

**Comment by erikquinn** [comment]
Hm, okay. I guess that makes sense. In that case, some hard value tolerance is probably appropriate. Something in the realm of a tenth of a degree or less ought to be plenty.

**Comment by oobayly** [comment]
Ok, thanks, I'll update to 0.1° and push. @n8rzz mentioned adding some tests, but I'm afraid I have no idea of where to start with that.
