### ISSUE TITLE
Cursor issue

### ISSUE THREAD

**Issue by KodiakChaos** [openscope/openscope#1438]
Browser: Microsoft Edge

Airport: All

Approximate play time before issue:

#### Issue Description
When I click on an aircraft for it to put it's call sign in the command box the cursor is in front of the call sign instead of behind. Also I have noticed the first letter I type doesn't always show up after clicking an aircraft.

#### Steps to reproduce
-

**Comment by erikquinn** [comment]
Hi @kodiakchaos! Thanks for the report. We are aware of the issue, and have it documented in #23. We'll do the work on that issue, and I'll close this one so we don't have multiple for the same problem.

Closing as duplicate of #23.
