### ISSUE TITLE
create RouteBuilder class and smooth out RouteModel

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#144]
_From @n8rzz on January 16, 2017 1:7_

from n8rzz/atc#251 :
>Way I see it, the RouteModel should be all encompassing of an entire "route", and the individual pieces are another class. Here, RouteModel is really being used like what I would call a 'RouteSegmentModel' or 'SimpleRouteSegmentModel', which differs from a 'ProcedureRouteSegmentModel'. An array of these things should make up a 'RouteModel'

_Copied from original issue: n8rzz/atc#262_

**Comment by n8rzz** [comment]
@erikquinn I've been raking my brain the last few days trying to figure out what exactly this should do.  Here is what I have in my head so far:
- a `RouteModel` class that accepts a `routeString` as provided by `spawnPattern.route` (or somewhere else).
- a helper function breaks up that `routeString` into `simple` and `procedure` route segments. (`FIXX` vs `FIXA.STAR.FIXX`)

And thats where I get stuck.  What should we do from there?  I know these are going to be used by the FMS, so eventually we will need to turn these strings into something useful like a `FixModel` or a `Waypoint` or something else.  Should this thing actually build `Legs` and their `Waypoints`?  Do we even need those classes anymore?

Ugh, I guess I need to think on this one some more.  What are your thoughts?

**Comment by n8rzz** [comment]
addressed under openscope/openscope#139

**Comment by n8rzz** [comment]
this does exist and was completed under #139, but it is tightly coupled to the `Fms` as a class method.  If we need this in the future this could be abstracted out to a helper function.

**Comment by erikquinn** [comment]
@n8rzz So what shall we do with this issue once 139 is merged?

**Comment by n8rzz** [comment]
Close it, I don't think we'll need it as originally described here.
