### ISSUE TITLE
Dev.openscope.io - Blank Radar field

### ISSUE THREAD

**Issue by wmstapp** [openscope/openscope#1443]
Browser: google Chrome

Airport:  All 

Approximate play time before issue:  at load

#### Issue Description
Radar field is blank... after toggling Video Map on and off, aircraft appear; however nothing else does.  Tried multiple reloads and multiple airports.  Also tried toggling "Fix and runway Labels" and "terrain" on/off.
![OpenScope](https://user-images.githubusercontent.com/45436083/65335106-6c91ae80-db89-11e9-93bc-a05ca2895572.PNG)

#### Steps to reproduce
-

**Comment by oobayly** [comment]
I can't reproduce that, but the video maps format has been updated. It's possible the old airport *.json files have been cached. Have you tried a Ctrl-F5 to bypass the cache?

**Comment by JPmAn24** [comment]
Just had this happen to me too. The errors that I was seeing in the console (F12 menu) showed an error of not being able to find the length of an undefined array. The errors showed `CanvasController.js:1493 Uncaught TypeError: Cannot read property 'length' of undefined`. Could this be related to the work done on #1437 ?
