### ISSUE TITLE
Headings outside of 001-360 should be rejected

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#1456]
Telling aircraft to fly headings which don't exist, eg `fh -90`, `fh 0`, `fh 380`, etc, will all result in aircraft determining the appropriate heading, eg `-90 --> 270`, `0 --> 360`, `380 --> 020`. But it should be rejecting these inputs because they are most likely an erroneous input that was not intended (eg `fh 1230` when they meant `fh 130`-- the aircraft will normalize a 1230 degree heading to 150 degrees, which was not the intent).

- Inputs <= 0 should be rejected
- Inputs > 360 should be rejected

**Comment by oobayly** [comment]
This can use some of the validation logic as #1451, namely `isValidCourseString`. Is it worth waiting for that to be merged into develop so there's no code duplication?
