### ISSUE TITLE
Wind sock is either not displayed or unable to find

### ISSUE THREAD

**Issue by odiferousmint** [openscope/openscope#1478]
Browser: Chromium
Airport: any
Approximate play time before issue: N/A

#### Issue Description

Wind sock does not seem to be displayed in the "lower right corner" as the tutorial suggests, or perhaps I am blind. :P

Screenshot: https://i.imgur.com/FPpSI39.png

**Comment by Marcel510** [comment]
The wind sock has been replaced by the airport info view in the top left corner which indicates the wind direction and the wind speed.
![Screenshot_326](https://user-images.githubusercontent.com/24833249/69834415-7810ee00-123a-11ea-9a54-237ee9ff1c1e.png)
The tutorial should be updated though.
