### ISSUE TITLE
Fix z-index of the command popup menu

### ISSUE THREAD

**Issue by oobayly** [openscope/openscope#1480]
Browser:
* Firefox 70.0.1 (64-bit)
* Chrome 8.0.3904.108

Airport: All

Approximate play time before issue: Immediate

#### Issue Description
#1191 (Consolidate command bar buttons) shows a popup menu, but this is hidden behind StripView list.
![image](https://user-images.githubusercontent.com/3430117/69951562-6145f200-14ed-11ea-9b45-8fddaf45209d.png)

#### Steps to reproduce
Expand the StripView list and then click on any of the command buttons that have a popup menu.

#### Fix
A very simple fix is to increase the z-index of the `.controls-menu` class (currently 2) to be greater than the `.stripView` (currently 100)

``` diff
--- a/src/assets/style/module/controls/_controls.less
+++ b/src/assets/style/module/controls/_controls.less
@@ -3,7 +3,7 @@
     margin: 0;
     padding: 0;
     overflow: hidden;
-    z-index: 2;
+    z-index: 125;
 }
```

![image](https://user-images.githubusercontent.com/3430117/69951796-d9acb300-14ed-11ea-9dff-31d94c306acb.png)

**Comment by erikquinn** [comment]
Resolved by #1481. Closing.
