### ISSUE TITLE
Popup for event history / logs and/or setting to change fade-out delay

### ISSUE THREAD

**Issue by odiferousmint** [openscope/openscope#1483]
It would be great to have a scrollable history of events and/or to be able to change the fade-out delay.

Perhaps it could display the last N events when the input field (aircraft command) is focused, but it should be customizable as it might annoy someone. Bonus points for customizing the number of events displayed in this manner. In any case, choose whichever solution works best for you, if any. :)

**Comment by erikquinn** [comment]
A decent idea, but not something I'd really think is worth the time it would take (even if miniscule). I just don't see much of a need for it. If others disagree, we can reopen, but will close for now. Thanks though!
