### ISSUE TITLE
Be able to move/drag the details of the aircraft to avoid overlapping text

### ISSUE THREAD

**Issue by odiferousmint** [openscope/openscope#1484]
The issue is that sometimes (or depending on the circumstances often) when the aircraft is at the same position or nearby, their details overlap and become unreadable. Of course it could also happen with other labels as well.

A possible solution would be to be able to drag all of their details (along with the ALT and SPD) and adjust the grey line between the details and the blip. This is implemented in most if not all ATC software.

Related issue: https://github.com/openscope/openscope/issues/666

**Comment by erikquinn** [comment]
This is achievable by moving the data blocks (a scope command-- accessed by tab, then the number for the direction and click the aircraft). This is consistent with how they work in real life, hence where the solution came from. I _think_ it's in the tutorial. 🤔
