### ISSUE TITLE
Speech stops working

### ISSUE THREAD

**Issue by bgleb00** [openscope/openscope#1489]
Browser:
Google Chrome 78.0.3904.108 (Official Build) (64-bit)

Airport: KSTL

Approximate play time before issue: 2 hrs

#### Issue Description
Speech functions stopped working. It doesn't readback anything after playing for some time

#### Steps to reproduce

1. Enable speech function and keep playing
2. After some time (2hrs) speech function stops working, but the indicator is still on.
3. Turning it off and on again, solves the issue for some time

**Comment by erikquinn** [comment]
Closing as duplicate of #1582.
