### ISSUE TITLE
ZSPD: two "34R" runways

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#149]
The left runway should be renamed to "34L".

![image](https://cloud.githubusercontent.com/assets/4623358/22172953/f816654c-df68-11e6-92d2-8a6a3d825f9a.png)

Originally reported by @siqing-wang in zlsa/atc#783.

**Comment by indianbhaji** [comment]
On it!

**Comment by siqing-wang** [comment]
Hi, when will this be pushed to http://www.openscope.co?

**Comment by n8rzz** [comment]
@siqing-wang This fix has been merged into `release` and will be included in the next release scheduled for the end of this month.
