### ISSUE TITLE
planes are not landing when i tell them to...

### ISSUE THREAD

**Issue by jetmaster101** [openscope/openscope#1494]
Browser: chrome 

Airport: ottowa 

Approximate play time before issue: N/A

#### Issue Description
when i tell a plane to ILS land at a runway, it just flys by

#### Steps to reproduce
-

**Comment by VJC009** [comment]
@jetmaster101 make sure your aircraft intercepts the localiser at 30 degrees or less, also ensure they intercept below the glideslope, you can look up IAP charts to find these intercepts. Also when you clear an aircraft for the ILS, the drawn path (pink line) will show a straight line to the intercept point of the localiser, then it bends and follows the localiser till the runway. Also, after you clear the aircraft for the ILS, eg. AAL245 i 23, you can not issue it anymore heading or altitude commands, as those automatically cancel the clearance.
