### ISSUE TITLE
Scope display profiles

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#15]
Different profiles for scope colors, fonts, etc should be established in order to provide different themes that emulate the different radar systems used (STARS, ARTS, DSR/Host, ERAM, europe-things-i-don't-know-about).

Example items to be defined in a scope display profile (not all will be included in initial work):
 - [ ] brightness of aircraft targets, data blocks, control symbols
 - [ ] brightness of background color
 - [ ] brightness and radius of range rings
 - [ ] brightness of video map markings
 - [ ] center of range rings
 - [ ] default direction of data block leader lines
 - [ ] default length of data block leader lines
 - [ ] default length of PTLs

Related: zlsa/atc#371, zlsa/atc#395, n8rzz/atc#76.
Blocks: #115.
Originally reported in zlsa/atc#716.

**Comment by n8rzz** [comment]
:grimacing: we should move this to an epic and try to create smaller issues to accomplish this work.
