### ISSUE TITLE
`fix` command with multiple arguments skips to last fix

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#153]
Using the fix command with multiple fixes should cause a reroute where they proceed direct to the first one listed and then each of the subsequent ones, then resume their previous route. However, it is currently proceeding direct to the last fix given with the command, and skipping over the first ones.

> @JasonMKurtz:
>
>I can't figure out why "f dh457 dh458" results in the aircraft going to direct to the second one. Am I doing something wrong?

Originally reported in zlsa/atc#784.

**Comment by n8rzz** [comment]
should be retested after (n8rzz#181)[https://github.com/n8rzz/atc/issues/181] is merged

**Comment by siqing-wang** [comment]
It looks like it is not skipping to the last one. Instead, it uses reverse ordering.
Current behavior: "Fix A B C D" will go to D first, then C, then B, then A.

**Comment by n8rzz** [comment]
@erikquinn this issue goes away after openscope/openscope#193 is merged

**Comment by erikquinn** [comment]
Fix command deprecated. Reroutes work properly.
