### ISSUE TITLE
KDCA erroneous STARs = often initial collisions over LETZZ

### ISSUE THREAD

**Issue by dolek73** [openscope/openscope#1542]
The arrivals flow from NW are instructed to descend to FL80 over LETTZ and then descend to FL70, but this is the same also for collided flow from the SW. These two flows often collided over or passing LETZZ, prior switching to our control (only flights at or under FL70 are under our ATC control here) without possibility to solve it!
Thank you very much for the change in appropriate STARs for KDCA.
![KDCA-collision](https://user-images.githubusercontent.com/54574505/76417581-67295a00-639d-11ea-820e-c93a0f4ace47.gif)

**Comment by erikquinn** [comment]
This definitely needs to be in their airspace, or only one of the two streams used. I believe it is all MTV airspace to 190 in most places, with other sectors below them. Will have to check, but in short we should just give them more airspace since they would normally have more.
