### ISSUE TITLE
Remove FlyBe and Thomas Cook

### ISSUE THREAD

**Issue by VJC009** [openscope/openscope#1543]
Airports: EGCC, EGNM, EDDL (To the best of my knowledge)

I love this sim, it's really realistic and well made, however, I'd like to request an update to the game files as I'm not sure how to go about it myself. I'm sure you all know by now Thomas Cook (TCX) and FlyBe (BEE) have been shut down. These callsigns should be removed from the sim. Apologies if this has already been mentioned.

If I have not formatted my issue correctly or posted in the wrong place please me know I'm very new to GitHub! :)

**Comment by Fechulo** [comment]
Hi @VJC009 👋 Thanks for the report!
If you'd like to try to fix this yourself, it's not too difficult. All that needs to be done is for the airline files to be deleted and any references to them in any airport files to be removed. You can join us on [Slack](http://slack.openscope.io/) if you have any questions

I'd also be happy to do this myself you'd prefer someone else to do it 😄

**Comment by VJC009** [comment]
Hey @Fechulo, yes, I'm actually quite interested in helping in any capacity I can, and I already have Slack bc of vatsim, so that'd be great! See you there!
