### ISSUE TITLE
"route" command completely inoperable

### ISSUE THREAD

**Issue by VJC009** [openscope/openscope#1545]
Browser: Google Chrome

Airport: Seemingly all

#### Issue Description
So when I use the "route" command on any plane or airport it seems, one of four things happens:

1. The game just freezes, and the page needs to be reloaded.
2. If you select a fix on the plane's route, it simply reads back it's own route. E.g. A plane who's route 
    in its strip is A B C, the command "[callsign] route B" returns "[callsign], rerouting A B C" with no 
    change in its route.
3. If you select a fix, not on the plane's route, it reads back "[callsign], routes do not have 
    continuity!"
OR
4. If you select a fix, not on the plane's route, it reads back "[callsign], requested route of [fix] is 
    invalid

**Comment by erikquinn** [comment]
https://github.com/openscope/openscope/blob/develop/documentation/aircraft-commands.md#route

Please read the documentation on the route command, you are not using it as intended.

To go direct to a fix they already have on their route, use `pd` for "proceed direct".

**Comment by erikquinn** [comment]
The first point is worth looking in to however, as it should not be freezing for any reason. We'll check that out :)

**Comment by VJC009** [comment]
> https://github.com/openscope/openscope/blob/develop/documentation/aircraft-commands.md#route
> 
> Please read the documentation on the route command, you are not using it as intended.
> 
> To go direct to a fix they already have on their route, use `pd` for "proceed direct".

Sorry, my bad! Seems I got a bit muddled!

**Comment by erikquinn** [comment]
Oh wow, that's not good. It must be very old to still have that version of the route command.... 😬
