### ISSUE TITLE
Add EMERGENCY aircraft to the mix

### ISSUE THREAD

**Issue by Hawaiicoder** [openscope/openscope#1554]
Hello everyone! I LOVE openscope, however, it lacks one feature that I think would take it to the next level! I suggest adding emergencies where randomized aircraft declare emergencies and then you must vector them back to land- if you can't do it in time, they crash or have to ditch. At the same time, maybe we could start communicating with the ARFF units responding to an emergency. I really don't know where to start though, so if someone could help with this that would be great.

**Comment by Hawaiicoder** [comment]
That PR will not close the issue. It's just one thing (the responding ARFF) out of several. I'll keep chipping away as checks get completed.

**Comment by erikquinn** [comment]
At this time, this isn't a feature that aligns with the goals of the project. Closing.
