### ISSUE TITLE
Additional Aircraft?

### ISSUE THREAD

**Issue by Hawaiicoder** [openscope/openscope#1558]
Hello again. I just thought up an idea- what if military aircraft also flew at SOME airports? It would add an additional (yet realistic) challenge, to deal with aircraft that have to fly faster and still maintain separation. I'd be happy to do this, as it seems it wouldn't take much (and it would be a good project for a newbie like me). All I need is for someone to explain what units all the various specs are in the aircraft models. It wouldn't be a huge selection, just something to spice it up a bit more. 

I think I would divide aircraft by country- realistic air forces would be placed under airlines, and aircraft could still transfer through other nations, i.e. a USAF F-16 transits through the UK, or a French Air Force C130 lands in the US. (I have personally seen a French C130 in the US. It's realistic.)

Anyone with any advice or knowledge on the units as requested above please let me know. Once I know the units I'll get to work.

Tasks-

US Military

- A-10 Warthog

- AV-8 Harrier

- F-16 Fighting Falcon

-F/A-18 Hornet

-F-35 Lightning II

-B-52 Stratofortress

-B-1 Lancer

-C-17 Globemaster III

-C-130J

-UH/HH/SH-60 Blackhawk/Pave Hawk/Seahawk

-CH-47 Chinook

-CH-53

-KC-135

Canadian

-King Air C90

-Twin Otter

RAF

-Typhoon

-A400M

German Air Force (Luftwaffe)

-A310/A310MRTT

-Tornado

-C160

Possibly more.
Only unique aircraft are listed after US Military. I don't expect anyone to help me with this, as I think I can handle it myself, unless something doesn't work and I can't find the cause. I hope I can do this to make openscope a bit more diverse in terms of aircraft speeds (i.e. helicopters can hover if necessary, but fighters have to move fast.

**Comment by Fechulo** [comment]
Having military aircraft at airports is definitely 'allowed', it's just so rare at most airports that adding military traffic isn't really worth the effort. SAWH is an example of an airport with frequent military operations so it made sense to add military traffic there. If you want to go ahead with this, you'll find all the information on aircraft files in the [documentation](https://github.com/openscope/openscope/blob/develop/documentation/aircraft-format.md). If you have any questions you can reach out to us on [Slack](http://slack.openscope.io/)

**Comment by Hawaiicoder** [comment]
Thanks!

**Comment by Hawaiicoder** [comment]
Progress is slow but steady.

**Comment by OlaRune** [comment]
I know of at least two Swedish airports that are shared between military and civilian flight. I might try to add one of these later. However they are fairly low traffic, it’s like a few civilian flights a day "borrowing" the military airport because it is not economically viable to have a civilian airport for such low traffic.
