### ISSUE TITLE
-200 Points on Departures, I think

### ISSUE THREAD

**Issue by mairola** [openscope/openscope#1560]
Browser:Chrome

Airport:KRDU

Approximate play time before issue:30 minutes

#### Issue Description
Not seeing any errors, but all of a sudden I'm -200 points. and then -400 points. Appears to be on departures. Is there a restricted airspace I'm not seeing? 

#### Steps to reproduce
- Has happened the 3 or four times I've tried to play. Landing 23L/R Thought it was the Bexgo3.LVL sid, but I didn't have any departures there this last time. Will try again and see if I can nail it down a bit more.

Great Sim.. Thanks for building it

**Comment by mairola** [comment]
Of course, I played again and had no issues. Had a positive score of 120. Don't think I did anything different.

**Comment by mairola** [comment]
I've played it twice and can't reproduce it. Clearly I was doing something wrong. What mistake is -200?

**Comment by Fechulo** [comment]
Hey @mairola :wave: Sorry for only getting back to you now. The [scoring document](https://github.com/openscope/openscope/blob/develop/documentation/scoring.md) doesn't describe anything that would cause a 200 point reduction, but I wouldn't be surprised if the document was out-of-date or incomplete. It sounds to me like aircraft are entering restricted airspace, but I'm not too sure. KRDU has a restricted area southwest of the airport, about 20nm outside the airspace. You can enable restricted areas by going to the scope settings (the radar scope icon at the bottom right)

**Comment by mairola** [comment]
No worries!
There is restricted airspace way to the south after they have been handed off to center. Do I need to prevent them from flying through airspace that is outside my control?

**Comment by Fechulo** [comment]
Yeah, aircraft shouldn't be flying into that restricted airspace if they're following the SID. Giving a direct to CHS to aircraft flying the ROZBO3 departure might be the cause. Other than that, arrivals leaving the airspace will result in a 200 point reduction, but you should get an error when that happens.

**Comment by mairola** [comment]
Since I was new, I'm going to assume an arrival left my airspace with me dealing with them. Thanks!
