### ISSUE TITLE
Aircraft taxi from the runway to the runway

### ISSUE THREAD

**Issue by Fechulo** [openscope/openscope#1565]
You can instruct aircraft already on the runway to taxi to the runway. Although a cool 'feature', this is not desired behaviour
![euro](https://user-images.githubusercontent.com/13125311/80551951-17d6d180-89bd-11ea-9e75-2d209978cae3.gif)

**Comment by j-651** [comment]
Should this only prevent you from re-issuing duplicative commands to the same runway or any runway? Would this only apply to the first aircraft in queue?

In AicraftModel.js:1318 there's a comment in taxiToRunway():
```js
// remove aircraft from previous runway's queue
```
which seems to imply that it was intended to allow taxiing aircraft to a different runway after an initial command. Perhaps if you have a typo in your first one?

**Comment by erikquinn** [comment]
Only prevent you from re-taxiing to the runway they've already taxiied to. Should respond with some sort of red "we're already holding short of Runway X!" rather than saying "ok!" then disappearing for 3 seconds to reappear where they just were.
