### ISSUE TITLE
KJFK missing waypoint DARBO

### ISSUE THREAD

**Issue by JPmAn24** [openscope/openscope#1573]
Browser: Google Chrome

Airport: KJFK

Approximate play time before issue: immediate

#### Issue Description
_please include any console errors and/or screenshots_ 
![image](https://user-images.githubusercontent.com/28244253/80921532-91175100-8d3c-11ea-913b-9419f11bdd53.png)

#### Steps to reproduce
- Load KJFK

**Comment by j-651** [comment]
Shouldn't this have been closed by #1574? @erikquinn

**Comment by erikquinn** [comment]
Hm, yes. Sometimes github doesn't autoclose linked issues-- strange.

Closing.
