### ISSUE TITLE
KLAX Airport Guide has information for New York

### ISSUE THREAD

**Issue by j-651** [openscope/openscope#1590]
Browser: Chrome

Airport: KLAX Los Angeles

Approximate play time before issue: Not applicable

#### Issue Description
_please include any console errors and/or screenshots_ 
![image](https://user-images.githubusercontent.com/35548468/83543185-0c019200-a4ca-11ea-9542-a350ce597848.png)

#### Steps to reproduce
- The LAX airport guide contains a description of JFK instead.

**Comment by Fechulo** [comment]
Well that's embarrassing :man_facepalming:

**Comment by Fechulo** [comment]
@j-651 Fixed by #1594 if you'd like to take a look :smile:

**Comment by j-651** [comment]
Fantastic, thanks!
