### ISSUE TITLE
LROP score deduction

### ISSUE THREAD

**Issue by MemphisDon17** [openscope/openscope#1596]
Browser:

I'm new to Openscope, but paying LROP on multiple occasions, the score gets reduced by 200 points with no notice or warning.  It does it twice every time (-400 score) in the first 20 minutes or so and I can not determine why.  May be a bug or it may be something I'm doing and don't understand why but it would seem I would get some sort of notification in the comment line at the bottom as to why.

These 2 screenshots are literally a second apart.
![Opnescope 1](https://user-images.githubusercontent.com/66389837/83690284-139e6500-a5b6-11ea-9704-be7eb6b00400.jpg)
![Opnescope 2](https://user-images.githubusercontent.com/66389837/83690288-1436fb80-a5b6-11ea-80d8-465a1f3e8b7b.jpg)

**Comment by j-651** [comment]
@MemphisDon17 There is restricted airspace where THY3HI is in your screenshot. See below with the restricted airspace display enabled. In screenshot 1 below, the points are deducted as soon as ROT785 passes below FL60 within that circle.

The display of this can be toggled from within the radar icon at the bottom right (screenshot #2).

![image](https://user-images.githubusercontent.com/35548468/83703071-760a5c00-a5dc-11ea-8143-69cc6157e5d5.png)

**Restricted Airspace Toggle**
![image](https://user-images.githubusercontent.com/35548468/83703122-92a69400-a5dc-11ea-95f4-e86b5c3fbc1e.png)

**Comment by MemphisDon17** [comment]
Thanks.  I could not figure what it could be.  Just thought I’d get some sort of message telling me.

Also, when I looked at the “scoring” page, I don’t remember seeing anything worth 200 points.

Sent from my iPhone

On Jun 3, 2020, at 7:57 PM, Jay <notifications@github.com> wrote:

﻿

Reopened #1596<https://github.com/openscope/openscope/issues/1596>.

**Comment by j-651** [comment]
Looking at past issues, it looks like this was the case also in #1560. Further, #1020 suggests that scoring is eventually going to be removed altogether, so the docs may not be updated.

[Scoring docs](https://github.com/openscope/openscope/blob/develop/documentation/scoring.md)
