### ISSUE TITLE
Scaling Traffic Volume/user specified spawnPattern rates

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#16]
Present a slider-based UI that enables users to scale the rate at which traffic is being spawned; both by category (arrival/departure/overflight), as well as per each `spawnPattern` (in order to have control over WHERE the aircraft are going to or coming from) in order to achieve various goals in skill enhancement exercises. I'd love for them to be exposed in the UI with hierarchy, such that we can drag up and down "arrivals" / "departures", or I can _expand_ those and scale up/down each spawnPattern individually for further customization of traffic.

@sixeyeco had some nice mockups: ["options"](http://sixeyeco.github.io/atc/options-loader7b.html) and ["options as a popup"](http://sixeyeco.github.io/atc/index2.html)

Also see zlsa/atc#306, zlsa/atc#677.
Originally reported in zlsa/atc#374.

**Comment by n8rzz** [comment]
@suhaildawood here is another one fir your radar :wink:

**Comment by n8rzz** [comment]
https://codepen.io/n8rzz/pen/pPjELQ?editors=0010

**Comment by felixscheffer** [comment]
Can someone provide an icon for the traffic menu?

**Comment by Marcel510** [comment]
Maybe something like this:
http://chittagongit.com/icon/speed-icon-png-19.html

**Comment by felixscheffer** [comment]
@Marcel510  When I scale down the icon to 16px, it looks complete sh*t. 😭

**Comment by felixscheffer** [comment]
@n8rzz Nope, it's png.

**Comment by erikquinn** [comment]
I can svg that real easy tonight. Takes maybe 10 minutes

**Comment by erikquinn** [comment]
Uploaded in zip because github won't allow uploading svg. :man_shrugging: 

[traffic.zip](https://github.com/openscope/openscope/files/2569678/traffic.zip)
