### ISSUE TITLE
SSL protocol error when browsing https://www.openscope.co ...

### ISSUE THREAD

**Issue by panther2** [openscope/openscope#160]
... using Chrome browser (ChromeOS and Windows; latest stable channel).

Error message:

> This site can’t provide a secure connection
www.openscope.co sent an invalid response.
Try running Connectivity Diagnostics.
ERR_SSL_PROTOCOL_ERROR

http://www.openscope.co  works fine

**Comment by n8rzz** [comment]
@panther2 yep, we don't have an SSL at the moment that I'm aware of.  I'm going to leave this open for a little bit, just to check into it, but SSL is likely overkill for our purposes.

**Comment by panther2** [comment]
Maybe you should change the address on the 
https://github.com/openscope
page to the non-ssl-one just in case ...

**Comment by n8rzz** [comment]
Haha, yeah.  That would be a good idea. We'll get that taken care of.

**Comment by n8rzz** [comment]
@erikquinn looks like you'll have to do that one, I don't have access to change our link 😞
