### ISSUE TITLE
"no such aircraft" when addressing an aircraft on a flight strip

### ISSUE THREAD

**Issue by JasonMKurtz** [openscope/openscope#162]
My guess is that "return _isEqual(callsignToMatch.toUpperCase(), this.getCallsign());" (AircraftInstanceModel.js:472) is the culprit here.

**Comment by n8rzz** [comment]
that was exactly the culprit, nice work!

this will be included in [n8rzz#263](https://github.com/n8rzz/atc/pull/264)
