### ISSUE TITLE
FASTGA icao is disregarded

### ISSUE THREAD

**Issue by n8rzz** [openscope/openscope#164]
FASTGA icao is disregarded (ie. FASTGA872zz) - should be N872ZZ

I suspect we are having this same issue with `cessna`.

The `json_assembler` has been updated to only create `icao` keys for airlines that do not already have an icao, `FastGa` does and it is `N`.  This conflicts with some of the `AirlineModel` finding strategies and needs some investigation.

- [ ] update flightNumber generation to use `prefix` key, as defined in an `airline json` file
- [ ] update `generateFlightNumber` to use the `prefix`
- [ ] update `getCallsign` display correct  callsign

**Comment by erikquinn** [comment]
According to our records, this has been resolved as of v4.0.0. Closing.

**Comment by indianbhaji** [comment]
Kinda vetoing this closure:

![image](https://cloud.githubusercontent.com/assets/19408472/22400013/1b73e3a4-e5a2-11e6-9769-afac5929339c.png)

**Comment by indianbhaji** [comment]
(Opera, reload Berlin Tegel a few times until you get a FASTGA aircraft)

**Comment by n8rzz** [comment]
Very much open. There is more refactor needed to handle this and others, with the N registration

**Comment by n8rzz** [comment]
The description above is accurate for this new work.

**Comment by n8rzz** [comment]
partially addressed with openscope/openscope#195.  Will need to be retested for verification.

**Comment by erikquinn** [comment]
Resolved. I'm confident this time :wink:
