### ISSUE TITLE
Expedite command not working 100%

### ISSUE THREAD

**Issue by lucianoasmus** [openscope/openscope#1645]
Browser: Firefox

Airport: every airport so far

Approximate play time before issue: [What is meant by this?]

#### Issue Description
When I want a plane to expedite it's descend or climb, I would usually use the "x" command after the altitude, just like this: "BAW123, c 130 x". Unfortunately, it does not work for me anymore. I think it happened from one day to another, cannot remember of any updates. Typing "expedite" does still work tho.
![grafik](https://user-images.githubusercontent.com/62181068/90343239-d40ce400-e00e-11ea-899d-eb193daad05e.png)
![grafik](https://user-images.githubusercontent.com/62181068/90343251-01599200-e00f-11ea-841e-3cc9a92975b2.png)

#### Steps to reproduce
- For me it just happened. The command does not work with chrome either.

**Comment by j-651** [comment]
I think this might be a side effect of #1625 being merged. That PR added `x` as an alias for `cross`.

**Comment by lucianoasmus** [comment]
Okay, thank you. It would be nice tho to have a new shortcut alias for `expedite`. :)

**Comment by Hawaiicoder** [comment]
@lucianoasmus Maybe EX would be a good one.

**Comment by lucianoasmus** [comment]
I agree

**Comment by AF6754** [comment]
So that's why it didn't work.

**Comment by wmstapp** [comment]
hehe... here for the same.. I miss my X.  🤣
