### ISSUE TITLE
[refactor] improve command parser

### ISSUE THREAD

**Issue by JonasCir** [openscope/openscope#1684]
I took a look at the command parser and noticed that with some work, we could save a lot of LOC while improving readability :)
To make the review process easier, I'm going to submit the PRs individually.

The first step is to refactor the directory layout

**Comment by erikquinn** [comment]
For your planning purposes, these bullets will each need to be broken out into separate issues so each PR has a corresponding single issue number.

**Comment by 3tractorrides** [comment]
I’m interested to see what you can come up with here. Feel free to reach out if you have any questions on current implementation(s)

**Comment by JonasCir** [comment]
@erikquinn got it!
@3tractorrides Thank you very much for the offer :)
