### ISSUE TITLE
Aircraft command documentation updates + refine wording

### ISSUE THREAD

**Issue by cake-pie** [openscope/openscope#1699]
Browser: n/a

Airport: n/a

Approximate play time before issue: n/a

#### Issue Description
I've reviewed the aircraft commands documentation and in-app tutorial text for any required updates and other refinements. Documenting suggested changes here, input/discussion welcomed.

##### `aircraft-commands.md`
- update table of contents to remove "Move Data Block" which is a scope command
- `takeoff` - "climb to the altitude specified" implies that altitude is specified as an argument to this command, clarify by rewording as "... altitude they were *previously cleared to*"
- `taxi` - "hold short of *the* specified runway"
- `ils` - '*' is an alias, not a hotkey, i.e. it is accepted as valid input by the parser
- `fix` - add missing empty line to start new para for "deprecated" text. compare `abort`.
- `hold`
  - add documentation for distance-based holds, added in #1459
  - `l`,`r`,`left`,`right` are all acceptable for direction argument
  - holding over present position if no fix provided is intended behavior but doesn't actually work (#873 / #1318), document this
  - remove mention of commands that implicitly clear the hold #1333, in favor of explicit `exithold` command
- `exithold` - clarify behavior when no specific fix is given. see #1276, #1333
  - at some point I hope to revisit what the intended behavior ought to be and implement accordingly, but for now correctly document the actual behavior
- `altitude` - also mention that acft will not descend below MSA
- `heading`
  - 'shortkey' -> 'hotkey'
  - `l`,`r`,`left`,`right` are all acceptable for direction argument
  - document "turn by specified angle" with one- and two- digit angle specifying heading change
- `speed`
  - '+' and '-' are aliases, not hotkeys
  - add clarification that this is airspeed which will differ from ground speed 

##### tutorial text in `TutorialView.js`
ought to be json-ized, but that's a different issue.

- basic control instructions: radar vectors - make clearer distinction between how to specify target heading vs desired heading change
  - "Usually, you will specify a three-digit heading using..."
  - "instruct an aircraft to turn left *or* right by a given number of degrees if you specify a one- or two-digit number."

#### Steps to reproduce
n/a

**Comment by OlaRune** [comment]
I know that this issue is focused on the aircraft commands, but I'll throw this out there anyway.

In the scope command documentation all command syntax are specified to use the CID to point out the aircraft, but I think this is deprecated and replaced by just clicking the aircraft icon instead. I knlw it works this way with the scratchpad at least, which is the one I use myself.

Maybe this is more suited for its own issue, or it can be fixed with this issue. Your choice.

**Comment by cake-pie** [comment]
Per the scope command documentation
> note that `CID` was used in the examples, but aircraft may be referenced with any of ~~(a) the CID~~, (b) the full callsign, or ~~(c) the squawk code~~.

Have verified that manual input of callsign works. Clicking the aircraft on the scope is actually just [a shortcut](https://github.com/openscope/openscope/blob/e322287e69969fa14e11c8fcfdb0a903568de821/src/assets/scripts/client/InputController.js#L1051-L1055) to append the callsign to the command input and submit.

Have amended the documentation to clarify this, did formatting cleanup while I was at it.
