### ISSUE TITLE
css/less : centralize z-index declarations for ease of layer management

### ISSUE THREAD

**Issue by cake-pie** [openscope/openscope#1712]
#### Issue Description
While tinkering on a command autocomplete feature for #21 I needed to find out what `z-index` would be required to prevent canvas elements such as range rings from overlapping on top of my UI elements.

The lazy thing to do would be to set arbitrarily big `z-index` but it's better to do this in a coordinated way.

Indeed there are currently [12 different](https://github.com/openscope/openscope/search?q=z-index) `*.less` files declaring `z-index` with a wide range of values from 1, 2 to 100, 125, 200, 500 and even 1000, 1500.

This is hard to navigate and make sense of.  
For ease of layer management, instead have a section in `_vars.less` with something like:

```
// layer management
@static-canvas-z: 1;
@dynamic-canvas-z: 2;
@log-z: 5;
@airport-info-z: 5;
@strip-view-z: 10;
@controls-z: 20;
@dialogbox-z: 50; // shared
@pause-z: 99;
@loading-z: 100;
```

Much easier to understand what's going on.  
Respective elements get their z-index value via these variables.

**Comment by JonasCir** [comment]
@cake-pie I currently work on a refactoring of the command parser to simplify/clean it up. I really like the idea of auto completion. Do you already of an idea how to program it? B/c I don't want to break your plans with my refactoring :)

**Comment by cake-pie** [comment]
@JonasCir thanks for the note!

The autocomplete will not rely on any existing command parsing machinery, so most probably we won't run into much problems with your concurrent work in that area. I won't be touching or using anything in `src/assets/scripts/client/commands` at all.

I'll need to interface with `InputController.js` for input, and will modify its `input.command`, but all the stuff I need takes place *before* command is submitted. I suspect your changes are mainly relating to processing commands *after* they are submitted, such as in `processCommand()`, `processAircraftCommand()` and `processScopeCommand()`. If that is the case, then I expect any merge conflicts between our work should be minimal.

**Comment by JonasCir** [comment]
@cake-pie Great! My last PR made sure, that I don't need to touch anything in `InputController.js`. Everything I refactor is hidden behind this [call](https://github.com/openscope/openscope/blob/develop/src/assets/scripts/client/InputController.js#L790).
