### ISSUE TITLE
Difference between aircraftCommandMap and aircraftCommandDefinitions

### ISSUE THREAD

**Issue by JonasCir** [openscope/openscope#1718]
#### Issue Description
While writing tests for `aircraftCommandMap.js` and `aircraftCommandDefinitions.js`, I noticed that both files are not in sync.

1. `transmit` is a system command, but has no parser or validators associated.
2. `debug` has a parser and a validator, but not entry in the command map
3. ` has its own parser and validator (see [here](https://github.com/openscope/openscope/blob/develop/src/assets/scripts/client/commands/aircraftCommand/aircraftCommandDefinitions.js#L138)) but I think this should be an alias for something
4. `sayRoute` is a command, but has no parser or validator associated.
5. There are a couple of commands where I'm not sure that the command handlers are implemented: `airport`, `debug`, `auto`, `clear`, `transmit`, `tutorial`.

### How to resolve this
Bring the two files in sync. Remove or add entries.

**Comment by JonasCir** [comment]
Ok to get the discussion started:

1. Remove `transmit`
2. Remove `debug`
3. move ` to its associated command as alias (not certain which one it is)
4. add `zeroArgumentsValidator` and `noop` parser to `sayRoute`
5. PARSED_COMMAND_NAME is switched to run the code of `airport`,  `auto`, `clear`, `transmit`, `tutorial` etc. This is inconsistent and I think we should use `functionName` as we do normally, but I will address this later in time

What do you think @erikquinn ? :)

**Comment by erikquinn** [comment]
1. I think there may be something special with that one, but can't remember off the top of my head. @n8rzz?
2. Provided it's not used, that's fine
3. Just remove it... used to be the old way to move data blocks (before scope commands existed)
4. yeap!
5. Also defer to @n8rzz, I don't remember how that all worked in detail, and haven't really done any work on this area.

**Comment by n8rzz** [comment]
I'm interested to see what you come up with here.  `transmit` and `debug` are _likely_ holdovers from the original implementation and were things kept in place to reduce the amount of change when we rebuilt the command parser.

You have fresh eyes and are able to look at the current state of things and ask why.  Please keep doing that.  If it looks like it doesn't belong, it might not.

**Comment by erikquinn** [comment]
I agree. As a general sentiment, if you can make things make more sense, go for it. :)

**Comment by JonasCir** [comment]
Alright, thank you for the feedback, will do :)
