### ISSUE TITLE
JSONize airport load list

### ISSUE THREAD

**Issue by cake-pie** [openscope/openscope#1725]
#### Issue Description
`airportLoadList.js` is a javascript source file that only serves to contain data.

The justification appears to be:

https://github.com/openscope/openscope/blob/67f23ecfa27e73eb698ee7fe7c008ac03fdb8d3e/assets/airports/airportLoadList.js#L2-L9

Same can be accomplished by converting all of the airport load list data into JSON format, and ingesting it at app instantiation.  
Once built, the live copy of the file at `public/assets/airports/airportLoadList.json` can be modified without re-build / re-bundle  (skip minifying this file to preserve human readability)

Other benefits:
- all javascript source files compiled into `bundle.min.js` without any need for exceptions
- the json file could be validated against a json schema as part of workflow
- airport work issues and PRs no longer modify this one javascript file in order to add/remove airport from the list
  - such issues/PRs stop including the `refactor` label, which should really only apply to actual code changes

---

Because JSON does not support comments, before I proceed with this I need to know what should be done with all the entries in the list (44 of them!) that have been commented out. I can either:
- give them a `"disabled": true` property which is basically the same thing as `wip` that was removed for #1001
- delete them outright

**Comment by erikquinn** [comment]
`disabled: true` sounds logical to me!

**Comment by cake-pie** [comment]
Went with `disabled` so that omission of the optional property is equivalent to false by default, which is nicer semantically.
