### ISSUE TITLE
Add Helicopters to DCA

### ISSUE THREAD

**Issue by Hawaiicoder** [openscope/openscope#1729]
Helicopters are a massive part of DCA tower's job- Coast Guard helicopters are based at DCA, MEDEVAC and law enforcement helicopters are constantly buzzing around DC, and the most iconic of the DC helicopters, Marine One, regularly flies through DCA's airspace. This issue will primarily address helicopters in the DC area, but I fully intend to add them to other airports- New York, LAX, and many others are all candidates. It's not the primary feature of the sim, but in my opinion it's really important to make this sim as realistic as possible- adding helicopters will only add realism.

**Comment by erikquinn** [comment]
Correct, this is a tower thing. Soon tower controls will be automatic by default, as the focus of the sim is on approach.

Closing.

**Comment by Hawaiicoder** [comment]
@erikquinn Just curious, will departures also become automatic? And will the tower position be an option?

**Comment by erikquinn** [comment]
Right, that's the idea, for the departures to come out automatically. Most likely it will remain as an option to continue doing tower responsibilities, but that option will be set to "no" by default.
