### ISSUE TITLE
Code gardening: UiController.js

### ISSUE THREAD

**Issue by cake-pie** [openscope/openscope#1739]
#### Issue Description

Doing some cleanup in `UiController.js`.
Filing to get an issue number for commits, branch name and eventually PR.

- fixing incorrect JSDoc comments for properties (copy-and-pasted and not changed accordingly)
- add and document missing properties `trafficRateController`, `$toggleAirspace` to constructor + destructor
- use properties to access footer menu buttons in various `onToggleXyz` handlers instead of making unecessary jQuery objects
- add property `this.$log` for use in `ui_log`
- formatting/indentation consistency
- use data attribute to lookup row for current airport in airport switch dialog (instead of abusing class)
- alphabetize assignments to jQuery objects in: constructor, init, enable, disable, destroy
- group / alphabetize methods
- modify a few footer menu button click handlers so that analytics will have saner output. (originally reporting "false" for open/on and "true" for close/off)
- report both opening and closing of tutorial for analytics

~No change to code logic or function.~
Okay that turned out to be a lie, because of the last two items in the above list.

**Comment by cake-pie** [comment]
@n8rzz thought I should ask beforehand to avoid having to revert or change in code review:
How should I re-order this block of code? (from `UiController` `init()` method)

https://github.com/openscope/openscope/blob/67f23ecfa27e73eb698ee7fe7c008ac03fdb8d3e/src/assets/scripts/client/ui/UiController.js#L298-L320

I could:
a) enforce alphabetical order of whole block of code (move noncompliant L302, L320)
b) separate sections for elements related to dialogs and footer menu buttons, both alphabetical order
c) separate sections: dialogs alphabetically, footer buttons according to visual/DOM ordering

Will then apply the same consistent ordering throughout (constructor, `enable`, `disable`)

**Comment by n8rzz** [comment]
Yes please!

**Comment by cake-pie** [comment]
Please choose one of:

> a) enforce alphabetical order of whole block of code (move noncompliant L302, L320)
> b) split into separate sections for elements related to dialogs and footer menu buttons, both alphabetical order
> c) separate sections: dialogs alphabetically, footer buttons according to visual/DOM ordering

**Comment by n8rzz** [comment]
...and thats what I get for replying by email.  I am ashamed.

I'd go for `a`.  And, as you do, keep an eye out for abstractions.  There are multiple dialogs that we use, should there be a `DialogController` that worries about each with the `UiController` acting simply as traffic cop?  

I wrote a lot of this 5 or 6 years ago now, a lot of it makes me throw up a bit.  Some of it isn't bad.  All of it will benefit from fresh, critical eyes.

**Comment by cake-pie** [comment]
> There are multiple dialogs that we use, should there be a `DialogController` that worries about each with the `UiController` acting simply as traffic cop?

I think #1325 aims to do that?
