### ISSUE TITLE
Update build status badge on readme

### ISSUE THREAD

**Issue by cake-pie** [openscope/openscope#1758]
One of the badges we have at the top of `README.md` is for production build status (master branch).
`https://img.shields.io/travis/openscope/openscope/master.svg`
![](https://img.shields.io/travis/openscope/openscope/master.svg)

However, that badge gets the status from travis. Not sure if it's [travis-ci.org](https://travis-ci.org/github/openscope/openscope) or [travis-ci.com](https://travis-ci.com/github/openscope/openscope) but that's irrelevant anyway -- we're using neither of those now, having switched to github actions.

Github does supply a badge for workflow status:
`https://github.com/openscope/openscope/workflows/protected-branch-checks/badge.svg?branch=master`
![](https://github.com/openscope/openscope/workflows/protected-branch-checks/badge.svg?branch=master)

Ugh on the logo and the workflow name displayed in the raw.

The version wrapped by shields.io looks better:
`https://img.shields.io/github/workflow/status/openscope/openscope/protected-branch-checks/master`
![](https://img.shields.io/github/workflow/status/openscope/openscope/protected-branch-checks/master)

Oh, and apparently v6.23.0 is failing.

**Comment by erikquinn** [comment]
@cake-pie Yeah, it's a preexisting lint error that doesn't actually have any consequences. But it does look sad to see the little ❌. 😢

**Comment by cake-pie** [comment]
'kay!
