### ISSUE TITLE
SID transitions should not have to be the same name as the ending waypoint

### ISSUE THREAD

**Issue by JPNite3** [openscope/openscope#1760]
#### Issue Description
The "exitPoint" of SIDs are expected to have the same name as its ending waypoint, and when the two names do not agree, LegModel will throw an `Uncaught TypeError: Expect valid entry of *next procedure leg*, but received *name of transition*`

Example when the airport file has the exitPoint ` "BRUCE": [["BRUCE", "A150+"], "AGRIS"]` for a particular SID, and is fed the route `RJTT34L.ROVE2A.BRUCE`:
![image](https://user-images.githubusercontent.com/53888046/107154119-2d5f2b80-693f-11eb-9f95-88e8ef08944c.png)

The implementation must be changed so that instead of the name of the exitPoint, the last waypoint in the array for the particular exitPoint is used as the entry point for the next procedure leg (airway).

**Comment by erikquinn** [comment]
> SID transitions should not have to be the same name as the ending waypoint

Almost the entire planet categorically disagrees with this statement. The expectation for a route `RJTT ROVE2A BRUCE Y11...` to have BRUCE be _on_ Y11 is an expectation based on the fact that the overwhelming majority of countries require routes to be formatted as such. I've never seen a SID label their exit point in this way, and frankly, there is no reason for it-- they are complicating something simple without any advantage whatsoever. I can only assume this is unique to Japan, and I would hope it is rare even within Japan...

Even if we wanted to support it, given the way the logic is set up now, this would require a complete and total rewrite of all route parsing logic, something we don't have time for just to add one airport. I would recommend implementing `ROVE2A.BRUCE` as `ROVE2A.AGRIS`-- it may not be accurate, but is the only way this airport will be able to function. Alternatively, you could do `ROVE2A.BRUCE..AGRIS`, with the SID actually ending at BRUCE. But other than that, there is nothing we can do at this time.

Closing.
