### ISSUE TITLE
Stripview opens oddly when double-clicking aircraft label

### ISSUE THREAD

**Issue by Marcel510** [openscope/openscope#1795]
When double-clicking an aircraft the stripview on the right side of the screen opens oddly, see in this gif:

![unnamed23](https://user-images.githubusercontent.com/24833249/112026178-36ded480-8b36-11eb-9a69-0de5f6ded6fb.gif)

**Comment by erikquinn** [comment]
@Marcel510 Is this a regular computer, or like a tablet of some sort? And what browser?

**Comment by Marcel510** [comment]
@erikquinn 
regular computer
Browser: Google Chrome version 89.0.4389.90
OS: Windows 10
