### ISSUE TITLE
Realistic flight progress strips

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#18]
The flight strips are cool, but their utility (I think) is very limited. Since they are not of significant usefulness during the simulation, why not replace them with ones that are formatted the same as in the real world?

### FAA Terminal-Style Flight Progress Strips:
![image](https://cloud.githubusercontent.com/assets/5103735/21597905/2ad403e2-d120-11e6-9067-cf4b65bda71c.png)

This would resolve some other requests such as that in zlsa/atc#407 as far as exposing information that would be available to real-world controllers via the flight strip.

**Comment by n8rzz** [comment]
@suhaildawood here is another oldie that should be on your radar (pun intended)

**Comment by erikquinn** [comment]
Addressed by #406 (feature #285). Closing.
