### ISSUE TITLE
Support full approaches

### ISSUE THREAD

**Issue by cessnahat** [openscope/openscope#1801]
Especially in busy airspace, it would be nice to not have to always vector aircraft to final. Right now full ILS approaches can sort of be done with `rr` and `cr` commands, but the aircraft freaks out when you also include `ils ___`. It would be nice if you could include an IAF in an `ils` clearance and have the aircraft execute a full approach by itself.

**Comment by erikquinn** [comment]
This is literally issue #2. 😉 

Closing as duplicate.
