### ISSUE TITLE
Telling aircraft to go direct to next waypoint gives incorrect readback

### ISSUE THREAD

**Issue by OlaRune** [openscope/openscope#1811]
When telling an aircraft to go direct to the waypoint on their route that they are already on their way to, the readback is "can not proceed direct to X, it does not exist in our flightplan", when it should say something like "we are already going to X".

**Comment by cake-pie** [comment]
Am unable to reproduce this. When aircraft are instructed to go to their current waypoint, the readback is affirmative "proceed direct &lt;waypointName&gt;". Although this is a bit redundant, it is not problematic the same way that a spurious negative readback would be.

For example, I repeatedly issued `pd AUTUM` to this aircraft:
![multiple_Direct](https://user-images.githubusercontent.com/28502722/207578233-90c5b4f1-7933-4536-a111-8d92692cb310.png)

My best guess is that in the reported case, the aircraft indeed did not have the waypoint in its flightplan -- even though it might look like it, the aircraft could actually be headed for another different waypoint beyond the one in question, and just so happens to pass directly over it on the way there.

If not, more information needed to reproduce or diagnose. @OlaRune are you able to recall specifically how this happened?

**Comment by OlaRune** [comment]
I have no idea, too long ago. 🤪
