### ISSUE TITLE
Introduce "Cleared to land" command for landing planes

### ISSUE THREAD

**Issue by TroubiCZ** [openscope/openscope#1837]
Hello,

When checking #1828, I have got an idea. Right now, planes are landed using ILS command, but in real life, flights are handed to tower which gives the landing clearance. For example:

(radar frequency)
- Speedbird 1MW, cleared for ILS approach runway 24, report established
- Cleared for ILS 24, Speedbird 1MW
...
- Speedbird 1MW, fully established ILS 24
- Speedbird 1MW, contact Tower 134.56
- 134.56, Speedbird 1MW

(tower frequency)
- Ruzyne Tower, Speedbird 1MW, ILS 24
- Speedbird 1MW, Ruzyne tower, cleared to land runway 24, wind 280 10 knots
- Cleared to land runway 24, Speedbird 1MW

So, I propose to modify the "ils" command just to instruct a plane to intercept ILS.  When the plane is fully established, it should be displayed on the plane strip (and maybe the plane can report it?). After that, the ATC can issue a new "ctl <rwy>" (aka cleared to land) command, which actualy clears the plane to land. Without the clearence, the plane should go around eventualy.

I think this command would not be that hard to implement and it would add another level of realism to this great sim.

Kind Regards,
Trouba 1MW

**Comment by Fechulo** [comment]
Given that the sim is slowly moving away from Tower functions, this is unlikely to be implemented. The clearance, taxi and takeoff commands were all removed recently for that reason.

**Comment by TroubiCZ** [comment]
This is exactly my point. The flight should be cleared on ILS and than handed off to Tower.

**Comment by erikquinn** [comment]
@TroubiCZ Appreciate the suggestion! This one in particular we will not be implementing. But any other suggestions are welcome! :)

Closing.
