### ISSUE TITLE
Feature request: Openscope as PWA

### ISSUE THREAD

**Issue by SoftwUser** [openscope/openscope#1839]
Great simulation, thank you to the team!

Not sure where to post feature requests, so I hope it is correct here.

Any chance that Openscope will be installable as PWA?

**Comment by erikquinn** [comment]
Don't know what you mean by this. It is extremely unlikely to change significantly from its current state, but is open source, so obviously you can do what you want with it.

Happy to answer any questions, but closing this issue.

**Comment by SoftwUser** [comment]
@erikquinn 
Thank you for answering.

A PWA is a Progressive Web App, see https://en.wikipedia.org/wiki/Progressive_web_application

Chome for example offers to install some suitable websites as PWA - simply by showing the "Install" option inside the URL-field. 

I doubt that it needs a significant change, but I have no programming skills myself, so I might be wrong.

I am a user only - and would love to see Openscope as "app".

I have no programming skills, so can't do anything. 
But I doubt that offering Openscope as PWA would

**Comment by erikquinn** [comment]
I had actually read that, but the article didn't even really say anything. The short answer is that, whatever it is, we won't take the time to make openscope one of those. It will continue to exist in the state it's in, and we'll put all our focus into adding features instead.

**Comment by n8rzz** [comment]
I agree with Erik on that.  our app is text based, which requires a keyboard. doing that on a mobile device just makes for a poor experience, PWA or not. That and we just don't have the bandwidth to tackle something like that right now.
