### ISSUE TITLE
Speech Readback

### ISSUE THREAD

**Issue by indianbhaji** [openscope/openscope#186]
Just a few issues that may need addressing:

1. Wrong wind! The guy says 'wind' as in to wind someone up. Not the wind that blows things away.
2. It would be nice to say '100 degrees at 0 knots' instead of '100 at 0'
3. The guy speaks quite slowly?

**Comment by erikquinn** [comment]
1. Haha! Maybe we can tell her to say "wynd" instead and hope that gives the correct pronunciation.
 2. `wind one zero zero at five` is correct in FAA phraseology, which (when applicable) is the phraseology rule set we will be sticking to until we can have multiple sets of phraseology (ICAO phraseology mode vs FAA, etc). However, you definitely bring up a good point that if it's _literally_ `100 @ 0`, we should instead be saying `wind calm`.
 3. We can speed it up a bit! :+1:

**Comment by felixscheffer** [comment]
@indianbhaji @erikquinn  can you confirm that these issues still exist (the ticket is more than a year old)?

1. I am not a native speaker but "wind" sounds good me.
2.  ...
3. IMHO the speed is fine. Maybe someone increased it (currently 1.125).

**Comment by indianbhaji** [comment]
@felixscheffer I’ll check later but the lady was saying wind as in to twist something like a rope around an object

**Comment by indianbhaji** [comment]
@felixscheffer My apologies for not getting back to you on this. I was on my phone and completely forgot... anyways, the issue still remains. The lady is saying 'wind' as in the childhood riddle 'wind the bobbin up, wind the bobbin up, pull, pull, clap clap clap' instead of the movement of air

**Comment by Fechulo** [comment]
I wonder if simply adding the word "surface" before it could fix it, just giving it some context.

**Comment by erikquinn** [comment]
Resolved by #1213. Closing.
