### ISSUE TITLE
Altitude speech readback is incorrect

### ISSUE THREAD

**Issue by indianbhaji** [openscope/openscope#188]
Browser: Opera
Airport: any
Approximate play time before issue:
0 seconds

#### Issue Description
The audible altitude readbacks are incorrect.

#### Steps to reproduce

Example:
`SIA329 d 30`
> Singapore 329 descend and maintain one zero thousand.

**Comment by erikquinn** [comment]
Now it's actually just saying "maintain [altitude]", regardless of climb/descent required.
