### ISSUE TITLE
Add fix for runway 10C and 28C at KPIT 

### ISSUE THREAD

**Issue by madhursahay** [openscope/openscope#1894]
Browser: BRAVE

Airport:KPIT

#### Issue Description
_There are no specific fix points to align flights with 10c and 28c for ils approach, like other runways have this, but these two are missing it_
![image](https://user-images.githubusercontent.com/82830430/147630664-2239dbf7-f827-43ff-b44d-6ee734d8fac7.png)
 

#### Steps to reproduce
- Not too many but min. 3 would also work

**Comment by erikquinn** [comment]
This is because there is no ILS on Runway 10C-28C or Runway 14. 10C/28C is used mainly as a departure runway I would assume. It has RNAV approaches and such, but only ILSs are supported at the moment.

Closing.
