### ISSUE TITLE
Fly-over vs fly-by fixes

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#19]
Allow for differentiation between fixes that must be flown over before beginning turn or not, as there are some instances where it can make a difference.

![image](https://cloud.githubusercontent.com/assets/5103735/14350008/4e7d87be-fc8c-11e5-958d-2911b3d8307f.png)

Originally reported in zlsa/atc#427.

**Comment by headphase** [comment]
Just curious if there has been any work on this feature?  I could have sworn I recently saw a screenshot of an airport with a flyover waypoint icon but maybe my mind is playing tricks...

**Comment by n8rzz** [comment]
Not yet. We implemented hold fixes, but not flyovers yet.
