### ISSUE TITLE
Raise descent rate of all jets to at least 3000fpm

### ISSUE THREAD

**Issue by CanisLupus518** [openscope/openscope#1900]
the E135 has a noticeably terrible descent rate. Because of this, it is physically unable to "descend via" several STARs at many airports. I imagine this also effects some other aircraft.

I noticed that there are several closed issues and PRs related to this issue, but the only commit from them that I see for the e135 actually made it worse. I'm not sure if a better avg fpm needs to be calculated for certain jets, if something needs to be in place to allow for a reasonable override of fpm limits for "descend via" and "climb via" procedures, or if the climb\descent performance parameters need to be changed to something other than fpm.

**Comment by erikquinn** [comment]
Weird, I thought this was dealt with. But you're right, it's still showing goofily low values. As with almost all of them, these values are coming from the EuroControl Aircraft Performance Database (which is usuaully pretty good): 

https://contentzone.eurocontrol.int/aircraftperformance/details.aspx?ICAO=E135&ICAOFilter=e135

Regardless, EuroControl in this case (and others) is just wrong, and we should just change them to arbitrary "reasonable" values. I went ahead and looked for other aircraft that may be in a similar position-- here's all the jet aircraft sorted by descent rate, excluding those listed as 3000fpm or higher:

![image](https://user-images.githubusercontent.com/5103735/149826632-3eb7bd42-26df-43f5-b206-6e9f96c65d5c.png)

I think all of those offending aircraft could just be bumped up to 3000fpm for _descent_ only. This would include:
- [] AN72 (Antonov 72)
- [] DC10 (McDonnell Douglas DC-10)
- [] E135 (Embraer ERJ135)
- [] E35L (Embraer EMB-135BJ Legacy 600/650)
- [] E545 (Embraer Legacy 600)
- [] E550 (Embraer Legacy 500)
- [] IL62 (Ilyushin Il-62)
- [] IL76 (Ilyushin Il-76)
- [] MD82 (McDonnel Douglas MD-82)
- [] MD83 (McDonnel Douglas MD-83)
- [] SU9  (Sukhoi Superjet 100)
- [] A124 (Antonov 124 Ruslan)
- [] A306 (Airbus A300-600)
- [] A30B (Airbus A300B)
- [] A310 (Airbus A310-300)
- [] A343 (Airbus A340-300)
- [] A345 (Airbus A340-500)
- [] A346 (Airbus A340-600)
- [] A35K (Airbus A350-1000)
- [] A388 (Airbus A380-800)
- [] B762 (Boeing 767-200)
- [] BE40 (Hawker 400)
- [] C510 (Cessna Citation Mustang)
- [] HDJT (Honda HA-420 HondaJet)
- [] CRJX (CRJ 1000)
- [] E190 (Embraer 190/195)
- [] E290 (Embraer 190/195-E2)
- [] LJ40 (Bombardier Learjet 40)
- [] LJ45 (Bombardier Learjet 45)
- [] GL5T (Bombardier Global 5000)
- [] MD81 (McDonnel Douglas MD-81)
- [] MD88 (McDonnel Douglas MD-88)
- [] A321 (Airbus A321)
- [] C750 (Cessna Citation X)
- [] DC87 (McDonnell-Douglas DC-8-70)
- [] E145 (Embraer RJ145)
- [] E50P (Embraer Phenom 100)
- [] E55P (Embraer Phenom 300)
- [] GLF4 (Gulfstream IV)
- [] GLF5 (Gulfstream G550)
- [] H25B (Hawker 850)
- [] IL96 (Ilyushin Il-96-300)
- [] J328 (Dornier 328 JET)
- [] L101 (Lockheed L-1011 TriStar)
- [] LJ60 (Bombardier Learjet 60)
- [] LJ75 (Bombardier Learjet 75)
- [] E170 (Embraer 170/175)
- [] E75L (Embraer 175)
- [] E75S (Embraer 175)
- [] B788 (Boeing 787-8 Dreamliner)
- [] B789 (Boeing 787-9 Dreamliner)
- [] B78X (Boeing 787-10 Dreamliner)
- [] SU95 (Sukhoi Superjet 100-95)
- [] B743 (Boeing 747-300)

After checking, the way it works is what's listed in the aircraft's file is the _maximum capable_ descent rate. Descent planning plans to use 70% of that descent rate, and "expedited" descents will use the entire value. The descent will be expedited when told (ie `d 30 ex`), or automatically when established on approach. It does NOT automatically expedite when it is having trouble making a crossing restriction (which it absolutely should). This would go in as another condition for `AircraftModel.decreaseAircraftAltitude()` on line 2461.
