### ISSUE TITLE
Tutorial and default settings conflict for taxi

### ISSUE THREAD

**Issue by qubitter** [openscope/openscope#1912]
Browser: Any
Airport: Any
Approximate play time before issue: 00h00m00s

#### Issue Description
The default setting for tower control is "System Controlled". Because of this, when going through the tutorial, players will not be able to instruct aircraft to taxi, since they'll have taken off already.

To me, this suggests a fundamental problem with this part of the game's scope. Why are we telling aircraft to taxi? We're an app/dep controller. No reason for us to interact with an aircraft until it gets handed off from Tower at 4000 AGL. 

You could fix this issue by changing either the tutorial or the default tower behavior, but personally I think the tower functionality should be removed. Makes things a lot simpler, as well as much more accurate.

Now, according to @Fechulo in #1837 takeoff and taxi were removed? This is not the case in 6.26.0. But I agree and think they should be deprecated. 

#### Steps to reproduce
- Start a new game, any airport. 
- Start the tutorial. By the time you get to the part where you tell the aircraft to taxi, the plane will have taken off. 
- This is because the default behavior for tower operations is to be automatic.

**Comment by Fechulo** [comment]
Yeah, I didn't phrase that right. The commands were never removed, they are now automated, as you mention. The plan has always been to move away from all the TWR functions but that's a lot easier said than done. Automating clearances, taxi and takeoffs was the first step in that direction. The tutorial simply wasn't updated accordingly, and it probably should be.

**Comment by qubitter** [comment]
Just building on this - since we're not issuing clearances for takeoff/taxi, then we're not assuming ground/tower functions at all. The POV for this sim is meant to be that of an app/dep controller.

So why are we clearing people via SID and as filed? Those are both Tower/Gnd functions. See: https://www.faa.gov/air_traffic/publications/atpubs/aim_html/chap5_section_2.html

We should be able to tell departures to resume SIDs, if we have to vector them off for traffic. In fact, that's something I've run into many times before. But it doesn't seem like it's our job to clear them for SID. 

In fact, going by AIM 5-2-9.h.7, we should expect outbound flights departing via SID to inform us of their instrument departure routes.

Conclusions: Besides modifying the tutorial, I think we need to clarify the POV of the player in this scenario. At the moment, it seems like a mix of Tower and App/Dep control. We can very easily solidify it as App/Dep by changing CVS and CAF to function as they would in an approach/departure context: allowing us to _re_-clear aircraft as such after diverting for traffic etc.

**Comment by CutmanCometh** [comment]
It seems to me that we should allow the user to either control all tower clearances, or none.

The current state of the sim is that the player is responsible for an aircraft all the way through landing clearance, until it switches to ground. My understanding is that, in the real world, landing clearance is the responsibility of the tower controller, and approach's responsibility ends once the aircraft is handed off to tower.

Currently, we're not doing that in the sim: the player is responsible for maintaining spacing of landing aircraft and possibly departing aircraft, all the way down.

I see a UX problem: if I'm nicely spacing airplanes for landing, then the auto-tower clears a plane for takeoff right before my nicely-spaced plane lands, and then I get penalized for poor spacing, Ima punch a baby.
