### ISSUE TITLE
Add GND control

### ISSUE THREAD

**Issue by madhursahay** [openscope/openscope#1948]
enough we got pleasure of controling approach of an aerodrome
let's build now a fully new openscope system of ground control of an airport

I am not saying to remove approach, but let's add ground control too
all stuffs like clearance and taxi to rwy will be given by ground, will be damn cool

**Comment by madhursahay** [comment]
This is a really good suggestion, I think we should work on it :)

**Comment by Fechulo** [comment]
This has been suggested a number of times already, but an aerodrome simulator is beyond the scope of the project (pun very much intended). For the last while we've in fact been removing all aerodrome functionality and that's the direction that the project is headed in

**Comment by JonasCir** [comment]
@madhursahay Maybe start the project as separate one on your own? I thought about something similar as well :)

If you put it on GitHub, I'm certain there will be people who will contribute :airplane:
