### ISSUE TITLE
Airline ICAOs need to be lowercase

### ISSUE THREAD

**Issue by indianbhaji** [openscope/openscope#195]
The `icao` property inside files requires the airline ICAO to be lowercase.

ie.
`icao: "nca" `
instead of
`icao: "NCA"`

**Comment by n8rzz** [comment]
This is currently being handled programmatically with the `json_assembler.rb` script, which adds the `icao` key in the case where one doesn't already exist.  This is a bandaid.

- [ ] Add an `icao` key to each airline file, in lowercase
- [ ] remove if/else from `json_assembler.rb` and use the single method to combine the files
- [ ] add new test cases to `AirlineModel` for casing variations
