### ISSUE TITLE
Include a system to reduce game speed too..

### ISSUE THREAD

**Issue by madhursahay** [openscope/openscope#1951]
What I have seen is that aircrafts move much faster even at normal game speed, as an ATC, it doesn't feel to realistic.
If there would be a "button" to reduce speed too........it would contribute more to realism

**Comment by Fechulo** [comment]
The speed of the aircraft is accurate (as per EuroControl and FAA data), what you're probably seeing is the unrealistic refresh rate. Closing as a duplicate of #46
