### ISSUE TITLE
Route amendments will stop altitude changes

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#197]
Use of `rr`, `route`, and `fix` commands (basically anything that has the fms manipulate the route) is causing previous altitude instructions to be cancelled, and the aircraft holding its current altitude.

*Note: this only takes place when in the middle of a procedure. If just going direct from fix to fix, everything works okay. But if in the middle of a STAR and you assign something else, the alt/spd will be forgotten.*

> @dutchdavey in zlsa/atc#785:
>
>If you issue the 'a xxx' command to an aircraft it begins its descent. If you then issue a fix or rr, the aircraft stops its descent and holds its current altitude,
>
>Workaround: Alwasy issue the 'a xxx' command as last in the line, and reissue it in the same fashion, following any fix or reroute.

Related: #151.
Originally reported in zlsa/atc#785.

**Comment by erikquinn** [comment]
Found where this is happening, `AircraftFlightManagementSystem.js:786`, where a newly generated leg with no altitude or speed data takes the place of the old one with an altitude assignment. When we replace the leg, and the aircraft checks what altitude it should be descending to, it finds that no altitude is assigned, and does the expected default behavior of just maintaining their present speed and altitude.

Truthfully, this will actually be resolved by the work being done on separating hard altitude assignments (as opposed to "descend via the KORRY3 arrival" instructions) via the `MCP` and `FMS` in f/139 (#193). This should be revisited for cleanup following the completion of #193.

**Comment by n8rzz** [comment]
likely fixed as part of openscope/openscope#139

**Comment by erikquinn** [comment]
Rolled into #139.

**Comment by erikquinn** [comment]
Fixed in #193. Thanks MCP!!! :)
