### ISSUE TITLE
Add General Aviation Aircraft?

### ISSUE THREAD

**Issue by CutmanCometh** [openscope/openscope#1998]
Browser:
All

Airport:
All (perhaps inverse-weighted for airport size)

Approximate play time before issue:
N/A

#### Issue Description
We are simming airlines, currently. Would it add engagement/realism to sim GA aircraft?

#### Some discussion
Realistic simulation might require adding a few things
1. VFR approaches/departures (https://github.com/openscope/openscope/issues/1947)
2. VFR flight AI
  - Cross country VFR
  - Training maneuvers
  - Bone-headed pilot AI (👀 [N1NR](https://youtu.be/mUSUXnr4dSo))

This could currently be hacked by adding a "GA" airline, and only adding small aircraft, but that wouldn't add the full... flavor... of working with GA pilots.

Thoughts?

**Comment by JPmAn24** [comment]
As far as I know, we’ve got GA aircraft implemented as airlines for each country’s respective registration code. For example, airlines/n.json corresponds to US GA aircraft, and /xa.json corresponds to same for Mexico. These usually spawn in IFR flights like any other airline. A good example of seeing GA stuff is on KAUS. 

On the subject of adding in things such as pattern work, that should be able to be done alongside or after VFR approaches are implemented. The way I see it, those would be relatively easy to implement as spawnPatterns at each airport.

**Comment by MarylandFlyer** [comment]
We do have GA aircraft- I'm working on adding and enhancing the GA fleet so that it's a bit more diverse. Regarding VFR flights, that's something that I would absolutely love to see!

**Comment by erikquinn** [comment]
Scope too broad, and GA aircraft do exist, at least as IFR. There are other issues covering requests for VFR addition, so will close this one.
