### ISSUE TITLE
Comms log history

### ISSUE THREAD

**Issue by CutmanCometh** [openscope/openscope#2000]
Browser:
All

Airport:
All

Approximate play time before issue:
A few minutes

#### Issue Description
'Twould be nice to be able to see the history of outgoing and incoming communications, as well as scoring events, kind of like a chat history.

Currently, comms stay on screen for a few seconds, then disappear forever. Likewise with point events.

Example: I just got dinged for like -800 points or so, and I don't know why. I wish I could look at the logs and see what happened.

A simple modal dialog would work; activated by a footer menu item.

**Comment by n8rzz** [comment]
That should be doable. If I recall, there are only a few spots where we write to the log like that. Pretty sure most are centrally located as well. At any rate it would be pretty easy to create some a new structures to hold on to those logs or even persist them if we wanted to.

**Comment by rcobelli** [comment]
Currently working on implementing this. As of now, it's only displaying what changed your score; not every communication. Is this generally what you had in mind (screenshot shows mousing over the score to trigger the modal dialog)?

![Screenshot 2022-12-01 221817](https://user-images.githubusercontent.com/7349882/205209593-d4b82f3d-eb65-4409-93d1-1b827e76bf17.png)

**Comment by n8rzz** [comment]
Would it be possible to make that a bit wider so the text doesn't need to wrap (for most things anyway)? I'm also curious to see what a negative score might look like.

This is great start. I like what you have so far!

**Comment by rcobelli** [comment]
Per feedback from @n8rzz:
 
![Screenshot 2022-12-06 153420](https://user-images.githubusercontent.com/7349882/206017486-0ca71e48-98ce-4827-9d94-eb4c5caed12d.png)

**Comment by n8rzz** [comment]
Last little nitpick: any chance we could color negative numbers red?

Other than that, looks awesome, nice work! Is this in a PR already? If not, you should open one soon.
