### ISSUE TITLE
Command to have aircraft repeat last transmission

### ISSUE THREAD

**Issue by rcobelli** [openscope/openscope#2020]
Browser: All

Airport: All

Approximate play time before issue: Almost immediately

#### Enhancement Description
Due to how quickly the communication log fades out, you sometimes miss what an aircraft called you with. One solution to this is to create a new command asking the aircraft to repeat themselves.

I know that in the real world, the phraseology is usually "say again" but there is already a command for `sa` so I propose using `repeat` or `rpt`

#### Proposed Enhancement
`AAL123 repeat` or `AAL123 rpt`

**Comment by rcobelli** [comment]
After talking with other players of the game, another potential way of addressing this situation is to create a new setting that adjusts how long radio calls from aircraft remain visible. If the calls remain visible longer per the player’s preference, the `say again` command may not be necessary. 

Leaving this open for a few days before starting on a PR for comment from others

**Comment by 3tractorrides** [comment]
I’m a fan of that solution. The delay time is a value we set, so if we want to increase the delay that should be pretty simple to change.

**Comment by cake-pie** [comment]
I also think that user-configurable log fade out delay is the better solution here. Besides giving user more control according to their preferences, it requires only adding UI to adjust existing values, whereas adding support for aircraft to repeat their last transmission would require storing additional state in aircraft to cache that information.
