### ISSUE TITLE
Build: --prod flag not working as intended

### ISSUE THREAD

**Issue by cake-pie** [openscope/openscope#2052]
This bit of the build config does not appear to be working as intended:

https://github.com/openscope/openscope/blob/2860a23834ec11311cea47bac199031d0844955b/tools/tasks/scriptTasks.js#L28-L30

Regardless whether we `npm run build` or `npm run build:dev` it seems like the condition is not evaluating to true.

**Comment by n8rzz** [comment]
I'd love to move all these build steps to something more sane like webpack or vite. I wrote all this way back in the day before webpack was really a thing. This stuff is starting to show it's age, unfortunately.

**Comment by n8rzz** [comment]
Furthermore, I'd love to translate the app to Typescript too. But that is a many months long endeavor I just don't have time for at the moment.

**Comment by cake-pie** [comment]
Appears to be a misconfiguration of argument parsing, because rather than treating `--prod` as a flag, it seems to expect a value to be passed to the option, like `npx gulp build --prod true`, which would yield the expected behavior, resulting in smaller `bundle.min.js`. Investigating further.

**Comment by cake-pie** [comment]
The option is explicitly configured in the yargs setup in `cli.js`:

https://github.com/openscope/openscope/blob/2860a23834ec11311cea47bac199031d0844955b/tools/cli.js#L25-L29

It would need `boolean: true` to work as a boolean flag. Alternatively, we could just remove the whole explicit configuration of the option -- yargs default behavior without any config would suffice: argv.prod is `undefined` if flag absent (falsy to `gulpif`); `true` if flag present without a value being supplied, and would take on any value that is explicitly passed to the option (which `gulpif` would coerce to boolean)

As far as I can tell from the gulp configs and `package.json` it looks like nothing else in `cli.js` is actually used insofar as our local dev workflow and github actions are concerned. If I can get confirmation that it is not required for some other context (e.g. deployment?) then I think it would be best to completely eliminate all the unnecessary `cli.js` machinery in favor of a much simpler setup, as `--prod` is really the only flag we care about. (Incidentally, the help/usage stuff in `cli.js` doesn't work because `gulp-cli` would eats any `-h` or `--help` in the command line and output gulp's help instead.)
