### ISSUE TITLE
Double-clicking on an aircraft tag breaks the game

### ISSUE THREAD

**Issue by Fechulo** [openscope/openscope#207]
Browser: Chrome
Airport: Any
Approximate play time before issue:
However long it takes you to double-click on an aircraft tag

Issue Description
When an aircraft tag is double-clicked, the game glitches out in a really weird way...
See [this video](https://www.youtube.com/watch?v=HKZEpnp8lgQ)

Steps to reproduce
Double-click on any aircraft strip for an aircraft waiting to taxi

**Comment by n8rzz** [comment]
bisecting seems to land on commit `45a03fc4394eb6d7c669b306d4f85c932237a1fc`

**Comment by n8rzz** [comment]
turns out, this is because an aircraft that is not yet visible does not yet have a position.  Thus our calculations for finding canvas position fail because they result in `NaN`.  Simple defaulting will resolve this issue.
