### ISSUE TITLE
Multiple aircraft with same callsign

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#211]
In some rare cases, aircraft are being created with the same callsign. This should be prevented. Measures _are_ already in place for this exact thing, so it is curious that this can still occasionally be observed.

This occurrence was at `TNCM`, with two aircraft called `FWI667`. Were on different routes (`SKB..TIKAL..UMANA` and `PORQE..DANDE..AVAKI`).

Subsequently, the aircraft cannot be deleted using the `del` or `kill` commands; no commands will work, as the sim states `multiple aircraft match the callsign, say again`.

Observed on `master` at `v4.0.1`.

![image](https://cloud.githubusercontent.com/assets/5103735/22614948/79b9a6c8-ea58-11e6-89f3-fa544c946002.png)

**Comment by novinsh** [comment]
@erikquinn same happened on EBBR with one craft in apron the other on air. I am not sure about the revision but this happened at about the same time I am posting this comment.

![multiple_aircraft_callsign](https://cloud.githubusercontent.com/assets/2837237/22805679/efb616ec-ef33-11e6-8b0a-ff24c284ff0d.png)

**Comment by n8rzz** [comment]
I see the screenshots, but I honestly have no idea how this is even possible. 😮

**Comment by ron-eo** [comment]
I am using it right now and I have that error but there is only 1 plane on the screen with that call sign! Weirdness!

**Comment by ron-eo** [comment]
Oh, it just showed up outside the radar area! Still weird as you cannot control them.

**Comment by indianbhaji** [comment]
I believe that the fix for this is not public yet - it's in the develop branch for release soon.

**Comment by ron-eo** [comment]
And I just got another pair...one on the apron and one outside the radar again. Kind of annoying as you have to just let them go!

**Comment by n8rzz** [comment]
@indianbhaji is correct.  The bug was found and a fix has been merged into `release`.  This fix will be a part of the next release scheduled for the end of this month.

**Comment by ron-eo** [comment]
OK, thanks folks. So sad to see planes go! :( ;)
