### ISSUE TITLE
Flight strip bay scrollbar styling not applied in FF/IE/Edge

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#22]
In Firefox ,Internet Explorer and MS Edge, the flight strip bay has an ugly scrollbar instead of the one intended. Works in Chrome, which is the recommended browser for many reasons. Nonetheless, it should probably be addressed somehow.

Originally reported in zlsa/atc#471.

**Comment by n8rzz** [comment]
styling scrollbars is notoriously difficult to do cross-browser.  Not that it can't be done, but it will likely require some cleverness and/or additional plugins to achieve.

**Comment by erikquinn** [comment]
Yep, it does seem like it would be tricky. Firefox doesn't style them at all, and our use of webkit is only supported in chrome/safari. It may be worth giving up on the project tbh.

https://stackoverflow.com/questions/15420314/how-to-make-custom-scrollbars-show-in-all-browsers

**Comment by n8rzz** [comment]
we should definitely close this one.  my original comment still stands, there are better uses of our time I think.
