### ISSUE TITLE
Command bar cursor not at end of line in MS Edge

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#23]
The cursor should be at the end of the line, but in Microsoft Edge, it is at the far left instead.

Originally reported in zlsa/atc#489.

Also, per duplicate issue #1438, clicking aircraft will sometimes not put the command bar in focus, meaning the first keystroke is not shown in the command bar.

**Comment by erikquinn** [comment]
Some possibly helpful info? [https://github.com/angular-ui/ui-mask/issues/46#issuecomment-149901821](https://github.com/angular-ui/ui-mask/issues/46#issuecomment-149901821)

> Changing the type attribute on the input element from "text" to "tel" seems to fix the issue.
>
>`<input type="tel">`
>
>I've tested this out in MS Edge, and in Google Chrome v45.0 on both Galaxy S6 and Galaxy Note 3.
---
>Instead of changing the attribute have you tried removing the input event using the eventsToHandle property in the options?
>
>From the readme:
>
>>When customizing eventsToHandle or clearOnBlur, the value you supply will replace the default. To customize eventsToHandle, be sure to replace the entire array.

**Comment by n8rzz** [comment]
this would be a red herring (dead end).  The quotes posted are in reference to `angular-ui`, which is an angular package (we are not using angular) and its specific use as a directive.

Additionally, changing the input type to `tel` would only allow for numbers to be entered within the command bar.  Which is not what we want.

At the end of the day, this is likely a browser bug that is going to be very tricky to fix.

**Comment by n8rzz** [comment]
additionally, Edge is not widely used by our users:

<img width="433" alt="screen shot 2017-08-11 at 7 50 59 am" src="https://user-images.githubusercontent.com/3325985/29213687-e9d90b56-7e69-11e7-8c38-6f98693374ed.png">

_time frame: 7/11/2017 - 8/11/2017_

**Comment by oobayly** [comment]
I also get this issue on Chrome on Mint. I've pinned it down to it happening when I click one of the buttons on the bottom bar. Focus is taken away from the textbox, so when I click on an aircraft, focus isn't correctly transferred back to the textbox.

Its a simple change to check whether the textbox has focus, and if not explicitly set it.
