### ISSUE TITLE
TJSJ and KFDW Aircraft entrance into map bug

### ISSUE THREAD

**Issue by Exfil** [openscope/openscope#239]
I don't know if its just me or everyone else but when I'm playing in TJSJ and KFDW, aircraft that pass the radar boundary to enter into my jurisdiction remain gray colored and uncontrollable for a substantial amount of time. This happens ever since the sim was moved to openscope.

Someone please look into this, thanks.

**Comment by n8rzz** [comment]
Likely due to a large gap in spawn altitude and airspace ceiling. In English, the aircraft doesn't have enough time to decend below the airspace ceiling.

Thanks for the report!

**Comment by erikquinn** [comment]
So this is specific to pre spawned aircraft. They are spawning at the same altitude when spawned near the boundary as they do when they are spawned far out. The descent takes a while, hence the problem.

This will be addressed as part of #32.
