### ISSUE TITLE
Airport Revival: John F. Kennedy International Airport

### ISSUE THREAD

**Issue by indianbhaji** [openscope/openscope#242]
John F. Kennedy International Airport (IATA: JFK, ICAO: KJFK, FAA LID: JFK) is a major international airport located near South Ozone Park in the borough of Queens in New York City, United States, 12 miles (20 km) southeast of Lower Manhattan. It is the busiest international air passenger gateway into the United States,  the fifth busiest airport in the United States and the busiest airport in the New York City airport system, handling 58,956,288 passengers in 2016. Over ninety airlines operate out of the airport, with non-stop or direct flights to destinations in all six inhabited continents. The airport features six passenger terminals and four runways. It serves as a hub for American Airlines and Delta Air Lines and is the primary operating base for JetBlue Airways. In the past, JFK served as a hub for Eastern, National, Pan Am, and TWA.

Opened as New York International Airport in 1948, it was commonly known as Idlewild Airport before being renamed in 1963 in memory of John F. Kennedy, the 35th President of the United States, following his assassination.

This airport was omitted when spawnPatterns were introduced.

**Comment by headphase** [comment]
What needs to be done for JFK to be reenabled?  I'd like to help if possible :)

**Comment by n8rzz** [comment]
spawnPatterns need to be added.

for local env setup see: https://github.com/openscope/openscope/tree/develop/tools
for spawnPattern documentation see: https://github.com/openscope/openscope/blob/develop/src/assets/scripts/client/trafficGenerator/spawnPatternReadme.md

**Comment by headphase** [comment]
Thank you for both of those links!  I don't understand the following part of the local setup instructions:

> After you have node installed, navigate to the project folder and run npm install && npm run build. This will install the project dependencies and run the build tasks for the css and javascript.

Where are these two files?  I don't see them in the Openscope folders.

**Comment by indianbhaji** [comment]
@headphase `npm install && npm run build` isn't an executable file. It is a command that can be run if you install [node.js](https://nodejs.org/en/).

Make sure you install version 7.8.0 from there - if you need help with this, join our [Slack](openscopeatc.slack.com) and we'll be able to assist you further.

**Comment by Fechulo** [comment]
@headphase yeah, that's not very clear... they're not files, they're commands that you have to run in the command line. Open up the command line, navigate to the project folder. (e.g. If the folder is in the desktop you need to type 'cd Desktop/openscope-develop') then run 'npm install' and once that's done 'npm run build'. To test it you can create a local server by running 'npm run start'

**Comment by erikquinn** [comment]
It all _sounds_ complicated, and is a one-time pain-in-the-butt, but it's truly not that bad, and we're happy to help through any hiccups or confusion with the setup process by chatting on slack (join at [slack.openscope.co](http://slack.openscope.co))

**Comment by headphase** [comment]
Excellent thanks for the help; I posted in the slack help channel

**Comment by indianbhaji** [comment]
@headphase took this on, changing the assignee
