### ISSUE TITLE
openscope.co without www is "under heavy load" (nginx)

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#258]
Visit [openscope.co](http://openscope.co) and you'll get one of two pages:

![image](https://cloud.githubusercontent.com/assets/5103735/23108833/00113e90-f6e1-11e6-8fe3-c8c2ef32aa25.png)
![image](https://cloud.githubusercontent.com/assets/5103735/23108841/132b6d7a-f6e1-11e6-8ef2-566092c0c5f6.png)

Visit [www.openscope.co](http://www.openscope.co) and everything works as it should.

**Comment by n8rzz** [comment]
Initial investigation has found:
- root domain `openscope.co` is working correctly
- requests made to `www.openscope.co` never make it to our servers and eventually display one of the two errors above.
- domains all appear to be mapped correctly and have been working fine up until 1930 central time.
- our domain host is experiencing DNS issues: https://twitter.com/HoverStatus/status/833481558484930560

This seems to be a result of our domain host's DNS issues.  Will update when we know more.

**Comment by n8rzz** [comment]
Response times for `openscope.co` seem to be getting better, though still intermittently failing.

**Comment by n8rzz** [comment]
Domain forwarding is back online and `openscope.co` resolves correctly.
