### ISSUE TITLE
Firefox fails to load app on first visit

### ISSUE THREAD

**Issue by n8rzz** [openscope/openscope#263]
continuation of conversation from #248

**Comment by n8rzz** [comment]
> I tried IE first and it was working but seemed to freeze after about 10 planes. I tried Chrome next and it seems to be ok except that is also froze when I went to another browser window. I restarted it and it seems to be working fine. I also noticed that the openscope window doesn't refresh when you take the focus off and go to another web browser window. Thanx!

The 'freeze' is actually a feature (if I'm understanding you correctly).  When the main window looses focus, the app pauses.  there is nothing worse than working the sim for a little while, get distracted and move away only to come back and everything has gone to 💩 .  If you click back in the main window everything should start back up again.  You'll notice the clock in the top left stop and start when focus is lost/gained.

**Comment by ron-eo** [comment]
OK, it's by design so that's fine with me! :) It happened on all the browsers I tried so it is working! :)

**Comment by n8rzz** [comment]
@ron-eo The firefox bug above seems legitimate, so thanks for finding that one!
