### ISSUE TITLE
Using runways not valid for assigned procedure causes crash

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#27]
When either of the following are true:
 - taxiing a departure to a runway, and then assigning them a SID that is not valid
 - an aircraft is expecting to land on runway A, and is assigned a STAR only valid for runway B

...the game will crash.

Originally reported in zlsa/atc#573, zlsa/atc#519, zlsa/atc#580.

**Comment by felixscheffer** [comment]
I tried both cases and I don't see any crashes. Can you confirm that the issue still exists, please?

**Comment by n8rzz** [comment]
@erikquinn this looks like a closable issue unless this is still a thing?

**Comment by erikquinn** [comment]
Resolved, closing.
