### ISSUE TITLE
New Airport: KCVG

### ISSUE THREAD

**Issue by RNGFavorsNoobs** [openscope/openscope#272]
Description in [this pull request](https://github.com/openscope/openscope/pull/275).

**Comment by n8rzz** [comment]
@RNGFavorsNoobs if you want to open a PR, we can spin up a release app that will run your code.  It'll update after every push.  At least then you'll be able to check your work.

**Comment by RNGFavorsNoobs** [comment]
@n8rzz , I'm nor exactly sure what a PR or a "release app" is, but if it means I can test it for myself, that would be awesome!

**Comment by n8rzz** [comment]
yeah, open a pull request.  Just thinking about it, I'm not sure if we can spin up a review app from a fork.  But I'm curious, so lets give it a shot!

**Comment by RNGFavorsNoobs** [comment]
@n8rzz I've already opened a pull request [here](https://github.com/openscope/openscope/pull/273).

**Comment by n8rzz** [comment]
If you head on over to the pull request, you will see a button towards the bottom `view deployment`.  click that and it will open the app, with the code from your branch.  😉

**Comment by n8rzz** [comment]
... unless there is a failure.  like there is now ☹️

**Comment by RNGFavorsNoobs** [comment]
Was just about to say something, haha.

**Comment by n8rzz** [comment]
looks like a JSON error somewhere.  try throwing the json you've created in here: http://jsonlint.com/ and then fix any lint errors, then re-commit.  The app should rebuild on any new commits.

**Comment by Fechulo** [comment]
Maybe the missing comma on line 3?

**Comment by RNGFavorsNoobs** [comment]
There were two errors. Fixed and recommitting. Hold on.

**Comment by n8rzz** [comment]
@RNGFavorsNoobs you can also join our slack channel http://slack.openscope.co/ (and you can be the first to test this little guy)

**Comment by RNGFavorsNoobs** [comment]
Recommitted and joining the slack.

**Comment by n8rzz** [comment]
@RNGFavorsNoobs we will close this once your PR is merged

**Comment by RNGFavorsNoobs** [comment]
@n8rzz Whoops. : P
