### ISSUE TITLE
Update all airports to include video maps, if possible

### ISSUE THREAD

**Issue by RNGFavorsNoobs** [openscope/openscope#283]

**Comment by indianbhaji** [comment]
Best of luck with this!

You'll be able to update most of the US ones, but I'd doubt that you'd find
many out of the US.

**Comment by RNGFavorsNoobs** [comment]
We'll see. ;)

**Comment by panther2** [comment]
Please help me: What is a "video map"? Charts?

**Comment by n8rzz** [comment]
@panther2 see `KLAS`, `KMSP` or `KORD`

**Comment by panther2** [comment]
I see, thanks!
