### ISSUE TITLE
Extract AircraftInstanceModel view logic to new class

### ISSUE THREAD

**Issue by n8rzz** [openscope/openscope#285]
There is a ton of view logic in this class that needs to be moved to a more appropriate place.  This will likely require a fair amount of untangling in order to remove it successfully.

This new class will need to be plugged into the update cycle in order to stay up to date.

Specifications:
- The `AircraftInstanceModel` should hold the data.
- The `AircraftView` should take the data and display it.
- Remove number transformations in AircraftStripView.updateAircraftTelemetryText() such as `Math.ceil()`
- Must fulfill specifications of #168

**Comment by n8rzz** [comment]
depends on openscope/openscope#457

**Comment by erikquinn** [comment]
Resolved by #406. Closing.
