### ISSUE TITLE
New Airport: MDSD

### ISSUE THREAD

**Issue by pedriglieri** [openscope/openscope#288]
Hi my name is Giancarlo I´m a big fan of the simulator.

I spent my free time practicing the simulator, i would love to play the airport of my hometown Santo Domingo Dominican Republic called Aeropuerto Internacional Las Americas.

the ICAO code is MDSD. the Aeronautical information publication is on this page

http://aip.idac.gov.do/

how i can help to make this possible?

Thanks for your time.

**Comment by indianbhaji** [comment]
Hi @pedriglieri,

Currently we are revising our documentation to fit the recent updates to the game, however if you wish to contribute, I'd advise just looking through some of the airports we have in `/assets/airports/` for the time being.

We'd be able to assist you easier and quickly if you join our Slack, @erikquinn should be able to deal with this. The process of creating airports involves installing node.js, but if you need help with that we can do so easily through our Slack channel.

**Comment by Fechulo** [comment]
@pedriglieri I probably should've said this before, but I've started working on MDSD. So far I've added the RNAV SID's (I'm planning on adding the rest later) and all the STAR's for RWY17. I also added the multiple restricted airspaces and I'm planning on adding terrain at the end.

Si tienes preguntas o sugerencias no dudes en mandarme un mensaje por [slack](openscopeatc.slack.com)

**Comment by erikquinn** [comment]
Actually, anyone can now join the slack team simply by visiting [slack.openscope.co](http://slack.openscope.co) for an invite. :smiley:

**Comment by pedriglieri** [comment]
wow muchas gracias por tu ayuda. si necesitas alguna información que te pueda suministrar estoy totalmente disponible no dudes en preguntar


Enviado desde Outlook<http://aka.ms/weboutlook>

________________________________
De: Fechulo <notifications@github.com>
Enviado: domingo, 19 de marzo de 2017 10:06:54 p. m.
Para: openscope/openscope
Cc: pedriglieri; Mention
Asunto: Re: [openscope/openscope] New Airport: MDSD (#288)


@pedriglieri<https://github.com/pedriglieri> I probably should've said this before, but I've started working on MDSD. So far I've added the RNAV SID's (I'm planning on adding the rest later) and all the STAR's for RWY17. I also added the multiple restricted airspaces and I'm planning on adding terrain at the end.

Si tienes preguntas o sugerencias no dudes en mandarme un mensaje por slack<openscopeatc.slack.com>

**Comment by pedriglieri** [comment]
Donde se puede ver la simulación del MDSD?


Enviado desde Outlook<http://aka.ms/weboutlook>

________________________________
De: Fechulo <notifications@github.com>
Enviado: domingo, 19 de marzo de 2017 10:06:54 p. m.
Para: openscope/openscope
Cc: pedriglieri; Mention
Asunto: Re: [openscope/openscope] New Airport: MDSD (#288)


@pedriglieri<https://github.com/pedriglieri> I probably should've said this before, but I've started working on MDSD. So far I've added the RNAV SID's (I'm planning on adding the rest later) and all the STAR's for RWY17. I also added the multiple restricted airspaces and I'm planning on adding terrain at the end.

Si tienes preguntas o sugerencias no dudes en mandarme un mensaje por slack<openscopeatc.slack.com>

**Comment by erikquinn** [comment]
@pedriglieri Se puede probarlo aquí: [openscope-dev-pr-289.herokuapp.com](http://openscope-dev-pr-289.herokuapp.com)

Pero parece que @Fechulo está todavía trabajando en ello, entonces probablamente hay unas cositas que no ya son completas. Cuando él termina, lo revisaramos unas veces hasta está listo para ponerlo en [la juega principal](http://www.openscope.co) :smile:

**Comment by pedriglieri** [comment]
Comprendo. Si necesitas alguna información especifica no dudes en preguntármelo y gracias de verdad.


Enviado desde Outlook<http://aka.ms/weboutlook>

________________________________
De: Erik Quinn <notifications@github.com>
Enviado: miércoles, 22 de marzo de 2017 9:32:34 p. m.
Para: openscope/openscope
Cc: pedriglieri; Mention
Asunto: Re: [openscope/openscope] New Airport: MDSD (#288)


@pedriglieri<https://github.com/pedriglieri> Se puede probarlo aquí: openscope-dev-pr-289.herokuapp.com<http://openscope-dev-pr-289.herokuapp.com>

Pero parece que @Fechulo<https://github.com/Fechulo> está todavía trabajando en ello, entonces probablamente hay unas cositas que no ya son completas. Cuando él termina, lo revisaramos unas veces hasta está listo para ponerlo en la juega principal<http://www.openscope.co> 😄

**Comment by Fechulo** [comment]
@erikquinn I had no idea you spoke Spanish!
@pedriglieri es un placer! De momento no necesito nada pero este domingo me voy de viaje asi que es posible que no pueda hacer mucho progreso por unas semanas.

**Comment by pedriglieri** [comment]
No te preocupes no te sientas presionada. y que tengas un excelente viaje


Enviado desde Outlook<http://aka.ms/weboutlook>

________________________________
De: Fechulo <notifications@github.com>
Enviado: miércoles, 22 de marzo de 2017 9:39:20 p. m.
Para: openscope/openscope
Cc: pedriglieri; Mention
Asunto: Re: [openscope/openscope] New Airport: MDSD (#288)


@erikquinn<https://github.com/erikquinn> I had no idea you spoke Spanish!
@pedriglieri<https://github.com/pedriglieri> es un placer! De momento no necesito nada pero este domingo me voy de viaje asi que es posible que no pueda hacer mucho progreso por unas semanas.

**Comment by Fechulo** [comment]
@pedriglieri The airport is pretty much done! You can test it [here](openscope-dev-pr-289.herokuapp.com) and let me know if you'd like anything to be changed or improved.

**Comment by pedriglieri** [comment]
Wow de verdad que te esmeraste mucho. Gracias ahora mismo lo revisare detalladamente y te enviare respuestas al respecto.


Enviado desde Outlook<http://aka.ms/weboutlook>

________________________________
De: Fechulo <notifications@github.com>
Enviado: sábado, 25 de marzo de 2017 11:56:51 p. m.
Para: openscope/openscope
Cc: pedriglieri; Mention
Asunto: Re: [openscope/openscope] New Airport: MDSD (#288)


@pedriglieri<https://github.com/pedriglieri> The airport is pretty much done! You can test it here<openscope-dev-pr-289.herokuapp.com> and let me know if you'd like anything to be changed or improved.

**Comment by pedriglieri** [comment]
Las aeronaves que salen atravesando el TMA de Punta Cana (MDPP) entra en jurisdicción de aproximación Punta Cana y las aeronaves que llegan aún estando en el TMA de Punta Cana entra en jurisdicción de aproximación Las américas (MDSD).


Ya que existe un acuerdo entre tales dependencias.


Enviado desde Outlook<http://aka.ms/weboutlook>

________________________________
De: Fechulo <notifications@github.com>
Enviado: sábado, 25 de marzo de 2017 11:56:51 p. m.
Para: openscope/openscope
Cc: pedriglieri; Mention
Asunto: Re: [openscope/openscope] New Airport: MDSD (#288)


@pedriglieri<https://github.com/pedriglieri> The airport is pretty much done! You can test it here<openscope-dev-pr-289.herokuapp.com> and let me know if you'd like anything to be changed or improved.

**Comment by Fechulo** [comment]
@pedriglieri lamentablemente acuerdos entre dependencias no se pueden simular en el juego. Por lo tanto hay 2 formas de mostrar el TMA: excluir el TMA de Punta Cana o Ignorarlo y completar el circulo del TMA de Santo Domingo. Cual opción te parece mas realista?

**Comment by pedriglieri** [comment]
Perdón. En realidad las salidas están bien el único detalle seria solo para las aeronaves que arriban, que automáticamente entran en el TMA de las Américas sin importar que esté en parte del TMA de Punta Cana, se le puede dar control.

Desde que llegue a la casa revisaré  mas cosas, pero de verdad gracias por dedicarle tiempo 😉👍

Enviado desde mi Windows Phone
________________________________
De: Fechulo<mailto:notifications@github.com>
Enviado el: ‎27/‎3/‎17 11:41
Para: openscope/openscope<mailto:openscope@noreply.github.com>
CC: pedriglieri<mailto:giancarlopedriglieri@outlook.com>; Mention<mailto:mention@noreply.github.com>
Asunto: Re: [openscope/openscope] New Airport: MDSD (#288)


@pedriglieri<https://github.com/pedriglieri> lamentablemente acuerdos entre dependencias no se pueden simular en el juego. Por lo tanto hay 2 formas de mostrar el TMA: excluir el TMA de Punta Cana o Ignorarlo y completar el circulo del TMA de Santo Domingo. Cual opción te parece mas realista?

**Comment by Fechulo** [comment]
Un placer 😄  Como he dicho, eso no se puede simular en el juego. Cual opción crees que sería más realista? o quizás mejor en términos de jugabilidad?

**Comment by pedriglieri** [comment]
Seria mejor eliminar el TMA de  Punta Cana y el nivel de dificultad si es posible intermedio

Enviado desde mi Windows Phone
________________________________
De: Fechulo<mailto:notifications@github.com>
Enviado el: ‎27/‎3/‎17 12:27
Para: openscope/openscope<mailto:openscope@noreply.github.com>
CC: pedriglieri<mailto:giancarlopedriglieri@outlook.com>; Mention<mailto:mention@noreply.github.com>
Asunto: Re: [openscope/openscope] New Airport: MDSD (#288)


Un placer 😄 Como he dicho, eso no se puede simular en el juego. Cual opción crees que sería más realista? o quizás mejor en términos de jugabilidad?

**Comment by Fechulo** [comment]
Ya hice ambos cambios, pero debido al nuevo TMA, tendré que rehacer el terreno. Ahora mismo estoy de viaje y no tengo los programas necesarios para generar el terreno, pero cuando regrese lo haré.

**Comment by pedriglieri** [comment]
Muchas Gracias. Tómalo con calma disfruta tus vacaciones y relájate.

Enviado desde mi Windows Phone
________________________________
De: Fechulo<mailto:notifications@github.com>
Enviado el: ‎28/‎3/‎17 14:22
Para: openscope/openscope<mailto:openscope@noreply.github.com>
CC: pedriglieri<mailto:giancarlopedriglieri@outlook.com>; Mention<mailto:mention@noreply.github.com>
Asunto: Re: [openscope/openscope] New Airport: MDSD (#288)


Ya hice ambos cambios, pero debido al nuevo TMA, tendré que rehacer el terreno. Ahora mismo estoy de viaje y no tengo los programas necesarios para generar el terreno, pero cuando regrese lo haré.

**Comment by Fechulo** [comment]
No son vacaciones pero gracias! 😂

**Comment by pedriglieri** [comment]
😃 o bueno. Pues que disfrutes tu viaje 👍 y que te vaya bien

________________________________
De: Fechulo<mailto:notifications@github.com>
Enviado el: ‎28/‎3/‎17 14:30
Para: openscope/openscope<mailto:openscope@noreply.github.com>
CC: pedriglieri<mailto:giancarlopedriglieri@outlook.com>; Mention<mailto:mention@noreply.github.com>
Asunto: Re: [openscope/openscope] New Airport: MDSD (#288)


No son vacaciones pero gracias! 😂

**Comment by Fechulo** [comment]
Just to update anyone who doesn't speak Spanish: The airport is now almost done. I've made some changes as suggested by @pedriglieri and this means I will need to re-generate the terrain. However, I'm currently away so I can't do it from here. Apart from that there's a few more things I'd like to add to the video map and maybe some small traffic tweaks.

**Comment by Fechulo** [comment]
@pedriglieri The airport is finally done 😄 I've updated the terrain and added the coastline to the video map. If there's anything that you'd change let me know!

**Comment by pedriglieri** [comment]
Hola que tal?
Como puedo acceder a MDSD ? Ya que en la página principal no me aparece.

________________________________
De: Fechulo<mailto:notifications@github.com>
Enviado el: ‎15/‎04/‎2017 18:27
Para: openscope/openscope<mailto:openscope@noreply.github.com>
CC: pedriglieri<mailto:giancarlopedriglieri@outlook.com>; Mention<mailto:mention@noreply.github.com>
Asunto: Re: [openscope/openscope] New Airport: MDSD (#288)


@pedriglieri<https://github.com/pedriglieri> The airport is finally done 😄 I've updated the terrain and added the coastline to the video map. If there's anything that you'd change let me know!

**Comment by Fechulo** [comment]
@pedriglieri Todavía no está en el simulador pero puedes probarlo [aquí](https://openscope-dev-pr-289.herokuapp.com/).
