### ISSUE TITLE
Web keep loading but not starting in Mozilla Firefox

### ISSUE THREAD

**Issue by Izeras** [openscope/openscope#293]
I've been trying to play, but "http://www.openscope.co/" doesn't start the game. It keep loading and the wheel moving but nothing changed. It seems that it only work in Google Chrome.

**Comment by n8rzz** [comment]
This is a known issue and, coincidentally, we just started work on this (#263).

In the mean time, I would suggest using a different browser (Chrome), then you should be able to load things just fine.
