### ISSUE TITLE
Update Loading Screen

### ISSUE THREAD

**Issue by suhaildawood** [openscope/openscope#294]
I got some inspiration from the openScope logo and decided to create an updated loading screen:
https://cl.ly/2J1h372K3a1o ← Video

![image](https://cloud.githubusercontent.com/assets/1642260/24204904/432efeac-0ef0-11e7-99c0-2403f233942b.png)

It's built using SVG + CSS. Open to any suggestions!

**Comment by erikquinn** [comment]
Yeeessssssss!!!!! :heart_eyes:

**Comment by n8rzz** [comment]
![a-thousand-times-yes](https://cloud.githubusercontent.com/assets/3325985/24205207/befb5c7c-0ee8-11e7-9cf3-c856ef13e30c.gif)

**Comment by olafghanizadeh** [comment]
Now make this in SVG :D

**Comment by suhaildawood** [comment]
@olafghanizadeh I already have! The video was a screen recording 🙂  PR coming soon
