### ISSUE TITLE
Pause simulation when browser tab not in focus

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#296]
Currently, if the browser window with the simulator in it does not have focus, the game _kind of_ pauses (the aircraft do not move), but the screen continues to be redrawn, the positions recalculated, etc. If the game does not have focus, it should pause itself, and resume when the user presses the play button.

Additionally, an option could be added to the settings menu to disable this behavior, so the simulation will continue to run, even if the browser tab does not have the focus.

**Comment by n8rzz** [comment]
this will likely need to happen in `App` somewhere where we look at the `#paused` value and exit out of the game loop.

**Comment by erikquinn** [comment]
The core issue is probably that the clock continues to run while the tab is out of focus. That causes the physics to recalculate position when resumed using the elapsed time that includes when the tab was not in focus.

**Comment by erikquinn** [comment]
So it seems that there are a few tricky things going on here:
 - When openScope is the _active tab in chrome, the game runs, regardless of whether or not chrome itself has focus. It correctly chooses to NOT update the clock. :+1: 
 - When a _different tab of chrome_ is in focus, the game does not run _at all_ :-1: 
   - When focus returns to openscope, all it sees was that it was running 30 seconds ago, was _never paused or defocused_, and assumes it has taken all this time doing calculations, and that it should continue as normal. This results in it updating the clock based on `currentTime - timeOfLastUpdate`. :-1: 

I'm having trouble coming up with a way that we can tell whether or not the time since last update was spent in or out of focus. If we could know that, then we would be able to do the math to find out how much time we should be moving the aircraft. Trouble is, since the game instantly stops running, and instantly resumes, we don't have a way to say `when the tab goes out of focus, pause the sim`, because there's no indication that the sim ever actually went out of focus when changing between tabs.

**Comment by n8rzz** [comment]
good news, there is actually an event that is happening there which causes the calculations to stop. https://github.com/openscope/openscope/blob/9ae9fa97942efef63da3af66d6aea2b35a8b7f0f/src/assets/scripts/client/game/GameController.js#L97

These should be re-worked a little anyway.  But since we have access to the event, we can math from a `pauseTime` to `now`, etc.
