### ISSUE TITLE
Cannot Issue Commands to 1 Aircraft at SAME v4.1.2

### ISSUE THREAD

**Issue by scott-j-smith** [openscope/openscope#303]
Hi,

For some reason the game isn't letting me issue any commands to the highlighted aircraft (ARG9521).  Same thing happened when I first started this airport today, but thought it might be a browser issue (since I switched from another airport).  So I reloaded the browser and it started fine, got the first 2 flights going, and then this one won't accept any inputs... but later ones do.

I searched the open issues and don't see any other reports for this airport, or any open airport work pull requests.

Scott

![image](https://cloud.githubusercontent.com/assets/22403776/24765001/35a6cb36-1ac4-11e7-900e-c8f9e562b009.png)

**Comment by n8rzz** [comment]
long story short, this is because of a malformed airport json file.

**Comment by n8rzz** [comment]
@scott-j-smith could you verify this has been fixed here: https://openscope-dev-pr-304.herokuapp.com/

**Comment by scott-j-smith** [comment]
Hi Nate,

It appears to be fixed in that branch.  It happened very quickly in the
main game, but your version I played for 10 min. without it occurring.

On another note, your version for that airport the arriving flights are
coming in very high and very fast.  You may already be aware of this, but
if not...

They don't slow down unless you give a command, and they end up way to high
by the time they get near the end of the route because they don't have time
to descend.   In the first screen shot below, I only told the two arrivals
to slow down to sp 180 near the MUBEN fix, which was too late.

And because they come in so high, they don't even enter the control area
below max height and become active until well inside the zone.  In the
second screen shot, flight ARG7097 only JUST dropped below FL 245 and
became controllable.

Scott

[image: Inline image 1]

[image: Inline image 2]

**Comment by n8rzz** [comment]
Was this happening before?

The images didn't seem to come through either, could you repost them when you have a minute?

@Fechulo @RNGFavorsNoobs either one of you guys wanna investigate what Scott is talking about here?  Any changes can be included in the current branch.

**Comment by erikquinn** [comment]
Possible that this is only an issue with prespawned aircraft. I think the prespawn altitude used to be 10000 to all of them, and now it's the spawn altitude, and we don't do anything to reduce that spawn altitude even when we spawn them much closer than the spawn point.

**Comment by scott-j-smith** [comment]
Hi Nate,

Here are the pictures (below).  I don't see this issue in the main game, only in your branch.

Erik,

I see this issue on Nate's branch with aircraft being spawned during the game too (all of the new arrivals), not just the pre-spawned ones.

Hope this helps,
Scott

![image](https://cloud.githubusercontent.com/assets/22403776/24815166/4c0f7aa6-1ba2-11e7-88bb-bbfd6dc2796f.png)

![image](https://cloud.githubusercontent.com/assets/22403776/24815173/51495866-1ba2-11e7-8403-122e97117d94.png)
