### ISSUE TITLE
Remove unnecessary altitude restrictions

### ISSUE THREAD

**Issue by indianbhaji** [openscope/openscope#305]
In Aaaammmerricaa when an aircraft is put on a STAR, they are given an instruction to descend via the STAR (follow the restrictions on the STAR)

In the outside world, when an aircraft is put on a STAR, normally descent instructions are given individually one by one. For example, at Heathrow, the LAM3A has 'expect FL160 at SABER' on the chart. Such expect altitudes should not be included.

Airports which are affected by this include those in the UK, Germany, Belgium, France and a whole lot more...!

**Comment by indianbhaji** [comment]
Oops - I put Heatrow instead of Heathrow...

Well, they do have the MLS (microwave landing system at Heathrow)

**Comment by erikquinn** [comment]
This is kinda being addressed with the process of going through all the airports to meet the other standards, so it can be addressed that way. Closing this issue.
