### ISSUE TITLE
VHHH Departures Only Spawn on the LAKES Departure Route

### ISSUE THREAD

**Issue by scott-j-smith** [openscope/openscope#313]
Playing on VHHH for about an hour, ver. 4.1.2.  All departures are on the LAKES SID.  Never any others.  Another airport that needs reviewing for 4.3.0 or 4.4.0 I guess.

Thanks,
Scott

![image](https://cloud.githubusercontent.com/assets/22403776/24930171/8f4e170a-1ed6-11e7-9661-eb18bfe39faf.png)

**Comment by n8rzz** [comment]
that looks correct (though not desirable).  there is only that single departure spawnPattern defined for that airport.

**Comment by scott-j-smith** [comment]
Hi Nate,

But when I played this airport on an earlier version (on the zsla site)
they were spawning on all departure routes (BEKOL and OCEAN for sure, and I
think PECAN too).   Wouldn't that be more realistic anyway?  Maybe this is
a low priority enhancement for this airport at some point at least.

Thanks,
Scott

**Comment by Fechulo** [comment]
@scott-j-smith that's correct. When the new spawnPatterns were introduced, the used SID's and STAR's were ignored for most of the airports. So there's a lot of missing spawnPatterns in the game right now. We're slowly trying to add them all again but it's going to take a while...

**Comment by scott-j-smith** [comment]
OK, no problem!  Thanks, @Fechulo.  I will be patient and not raise new
issues for this.  :-)

Scott

**Comment by n8rzz** [comment]
@scott-j-smith ha, keep 'em coming as you see them!  The worst that happens is we close it as a non issue.  But then at least they're called out.

**Comment by scott-j-smith** [comment]
Ha!  OK, Nate.  Will do.  :-)

**Comment by scott-j-smith** [comment]
Note that when this airport does get reviewed at some point, the arrival spawn pattern for the route coming in from the bottom left needs adjustment.  It sometimes spawns two aircraft too close together.

![image](https://cloud.githubusercontent.com/assets/22403776/24967062/dbbc7618-1f76-11e7-9834-0e30f4c4b94b.png)

**Comment by n8rzz** [comment]
@scott-j-smith when are you going to join our slack channel?  slack.openscope.co

**Comment by scott-j-smith** [comment]
Ok, I just did!  I haven't used slack before, so I'll take some time this
weekend to figure it out.  Thanks!
