### ISSUE TITLE
Update color set to match openscope

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#317]
With the move to openscope, we need to get a fresh set of paint on the scope colors. See the `openscope-legacy` repository and #294 to get an idea of what we're looking to do with the colors.

For now, we can simply replace the colors in use. In the future (or for super-mega bonus points), we can create different color profiles, able to be changed by the user through the settings menu.

**Comment by n8rzz** [comment]
@suhaildawood may be working in something like this already.
