### ISSUE TITLE
Add all series of Airbus A340

### ISSUE THREAD

**Issue by headphase** [openscope/openscope#319]
I can work on this after I finish my JFK refresh but if anybody has some spare time, a couple airlines are in need of an A345 aircraft json (at the moment they are using A346 stand ins)

**Comment by indianbhaji** [comment]
For reference, see [Eurocontrol](https://contentzone.eurocontrol.int/aircraftperformance/details.aspx?ICAO=A345&ICAOFilter=A345)

**Comment by adamstyl** [comment]
A piece of advice that might prove huge time saver: Eurocontrol considers A343, A342, A345 and A346 comparable. You can copy A346 to A345.

**Comment by Marcel510** [comment]
Closing, A345.json has already been added.
