### ISSUE TITLE
New airport please: KDTW

### ISSUE THREAD

**Issue by 40000feetup** [openscope/openscope#329]
Add Detroit-Metro Wayne County Int'l Airport.

**Comment by headphase** [comment]
Great suggestion.  I'd enjoy helping implement DTW once I finish JFK.

**Comment by erikquinn** [comment]
:+1: This would be a good one. Another triple parallel hub airport where we can get video maps (not much in the terrain department probably though), and thorough documentation of the airspace.

**Comment by Fechulo** [comment]
KDTW is now available in the sim!
