### ISSUE TITLE
Actually USE the suffixes of procedures

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#33]
Given a procedure `ANKER`, users should be able to enter `SID ANKER1Q` and/or `STAR ANKER1Q`, depending on the type of procedure. Such was the intent of the `suffix` property, but it was never really fully hooked up, and airport creators have worked around it by creating individual procedures `PIK27X`, `PIK27D`, `PIK23X`, `PIK23D`, `PIK21X`, `PIK21D`, etc. Completing the functionality of the suffixes would eliminate the need for them to do this.

Originally reported in zlsa/atc#655.

**Comment by erikquinn** [comment]
Depends on #193.

**Comment by n8rzz** [comment]
@erikquinn @indianbhaji  given the following procedure (from `egll`):
```javascript
"BUZAD": {
    "icao": "BUZAD",
    "name": "Buzad",
    "suffix": {"09L":"3K", "09R":"4J"},
    "rwy": {
        "09L": [],
        "09R": []
    },
    "body": [["_LONR072D10", "A30+"], "BUZAD", "WOBUN", "DTY", "HON"],
    "draw": [["_LONR072D10", "BUZAD"]]
},
```

if a command was issued `STAR BUZAD3K`, that would work out to the `BUZAD` star with runway `9L`.

Am I understanding this correctly?

**Comment by indianbhaji** [comment]
@n8rzz Yes

**Comment by panther2** [comment]
Just adding the problem that ocurred on EDDL, as discussed on slack:
There is only one suffix for multiple (two) runways there. This occurs on every SID.
