### ISSUE TITLE
Aircraft not reaching targeted speed

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#340]
Sometimes aircraft will get "stuck" at a speed that is less than 0.1 knots away from the target speed, and not be updated, due to the fact that we were explicitly allowing a small level of error in the code. Really though, that is not needed, and should be removed to prevent cases like this.

This is the reason on a rare occasion, aircraft will start their takeoff roll, _appear_ to reach their rotation speed, and then just never rotate. It's because they rotate at 130, and are remaining at 129.994303546375. If the aircraft happens to calculate that speed between physics updates, they would end up getting stuck there forever.

Need to change this so aircraft will insist upon reaching their exact targeted speed.

**Comment by n8rzz** [comment]
Is there a reason we've never enforced any sort of precision limits on our calculations?  Some of these math errors could be alleviated be enforcing precision to only 3 or 4 digits, don't you think?

**Comment by erikquinn** [comment]
Well we _have_ used flexible precision, and it causes much more trouble than it's been worth (such as here). And when the math says "increase your speed as much as performance allows you to in the X seconds that have passed, until you reach a value of Y", it's really not that complicated, and adding that range of acceptable values actually makes it more complicated and prone for odd behaviors.

**Comment by n8rzz** [comment]
Fair enough. I only ask because JS gets a little fussy with highly precise numbers.
