### ISSUE TITLE
"Lost radar contact with" message is shown multiple times per event

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#345]
I was unable to get a screenshot, but I saw "lost radar contact with" message appear many, many times for a single aircraft. It was probably one that crashed into terrain, but that message should only be shown once, and probably in red.

**Comment by n8rzz** [comment]
@erikquinn This may have already been resolved

**Comment by erikquinn** [comment]
That's probable. I haven't seen it in a long time. Might as well close at this point. If it comes back, we can always reopen!
