### ISSUE TITLE
Airline Flight Number Rules

### ISSUE THREAD

**Issue by headphase** [openscope/openscope#352]
One simple way to make the sim more realistic and compelling for users would be to enable a way to define a set range of leading digits that a specific airline's generated flight numbers may start with.  This variable could be contained in the airline's JSON file and there should be one rule to apply to three-digit flight numbers, and another to apply to four-digit flight numbers.

For example, Delta-proper flight numbers range from 1-2999.  Seeing 'DL 6XXX', for example, is very jarring because it's an extreme rarity in real life. 

I don't know the guts of how this could be coded into the sim but here's how I imagine an excerpt of the airline JSON file could look:

```
    "icao": "dal",
    "name": "Delta Air Lines",
    "callsign": {
        "name": "Delta",
        "length": 4,
        "3DigitPrefix": [1, 9],
        "4DigitPrefix": [1, 2]
    },
```

where '3DigitPrefix' and '4DigitPrefix' are ranges that allow 3 digit flight numbers to start with any number between 1 and 9 and four digit flight numbers to start with either a 1 or 2.  Of course, it would also be possible to use a discrete number instead of a range.

**Comment by n8rzz** [comment]
this is an interesting idea.  essentially adding flightNumber _rules_.  this could get complex in a hurry, but perhaps providing a range similar to what you included above:
```javascript
"flightNumberRange": [MIN, MAX]

// 3 digits
"flightNumberRange": [100, 999]
// or for 4 digits
"flightNumberRange": [1000, 2999]
```

for reference, the sections of code that matter to this are:
- `AirlineController. generateFlightNumberWithAirlineModel()` https://github.com/openscope/openscope/blob/develop/src/assets/scripts/client/airline/AirlineController.js#L63
- `AirlineModel.generateFlightNumber()` https://github.com/openscope/openscope/blob/develop/src/assets/scripts/client/airline/AirlineModel.js#L220

**Comment by headphase** [comment]
@n8rzz  That way probably makes more sense haha

**Comment by erikquinn** [comment]
At that point, might as well also provide the ability to utilize multiple ranges with a 2D array, eg `[[725, 729], [780, 800]]`. Not like there would be a ton of demand for it, but its basically no harder to leave the option available.

**Comment by n8rzz** [comment]
would that be an actual use case?

**Comment by headphase** [comment]
Non sequential ranges would be useful to simulate how airlines with cargo divisions typically use a small but high range of numbers for cargo ops, for example:

http://flightaware.com/live/flight/QFA7581
https://flightaware.com/live/flight/QFA11/history/20170419/1520Z/KLAX/KJFK

That raises another point; would it be possible to include the ability to assign rules to individual fleet types?  This gets into some very fine grain control but it would be nice to have the option :)

**Comment by n8rzz** [comment]
so for point number one, I think that would be possible with what erik mentioned earlier:
>might as well also provide the ability to utilize multiple ranges with a 2D array, eg `[[725, 729], [780, 800]]`

to the second point, I would say that is possible as well but would take much more work.  I think we could accomplish that by specifying each fleet within the `callsign` block and providing a range for each.
```javascript
"callsign": {
    "name": "American",
    "length": 3,
    "90long": [MIN, MAX],
    "90default": [MIN, MAX],
    "long": [MIN, MAX],
    "default": [MIN, MAX]
},
```

**Comment by erikquinn** [comment]
Also I was thinking it would provide the possibility of specifying specific real world callsigns for a particular airport. For example, for Virgin America, I see every day flights 114, 97, 77, 84, 108, 63, etc. Some other airlines are in series more or less, like Porter, with 719/720/724/725/756/727/728/729. This could be implemented similarly to the way fixes are listed within procedures: an array of items, each of which CAN be an array that provides (in this case) a range of flight numbers.

**Comment by indianbhaji** [comment]
@erikquinn This would include alphanumeric callsigns too right?

**Comment by n8rzz** [comment]
@indianbhaji same logic, yes

**Comment by erikquinn** [comment]
Well, it may be trickier with the letters when describing the series. As in how do we tell it to increment the number part? Or the letter? Both? It's not really set up to differentiate and would take some minor finagling compared to number series.

**Comment by n8rzz** [comment]
I'm so sure it would be much different. If we have a range, we could probably handle things the same way. 

To be clear, are you talking about N numbers with specific trailing letters?

**Comment by erikquinn** [comment]
well those could be random, I mean more like regularly scheduled flights with alphanumeric callsigns. For example, how does one "increment" `VIR22Q`? To `VIR23Q`? `VIR22R`? `VIR23R`?

**Comment by n8rzz** [comment]
🤔 

Perhaps we accept two keys: `range` and `specific` (or some other wording) where range is a random. Inner within the range, and specific is a list of specific flight numbers that can also be chosen. 

I suppose _another_ tricky part about this is that specific flight numbers are usually tied to specific routes, yes?  We could do something with that too, but that would become a little more complex with perhaps another 2d array.

**Comment by erikquinn** [comment]
Yeah that would work.

As far as correlating flight numbers with routes, that is beyond the realm of randomly generated traffic. Once you head down that road, our parameters will conflict with each other ("I need more aircraft on this spawn pattern, and I want this airline, but it only has this flight number left which is reserved for a different route...") and 💩 gets real messy. The best way to achieve that level of granularity is by simply using scripted scenarios (where everything is defined by the scenario architect).

**Comment by n8rzz** [comment]
Yeah, good point.

**Comment by headphase** [comment]
Correct me if I'm wrong but if we can make it possible to set right number arrays for each fleet type, then correlating flight numbers to a route would be cake.  Just use a unique fleet type and tie that to both a spawn pattern and a single flight number in The stay section of the airline's callsign block

**Comment by n8rzz** [comment]
@erikquinn @indianbhaji this issue may have been addressed by a recent PR.  If so, lets close this out.

**Comment by erikquinn** [comment]
More or less I think. There's still some things discussed here we could do, but the important bit is done, so I think it makes sense to close and make new issues for enhancements to that feature in the future if needed.
