### ISSUE TITLE
Airlines using "ILS" landing procedure

### ISSUE THREAD

**Issue by devman0903** [openscope/openscope#363]
ILS has been very glitchy. Running the ILS command makes the airline go off the radar / re-routes planes away from the radar

I will submit screenshots when the game is back up "if not fixed by then"

**Comment by n8rzz** [comment]
Could you provide some steps to reproduce this one?

- airport
- command(s) issued
- any console errors present after the command was issued

**Comment by devman0903** [comment]
it may take a while. will you be on later.

**Comment by devman0903** [comment]
i gotta go

**Comment by devman0903** [comment]
will comment the specs later

**Comment by n8rzz** [comment]
You could also head on over to slack.openscope.co if you want some faster debugging help 😉 

Sounds good!

**Comment by n8rzz** [comment]
ahh, and yes.  I'm on most of the time (easier to reach me via slack)

**Comment by erikquinn** [comment]
Closing as duplicate of #38.
