### ISSUE TITLE
System commands with no arguments not working

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#364]
For example, the command `version` should print the simulator version to the console.

Within the CommandParser, this fails at `#_buildSystemCommandModel)` when called at line 150. It seems to expect _either_ a callsign _or_ an argument. For example, `timewarp` takes an argument and works just fine, but those that have neither aren't handled correctly.

Additionally, if those commands that _expect_ arguments (like timewarp) don't receive them, they may not be working properly. `timewarp` alone results in the canvas going blank, which could either be an issue with the parser freaking out, or it could be working properly, and the canvas can't figure out what to do when time stops (in which case, we should enforce a default argument of `1` in the parser to prevent this).

**Comment by panther2** [comment]
@erikquinn 

I knew about `timewarp`, but not about any other system commands.
Is there an overwiew to learn about them? Would be interesting...
Thank you!

**Comment by erikquinn** [comment]
Good point, those are actually not documented... added #365 for that. :smile:
