### ISSUE TITLE
Add "Airport File Standards" document

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#367]
This should outline a few different things for airport file development:

1. Content Requirements
 - terrain
 - polygonal airspace boundary
 - airways
 - ALL supported procedures
 - accurate traffic level (and info to back it up)
 - base video map
1. Requirements for "Premium (?) Airport" Designation
 - full documentation on facility's airspace
 - airspace and traffic flow diagrams
 - exceptionally high realism (subjective to local knowledge)
1. Style Requirements
 - on spacing, bracket newlines, key order, etc

**Comment by n8rzz** [comment]
how does this differ than openscope/openscope#184?  Couldn't most of this in that document?  Or do you envision this as a companion document with more specific, detailed information?

**Comment by indianbhaji** [comment]
In my opinion it'd be better to separate it. It's easier to see a checklist of what should be done rather than going through a large document just to check what needs to be done.

**Comment by n8rzz** [comment]
totally cool.  I just wanted to call that out.  We can always cross reference the two docs.

**Comment by erikquinn** [comment]
yeah `airport-format.md` would be explanations of how everything works, what it means, what it needs to work. This would be the requirements as far as quality control. If the airport does not meet these requirements, it will require extra work before being merged.

We're approaching the point where there is _more_ than enough variety available, and we need to begin increasing the quality of each, rather than the quantity. But knowing what can be improved for a given airport is a lot easier if we have a checklist of things that can elevate it to "premium" level (the next purpose for those little flags in the load list).

**Comment by n8rzz** [comment]
perhaps I should wait till this is finished until I start #94 so that I can write that to follow this doc?

**Comment by erikquinn** [comment]
@n8rzz Probably. If it weren't for the fact that we've already delayed everybody's airports updates for months, I'd want to implement #47 first as well, since it will require yet another massive airport rework. But we'll just have to cross that bridge when we come to it. :smiley:
