### ISSUE TITLE
Add squawk command

### ISSUE THREAD

**Issue by n8rzz** [openscope/openscope#372]
add new command `squawk` that instructs an aircraft to set their transponder code to a specific numeric value.

this feels like an easy task to knock out, we're going to need these in the future anyway.  this will be a good opportunity for somebody else to add a new command.

---

acceptance criteria:
- [ ] `squawk` and `sq` command definitions
- [ ] accepts a single arg, as a number with exactly 4 digits
- [ ] sets `AircraftInstanceModel#transponderCode` property
- [ ] full test coverage of `CommandParser` additions

**Comment by indianbhaji** [comment]
Make sure that you add a check for a valid squawk code, all the digits should be 1-7
