### ISSUE TITLE
Airports with non-procedural arrival spawn patterns crash game

### ISSUE THREAD

**Issue by Wittner** [openscope/openscope#373]
iMac 21.5-inch, Late 2015
macOS Sierra
Chrome 57...
Playing EIDW
When first arrival announces on screen, app freezes. Developer tools show (repeated over and over):

####
    AircraftStripView.js:387 Uncaught TypeError: Cannot read property 'toUpperCase' of null
    at AircraftStripView.value (AircraftStripView.js:387)
    at AircraftInstanceModel.value (AircraftInstanceModel.js:2023)
    at AircraftInstanceModel.value (AircraftInstanceModel.js:1879)
    at AircraftController.value (AircraftController.js:242)
    at App.value (App.js:392)
    at App.js:389
####

Here's the offending line for quick reference:
####
    switch (navMode) {
            case WAYPOINT_NAV_MODE.FIX:
                this.$heading.text(headingText);
                this.$destination.text(destinationText.toUpperCase());
    ...

**Comment by n8rzz** [comment]
well 💩 , this looks like #370 all over again.

**Comment by erikquinn** [comment]
![image](https://cloud.githubusercontent.com/assets/5103735/25396129/660a55e4-29b1-11e7-83c4-1fefefa5eb36.png)

@n8rzz Looks like it's a case of `destinationDisplay` being null because it was calculated by:
`destinationDisplay = this.fms.getProcedureAndExitName();` in `AircraftInstanceModel.updateStrip()`.

**Comment by n8rzz** [comment]
yup 🤕. 

because we try to set that `destination` property using the `RouteModel` and blah blah blah.  I left a note in that linked issue about the root cause.

**Comment by n8rzz** [comment]
I can't believe we never ran into this when we were testing it.  That's my bad, I should have run through some of these.

**Comment by n8rzz** [comment]
this issue will be resolved by #370 

closing

**Comment by Wittner** [comment]
Cool. Thanks guys.

**Comment by erikquinn** [comment]
And thank you for the report!

**Comment by erikquinn** [comment]
Fixed via #376.
