### ISSUE TITLE
Poor Localizer Interception

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#38]
Aircraft intercepting the localizer is very clunky; the turns are not smooth, and frequently overcompensate. The math for the turn calculations needs to be improved and simplified (so it is more clear how it works).

Also see zlsa/atc#711, n8rzz/atc#66, n8rzz/atc#86

Originally reported in zlsa/atc#717.

**Comment by n8rzz** [comment]
@erikquinn was this finished under openscope/openscope#139 ?  or is there still more to do here?

**Comment by erikquinn** [comment]
More to do. I'm working on a new from-scratch solution that may hold more promise.

**Comment by erikquinn** [comment]
Also having issues (due to the same cause, obviously) with the aircraft landing in the wrong place (see #568).

**Comment by binaryfunt** [comment]
I've noticed that when I have an A/C routed to a waypoint along the localiser then tell it to land, the path goes way off.

In the picture below, Ryanair 146 was routed to HOS, then told to land on 23

![screenshot 242](https://user-images.githubusercontent.com/14579418/35194159-96b52b86-fea6-11e7-86cf-8b1115c34190.png)

A workaround is to assign a heading to the A/C, e.g. turn left 01 degrees.

**Comment by paul-at** [comment]
This is a major issue, which just kills entire simulator experience for me. A pity, considering the staggering amount of work that has been put in to make this simulator.

10-20% of planes end up continuing landing off runway even when given clearance within 30 degrees of runway heading and being below glide slope.

There is also a secondary issue mentioned in #568. In my view planes not lining up is only half of the problem, the other half being planes not going around and continuing to land even when not lined up.

**Comment by erikquinn** [comment]
@paul-at I agree. Truth be told, I've been hiding from this one because of how disgusting and painful it will be to figure out. But that simply can't go on forever, and you're 100% right: this is unquestionably the single greatest issue with the sim at the moment. And in some cases it's so prevalent that it destroys all usability.

Elevated to the highest priority, and scheduled to begin work this month. We'll get it fixed. Definitely appreciate your candor and nudge here, it's time to deal with this one and get it fixed. :+1:

**Comment by paul-at** [comment]
@erikquinn thank you for your response. I tried to look in the code and found a potential issue in _calculateTargetedHeadingToInterceptCourse. The code has a condition that appears to disable lateral navigation on final: https://github.com/openscope/openscope/blob/develop/src/assets/scripts/client/aircraft/AircraftModel.js#L1603
This may be the immediate cause of flying straight off course in the late approach.

I may be mistaken about this one, but overall, assuming the code that controls flight phase/mode doesn't have a major issue, it seems that the only place that can make plane flight fixed heading when its supposed to track localiser is one of the conditions returning current heading or course inside _calculateTargetedHeadingToInterceptCourse.

**Comment by erikquinn** [comment]
Right, that's the only reason it's so tricky. To get it to "fly this heading and then intercept the localizer". 

I think the issue lies in something to do with the airplane changing its mind on whether it should be starting the intercept yet or not. It starts to turn inbound, then says "no, stop! Fly the heading!". And then sometimes it'll get stuck being wrongfully prevented from turning the right direction.

The concept was that if we waited until the very last second to start the turn, then with wind taken into account, you may have turned late without realizing it. So instead, it would turn like a minute early, and make a wider turn to allow it the chance to correct any effect of wind. During that turn, if the new "time-to-turn" got more than a minute in the future, we would fly straight until a minute before, and resume the turn. Repeat until established. I think it was a good concept, but somehow it's got some strange and severe problems.

**Comment by paul-at** [comment]
Thank you @erikquinn, with your description the logic in code finally made sense and I think I managed to fix all issues.

The problem with getting stuck and flying across course without intercepting was trivial. The interceptAngle calculations were broken due to severity_of_correction parameter, resulting in _calculateTargetedHeadingToInterceptCourse method returning absurd angles of tens of thousands degrees. So at high angles the target heading was assigned to effectively random value until intercept wasn't possible. Changing severity_of_correction to 1 fixed it.

Off-runway landings from unstabilised approaches (#417 and #419) were much harder to solve. I had to implement going around procedures, didn't test extensively but overall seems to work.

Don't understand why you don't accept pull requests, attaching the [patch](https://github.com/openscope/openscope/files/2125767/patch.diff.txt).

**Comment by n8rzz** [comment]
@paul-at thanks for looking into this one and offering a fix.  We really appreciate contributions from the community.

We _totally_ accept pull requests, just not from forks.  And the reasons are three-fold:
- we can't see code coverage changes in a PR 
- we can't run our CI process (unit tests)
- we can't leverage heroku review apps

If you'd like to contribute, we welcome all who want to help.  The only step is for @erikquinn to send you an invite.  Once you're in the org, you can create a pull request within this repo.

I'd also invite you to take a look through our documentation (if you haven't already):
- https://github.com/openscope/openscope/blob/develop/CONTRIBUTING.md
- https://github.com/openscope/openscope/blob/develop/documentation/git-flow-process.md

We've gone to great lengths attempting to document the major parts of our process so we don't need to repeat ourselves all the time.  So I'd encourage you, if you haven't already, please read through those two docs.  

One last thing, if you plan to contribute please feel free to join our (now 100+ member strong) Slack channel (slack.openscope.co).  There is a good group of folks who are willing to lend a hand and answer questions.  Slack is faster than github comments, so don't be shy, we're pretty friendly.

**Comment by erikquinn** [comment]
^

And @paul-at if even if that's not of interest, the patch is appreciated, I'll have a look sometimes and fire up a new branch and PR so we can have a look at your work and verify it works, and go from there.

In short, it's just our policy that we won't _merge_ an external PR, because of the reasons Nate mentioned. But above all, we want the fixes, so patches, external PRs, zipped js files, snail mailed printouts, I don't care; as long as it follows the code conventions and fixes the problem, there's somebody willing to do the paperwork (aka "easy part"). Cause lord knows we've got some problems scattered about. :wink:

**Comment by erikquinn** [comment]
@paul-at invited to repo just now, check email and come aboard if you'd like to keep the changes coming! :smiley:

**Comment by erikquinn** [comment]
@paul-at Added your patch as `bugfix/38` branch, PR available in #1016. Thanks again! Will create a review app so we can try it out and make adjustments.

**Comment by paul-at** [comment]
@erikquinn thank you for taking it forward!
