### ISSUE TITLE
SID errors and a couple of warnings in console on startup

### ISSUE THREAD

**Issue by Wittner** [openscope/openscope#381]
Hi,

iMac 21.5-inch, Late 2015
macOS Sierra
Chrome 57...
Playing EIDW

[ INFO ] Version v5.0.1
[ INFO ] devicePixelRatio: 1

Not sure if this is an issue or not as it doesn't so far appear to affect the gameplay.

    StandardRouteModel.js:354 The 'LIFFY' procedure does not contain exitPoints or entryPoints. If 
    this is a SID, at least one exitPoint must be defined. If this is a STAR, at least one entryPoint must 
    be defined.
    value @ StandardRouteModel.js:354
This appears for 9 (all?) of the SIDs for EIDW

and these warnings also appear on bootup before [ INFO ] messages

    SpawnPatternModel.js:618 TOO FEW ARRIVALS IN SURGE! Requested: 10 acph | Acceptable 
    Range for requested entrail distance: 18 acph - 45 acph
    value @ SpawnPatternModel.js:618

and

    TOO FEW ARRIVALS IN SURGE! Requested: 10 acph | Acceptable Range for requested entrail 
    distance: 18 acph - 45 acph
    value @ SpawnPatternModel.js:618

**Comment by indianbhaji** [comment]
Not a problem at all, it's just a case of updating airports to use the latest specifications. Eventually those will disappear when we get round to updating them. Closing!

**Comment by Fechulo** [comment]
These issues have actually been fixed with #208 which hasn't been merged yet

**Comment by n8rzz** [comment]
@Wittner just to add a little more context, the codebase has gone through a substantial amount of change in the last 6 months.  Those warnings are there as a reminder to authors that and airport definition is incomplete.  

Currently we are only showing errors for standard routes (sids/stars) and spawn patterns (which will show up as warnings).  In the near future (via #94) airport file validation will be much more exhaustive.  This will enable airport authors to simply load the app and be able to see the pieces that still need work.

In addition to that, we are working on nailing down documentation on both what an airport file could look like and what kind of information should be required (#184 and #367).

**Comment by erikquinn** [comment]
And the month of May is the sprint for all the airport work. So you can expect to see all these sorts of things fixed on the [development app](http://openscope-dev.herokuapp.com) once 208 is merged. And merges of the many airport pull requests begins on the first of May (in four days).

**Comment by indianbhaji** [comment]
@erikquinn Do we work bank holidays?

**Comment by n8rzz** [comment]
Holidays!?  Ha, this is open source, there are no holidays or days off.

**Comment by Wittner** [comment]
Thanks for the info. I was trying to get exactly that - a bit of context so that's good. Now I'll have a better idea of what's an issue going forward. I'm a big fan of ATC sim stuff and a JavaScript programmer although having looked at the codebase I don't think I'm as used to the opinionated approach as you guys. My stuff tends to be functional (in the JS sense) and modular but your code looks really, really lovely. However, I'd be happy to do a bit of grunt work if it helps the cause and if you need help. Otherwise I like the way the sim is shaping up and I'll keep an eye on the progress of those arrivals. Look forward to using the app again when the arrivals are working :-) Keep up the good work.

@n8rzz - Holidays are probably when most open source gets written! ;-)

**Comment by n8rzz** [comment]
@Wittner yeah, we are taking a very heavy Object Oriented approach.  there are some sprinklings of functional but, for the most part, that stuff hurts my head.

We're always looking for help, so if you want to contribute mr @erikquinn can add you as a contributor on the repo and we can go from there.  you should also join the [slack channel](http://slack.openscope.co) cause it's much easier for questions and such.  Also, review the [tools readme](https://github.com/openscope/openscope/tree/develop/tools) which will give you a little more info on setting things up locally.
