### ISSUE TITLE
Compass rose is misaligned

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#39]
The compass rose displayed when an aircraft is selected is not aligned properly; it should be aligned relative to the position of the selected aircraft; instead it is relative to the airport.

Originally reported in zlsa/atc#718.

**Comment by erikquinn** [comment]
Additionally, this would be one of the things that should be enabled/disabled in the settings menu (defaulted to _off_).

**Comment by felixscheffer** [comment]
Issue still exists:

![image](https://user-images.githubusercontent.com/1678164/48985061-27852300-f104-11e8-84f0-2ec5a33502a5.png)

**Comment by n8rzz** [comment]
Hmm, fooled by `.shouldDeepRender()` again.  I was under the impression we had removed it.  As my esteemed colleague @felixscheffer has pointed out, we have not.  One thing of note is that the compass isn't visible unless you have an aircraft selected _and_ trigger a deep render (pan/zoom).

The big question here is: do we still want to support this compass?  I don't think it provides a whole lot of value and it's pretty expensive to draw every frame (when an aircraft is selected).  What do the real scopes (or even IVAO) do here?

**Comment by felixscheffer** [comment]
#45 is probably the way to go.

**Comment by n8rzz** [comment]
agreed.  that gets us closer to reality
