### ISSUE TITLE
Missing document 

### ISSUE THREAD

**Issue by panther2** [openscope/openscope#404]
In the current `airport-format.md` of the `development branch` , line 255, we see

`- **airspace_class** ― The FAA class of the airspace. For non-US airports, please review [this FAA airspace classification document](faa-airspace) and find the closest match based on the way the local airspace is treated.
`

The document is linked to [this FAA airspace classification document](https://github.com/openscope/openscope/blob/develop/documentation/faa-airspace)

However, a 404 error is returned as this document appears to be missing.

**Comment by n8rzz** [comment]
Oh 💩, I think that's just missing a `#` symbol inside the link.

**Comment by erikquinn** [comment]
Resolved via #405. Closing.
