### ISSUE TITLE
Abort Command doesn't provide feedback

### ISSUE THREAD

**Issue by scott-j-smith** [openscope/openscope#416]
Hi all,

Issued the "abort" command to an arrival at KPHX because it was way to high in altitude to intercept the ILS without a penalty.  The command was accepted, but the display still showed the open circle symbol indicating it was trying to intercept the ILS.  See screen shot.  I don't know if the command worked, and it was just a display glitch, or actually something wrong with the command.

A more minor, secondary issue is of course why the flight was so high.  That STAR might need to be reviewed.  Flight SKW9466, on the BRUSR1 STAR.

Scott

![image](https://cloud.githubusercontent.com/assets/22403776/25627609/29c9966e-2f31-11e7-8605-a3a83eb67467.png)

**Comment by n8rzz** [comment]
was that an aircraft that was spawned on load?  or had you been running the sim for a while?

**Comment by scott-j-smith** [comment]
Hi Nate,

I was running for 20 min. when that one spawned.  This airport only spawns 4 departures and 0 arrivals on startup.

Scott

**Comment by n8rzz** [comment]
thanks @scott-j-smith.

there is likely a problem with the spawn altitude range + distance to airport (the aircraft doesn't have enough time to descend in the space allotted).

The `abort` command, however, may be a different animal.

**Comment by erikquinn** [comment]
The `abort` command has been deprecated. Closing.
