### ISSUE TITLE
Refine sprint process checklists

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#418]
### General Changes
- reorder chronologically so it's less painful to navigate
- fix numbering in release procedures section

### Release Procedures:
New step 7: Merge `master` into `develop` with `git merge master`. This will merge the merge commit created in step 3, just to keep master and develop even at the start of each new sprint. _No actual diff should be observable from this._ You can check by fetching and running `git diff origin/develop`.) Include a commit message of `ARCH - Update with master`.

**Comment by n8rzz** [comment]
>No actual diff should be observable from this. You can check by fetching and running git diff origin/develop.)

This part could be simplified by verifying that the last commit sha is the same for both branches.

**Comment by erikquinn** [comment]
@n8rzz It won't be, though. `origin/develop` will have all the _code_ from `master`, but it won't have all the _commits_ (namely that develop will not have the `ARCH - Deploy v5.1.0` merge commit).

The idea is that there are no _changes_ to merge, but that we might as well merge the SHAs so `develop` and `master` are `even` at the close of the sprint.

**Comment by n8rzz** [comment]
sorry, by last commit I mean the point at which `master` and `develop` are synced up _before_ deploy.  the shas should be the same at that point.  I'll try to get working on this one tonight/tomorrow and we can continue the discussion in the PR.
