### ISSUE TITLE
Include water in terrain files

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#420]
We can show hills and such, but being able to also show shorelines would be sweet, and give a lot more context to the terrain you see in certain airports (GCRR, EIDW, KSFO, many others).

**Comment by Fechulo** [comment]
Do we want to do this using the terrain files or on a video map like in MDSD (#288)?

**Comment by erikquinn** [comment]
In the terrain file would really be cool, because it's enclosed in a polygon, we can enable/disable the water independently of the terrain (if we built that in), we can _fill_ the area with a certain color to indicate water (and easily change said color), etc. Video maps with shorelines are great too, but this would be easier to implement across all airports than editing and/or creating video maps (which can't contain fills anyway).

**Comment by headphase** [comment]
Yes please!!!

**Comment by oobayly** [comment]
This could be handled relatively simply. I'm in the process of putting a QGIS plugin for importing airport data so it can be edited easily. This is actually what kicked off #1436 

Coastline and lake data can be imported from ~~GSHHS~~ GSHSG to create a water polygon at 0ft.

![image](https://user-images.githubusercontent.com/3430117/64920034-835f8c00-d7aa-11e9-9f91-3db52826c19c.png)
