### ISSUE TITLE
Ability to change length of PTL from within game

### ISSUE THREAD

**Issue by MisterHighQ** [openscope/openscope#423]
Modify `PTL_LENGTH: 1` in `src/assets/scripts/client/constants/canvasConstants.js` to a variable PTL_LENGTH that can be changed from within the settings of the game.

Edit: Presently, it's difficult to focus on the direction and current position of the aircraft with the 1 minute PTL lengths that are too long and distracting.

**Comment by n8rzz** [comment]
@erikquinn hmm, I think we actually have an issue for this already?  Maybe buried in the requirements of some User Settings issue somewhere?

**Comment by erikquinn** [comment]
Yes, #115.

In the meantime, it may be worth adding an "ugly solution" such as `scope {ptl_length: 0.5}` where users can change a few basic things without an actual attractive UI. Because changing the settings is the easy part it's creating the buttons that will take longer to get around to.

**Comment by MisterHighQ** [comment]
That alone would be fantastic until something more rigid and permanent can be developed!
