### ISSUE TITLE
altitude aa leads to NaN

### ISSUE THREAD

**Issue by ij1** [openscope/openscope#424]
Issuing "a aa" to an aircraft results in "maintain NaN" and NaN to the flight's strip.

**Comment by n8rzz** [comment]
this should be handled in the `argumentParser`.  strange that passing strings actually makes it through?

**Comment by ij1** [comment]
altitudeValidator does not attempt conversion to number (and then check for NaN) like e.g. headingValidator does.
altitudeParser just uses convertToThousands directly for args[0] but doesn't run any check for the resulting value.

**Comment by n8rzz** [comment]
Well 💩. At least this is easy fix.
