### ISSUE TITLE
KSFO needs an update

### ISSUE THREAD

**Issue by panther2** [openscope/openscope#427]
While looking at https://github.com/openscope/openscope/pull/425#issuecomment-299657277 I realized that the SID OFFSH9 has been renamed to OFFSH1 (Charts valid from Nov. 3, 2016).

**Comment by indianbhaji** [comment]
This should be part of the Epic I made on zube.io, do you have access to it @panther2?

**Comment by panther2** [comment]
Not yet, @indianbhaji . 
I will contact you on slack about that, soon.

**Comment by n8rzz** [comment]
invite sent
