### ISSUE TITLE
Using ..fix ending in a departure spawn breaks scoring & other stuff

### ISSUE THREAD

**Issue by ij1** [openscope/openscope#437]
With departure spawn routes such as this:
  https://github.com/openscope/openscope/blob/feature/390/assets/airports/efhk.json#L824
...Instead of points (& radio call) when the aircraft leaves the area, I get: waypointName is null from hasWaypoint().

**Comment by n8rzz** [comment]
@erikquinn didn't we just enter an issue similar to this the other day?  I can't seem to find it ant the moment, though.

**Comment by n8rzz** [comment]
ah, here it is.  this could be related to: openscope/openscope#434

**Comment by erikquinn** [comment]
Yes I believe this is a duplicate.

**Comment by n8rzz** [comment]
@ij1 could you take a look at #434 and see if that differs from what you saw that prompted this issue?  If there is some difference, please edit your notes above.

Also, openscope/openscope#33 is currently in process and touches a lot of the files same files 434 would.  434 should be tackled after openscope/openscope#33 

Be warned if you do decide to start digging in on it :wink:

**Comment by ij1** [comment]
Probably a duplicate (if you believe so). I noticed it after I created this issue, however, it was just quite vague (so I wasn't sure whether it referred mainly to lacking SID entirely which is not the case in my case).

Anyway, at least when beginning with SID, everything seems to work but this part at the airspace boundary.

(I didn't have any plans about it :-)).

**Comment by n8rzz** [comment]
@ij1 thats cool.  We tend to lean on the create an issue first and then consolidate later.

don't worry about #434, I just wanted to call that out in case you were going to look into it.
