### ISSUE TITLE
KMSP: Excessively low departure spawn rate

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#44]
MSP needs to have its departure spawn patterns looked at, and the spawn rates adjusted to be more reflective of the actual traffic. They are currently set so low that there are almost no departures in the game.

Originally reported in zlsa/atc#737.

**Comment by n8rzz** [comment]
will fix as part of n8rzz@243

**Comment by n8rzz** [comment]
wrong button :-( 

This can at least be adjusted as part of the spawnPattern additions for [n8rzz#243](https://github.com/n8rzz/atc/issues/243)

**Comment by erikquinn** [comment]
Rolled into #243.

Closing.
