### ISSUE TITLE
Add `*T` measuring

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#45]
Using two clicks, the heading and distance between two points should be calculable and displayed to the user to aid in vectoring. In the STARS system, this is accessed via [*T (click) (click)], and in ERAM it's the "RNG BRNG" button, and click click. Need to figure out which to emulate or how else to most easily expose this functionality to the user.

Edit: this should include the ability to snap to aircraft or to a static position when no aircraft is within a specified distance. Includes aircraft to aircraft, aircraft to point, point to aircraft, and point to point.

Originally reported in zlsa/atc#740.

**Comment by felixscheffer** [comment]
We could:
1. use the right mouse button
2. use left mouse button + modifier (for example shift + left mouse button)
3. add a *T button to the command bar

**Comment by erikquinn** [comment]
Right mouse button is already used for panning. Personaly I like option 2 and 3 together-- satisfies the realism junkies and the casual users.

**Comment by oobayly** [comment]
Sorry for spamming the issue. I hadn't considered that I'd referenced it in the commit.
