### ISSUE TITLE
Vectors are treated as fixes

### ISSUE THREAD

**Issue by Fechulo** [openscope/openscope#451]
Airports that use the new # vector method throw warnings since it thinks they're fixes. There should probably be an exception for 'fixes' beginning with # when checking if they exist
![260](https://cloud.githubusercontent.com/assets/13125311/25875835/853bd7ba-3511-11e7-9d60-7a591f3fb40c.PNG)

Aircraft who are on a heading specified in the airport file show #[hdg] on their tags, when they should just show the heading without the `#`
![140](https://cloud.githubusercontent.com/assets/13125311/25875837/8748ee9e-3511-11e7-9f10-9fe4773552c8.PNG)

---

Related: #467.

**Comment by n8rzz** [comment]
we should also make sure there is some logic in there for hold fixes `@FIXXA` as well 

the second part will (should) be addressed as part of openscope/openscope#285

**Comment by erikquinn** [comment]
Dynamic strips will be dead soon enough anyway, really it's just the warning that needs to be addressed.

**Comment by n8rzz** [comment]
has some relation to openscope/openscope#467
