### ISSUE TITLE
Updates to airport-format.md

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#452]
- [x] `arrivalRunway`
- [x] `departureRunway`
- [x] `restricted`
- [x] `airways`

- note that empty draw sections must be empty 2D, not just 1: `[[]]`, not `[]`

**Comment by ij1** [comment]
There's also lack of whitespace in "runways":[ in airport-format.md that would be nice to take care of once the documentation gets updated.

**Comment by n8rzz** [comment]
I'm not sure we need whitespace in the runways block.  If anything, we need less of it. 

I may be in the minority with that opinion though. 

All the json files get minified for production anyway, so it's really a moot point for me. Whatever you guys want to do.
