### ISSUE TITLE
EGNM missing star and sid that terminates within controlled airspace

### ISSUE THREAD

**Issue by n8rzz** [openscope/openscope#453]
_originally reported in #445 by [calin-pere](https://github.com/calin-pere)_

So, I did some debugging yesterday, and it seems to be an issue with the airport file. I was looking at the egnm.json and it has this "route": "EGNM.NELSA.NELSA" spawning pattern but it doesn't have that sid for rwy 14. So maybe extra verification when loading airports ?

Also , I've discovered another issue on that airport file , the POL sid : the POL waypoint is reached before airspace exit is checked so the mode control is set to HOLD determining a bad exit from airspace.

If you need further clarification please ask.

**Comment by indianbhaji** [comment]
@n8rzz `EGNM.NELSA.NELSA` is only valid for runway 14?

**Comment by n8rzz** [comment]
@indianbhaji thats how it is defined now.  whether or not that is correct I cannot say, I'm not an airports guy 😉 

This airport seems suspiciously sparse on procedure definitions and may require some additional work than what was called out above.

**Comment by indianbhaji** [comment]
@n8rzz unless you want fiction procedures, have fun! :P

**Comment by erikquinn** [comment]
> If you need further clarification please ask.

I'm not sure I understand any of the above conversation. :laughing: What exactly is the issue here? Perhaps the crash is no longer an issue because of #505 (feature #434)?

**Comment by indianbhaji** [comment]
@erikquinn https://github.com/openscope/openscope/pull/493

**Comment by erikquinn** [comment]
@indianbhaji So this can be closed then?
