### ISSUE TITLE
StandardRouteModel throws due to vector waypoints lack of a positionModel

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#467]
`StandardRouteModel._updateWaypointsWithPreviousWaypointData()` crashes when trying to calculate distance between waypoint lists that include vector waypoints (eg `"#320"`) because those waypoints do not have a position.

**Comment by n8rzz** [comment]
@erikquinn could you include an example of the routestring in the fms that's causing this to throw?

**Comment by erikquinn** [comment]
In my case on #462, it's actually because of a vector waypoint within a procedure. But a simple `["FIXXA", "#320", "FIXXB"]` should do the same.
