### ISSUE TITLE
Can't load game on Safari (but on Chrome)

### ISSUE THREAD

**Issue by jakobeng1303** [openscope/openscope#473]
Can't be the internet and works perfectly fine with Chrome

**Comment by n8rzz** [comment]
- when you say can't load, do you mean the splash screen never goes away or you only see a green page?
- what version of safari are you using?
- do you see any console errors in safari (located in the dev tools window https://developer.apple.com/safari/tools/)?  I'm guessing not, but want to be sure.
- are you on windows or Mac?

Safari represents about 8% of our traffic, so if this is a bug, I imagine you're not the only one seeing it.

**Comment by n8rzz** [comment]
I just tried safari locally, and everything loaded just fine.  Though it did take a little longer than with Chrome.  I should note: I am on a mac with the latest version of safari.

**Comment by jakobeng1303** [comment]
I'm not getting past this point with Safari Version 10.1.1 (12603.2.4) and MacOS version 10.12.5 (16F73)
<img width="2560" alt="bildschirmfoto 2017-05-21 um 13 41 47" src="https://cloud.githubusercontent.com/assets/19208045/26283555/625aed76-3e2b-11e7-9864-bd6ab2413a94.png">

**Comment by jakobeng1303** [comment]
and Adblock is not the problem

**Comment by n8rzz** [comment]
Are you seeing any console errors?

**Comment by jakobeng1303** [comment]
<img width="422" alt="bildschirmfoto 2017-05-21 um 15 31 44" src="https://cloud.githubusercontent.com/assets/19208045/26284408/ab0c88c2-3e3a-11e7-85d9-9c7f179788e5.png">
<img width="909" alt="bildschirmfoto 2017-05-21 um 15 31 35" src="https://cloud.githubusercontent.com/assets/19208045/26284409/ab10f8e4-3e3a-11e7-8cc5-72752569937d.png">
<img width="304" alt="bildschirmfoto 2017-05-21 um 15 31 50" src="https://cloud.githubusercontent.com/assets/19208045/26284407/ab0c5e88-3e3a-11e7-9a20-db656ca72c9b.png">

As a matter of fact now I do

**Comment by n8rzz** [comment]
I see two problems:
- this first is the obvious `OTHH: no such airport`
- the other is the second screenshot with the invalid coordinate (there are two north coordinates)

It may be trying to restore the airport from a local storage value. In December tools, click on the Storage tab -> local storage and then change the value of `arc-last-airport` to `ksfo` And then refresh

That's should at least let you load the app.

**Comment by jakobeng1303** [comment]
sorry but what are December tools?

**Comment by n8rzz** [comment]
Ha, no that's my fault. That was supposed to be _Dev_ tools.

**Comment by jakobeng1303** [comment]
oh ok :D

**Comment by jakobeng1303** [comment]
Thanks a lot!!! It's working again
