### ISSUE TITLE
Airport Revival :: Flughafen Wien-Schwechat

### ISSUE THREAD

**Issue by jakobeng1303** [openscope/openscope#474]
Vienna International Airport (German: Flughafen Wien-Schwechat; IATA: VIE, ICAO: LOWW) is the international airport of Vienna, the capital of Austria, located in Schwechat, 18 km (11 mi) southeast of central Vienna and 57 km west of Bratislava. It is the country's largest airport and serves as the hub for Austrian Airlines and a base for Eurowings Europe. It is capable of handling wide-body aircraft up to the Airbus A380. The airport features a dense network of European destinations as well as long-haul flights to Asia, North America and Africa. In 2017, the airport handled 24.4 million passengers, a 4.5% increase compared to 2016.

- [x] basic airport information
- [ ] new terrain
- [ ] new airspace
- [ ] new fixes
- [ ] restricted areas
- [ ] airways
- [ ] SIDs
- [ ] STARs
- [ ] spawnPatterns
- [ ] videomap

**Comment by n8rzz** [comment]
@jakobeng1303 I created #475 for point number one.  Could you provide an example route for which this problem occurs in that new issue?

**Comment by n8rzz** [comment]
I'll let @erikquinn @indianbhaji @Fechulo or someone else chime in for points 2 & 3.

To your last point: 
We have adopted use of an `entry.procedure.airport` format for arrivals and `airport.procedure.exit` for departure routeStrings.  This string format is the basis of _a lot of internal logic_ and is not likely to change anytime soon.  We do aim for realism, though, so if you can make the case or do the work, we might consider it.  But this one is not likely.

**Comment by indianbhaji** [comment]
`entry.runway.airport` doesn't always work for Europe.

**Comment by erikquinn** [comment]
2. Agreed, it will need an update. 
3. Whatever the people want :smiley:

**Comment by indianbhaji** [comment]
I'm afraid the entire airport in the state it was two days ago isn't just a *problem*. The entire file needs rewriting, which I started yesterday.
