### ISSUE TITLE
Consolidate warnings for missing fixes in airport files

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#480]
The sim currently puts warnings into the console for any fixes that are being used but have not been defined in the `fixes` section of the airport json file. They show up as separate entries, and often multiple times. If they could instead be put into an array that clears duplicate elements and sorts, that would be a much easier thing to work with. For example, I copy and paste that list into skyvector (since its waypoint database seems to be the most comprehensive), use the nav log thing to generate a pdf including the coordinates, and then sublime to reformat them as needed.

![image](https://cloud.githubusercontent.com/assets/5103735/26287994/053b06e2-3e55-11e7-8b12-e9d79291043a.png)

Related: #94.

**Comment by indianbhaji** [comment]
:+1 exactly what I do sometimes
