### ISSUE TITLE
Add unique TransponderCodes and CIDs

### ISSUE THREAD

**Issue by n8rzz** [openscope/openscope#483]
we need a way to:
-  keep track of issued codes (codes in use)
- generate new codes for spawning arrival aircraft
- warn controller when attempting to assign a code already in use

this need not be a big class.  we can follow a similar pattern that was used for managing flight numbers and use a recursive pattern for generating unique numbers.  this class would likely live in the `AircraftController` and would be consulted with when instantiating a new aircraft _or_ when a new code is about to be issued.

---
- [x] make stripView list closed onload
- [x] rotate stripView-trigger based on open state
- [x] add CID number generator
    - [x] unique
    - [x] non-sequential
    - [ ] support `001 - 999`
- [x] add transponderCode generator method
    - [ ] allow `N` numbers to receive `1200`
    - [x] disallow invalid transponder codes
- [x] hook into command lifecycle when transponder command is issued

**Comment by erikquinn** [comment]
We will need the same for CIDs (three digit unique no sequential numbers used by en route). Just bringing that up in case it's preferable to do them together or with the same generic class.

**Comment by n8rzz** [comment]
🤔 

Might be better to abstract that to a factory or something then.  hmmm...

**Comment by n8rzz** [comment]
@erikquinn in regards to the `1200` transponder code.  wouldn't a GA aircraft under VFR be issued a transponder code _before_ entering controlled airspace?

**Comment by erikquinn** [comment]
Kinda. They would be issued a discrete code before  being allowed to enter airspace that requires positive radar identification... Which is just Class B (and A I guess, though VFR is prohibited in class A anyway).

So they could be wandering around the portions of the airspace of a non-elevated classification (the Class E "associated outer area") for example and may or may not be interacting with ATC, but will be squawking 1200, probably just like many other VFR aircraft doing the same. We would only see the altitude on our scope. 

I'm curious though, why do you ask?

**Comment by erikquinn** [comment]
Two quick things here:

> warn controller when attempting to assign a code already in use

Really, the controller shouldn't be doing any of that at this point. More scope-side commands will have to exist before that's possible. As far as a warning existing, the only warning they should receive is from the scope in response to the scope command, or when two aircraft are observed by the radar to be squawking the same code (I can find out what this should look like).

And the second, for the same reasons, is just that all GA aircraft (`n` airline) are to be treated as IFR with normal squawk assignments the same as any other airline.

**Comment by n8rzz** [comment]
Well as far as current functionality, are you ok with the message that is in there?  The important thing is that we have all the logic in place. If we decide to move it to some other place (scope commands, etc) we can.
