### ISSUE TITLE
add meta tags to index.html

### ISSUE THREAD

**Issue by n8rzz** [openscope/openscope#484]
our SEO is crap.  it would be good to have a readable search preview.

<img width="627" alt="screen shot 2017-05-23 at 8 32 46 am" src="https://cloud.githubusercontent.com/assets/3325985/26356609/394d486c-3f92-11e7-82b6-bee90051f28f.png">

**Comment by sam-irl** [comment]
Fixed in #580, closing

**Comment by erikquinn** [comment]
@sam-irl This will be closed when #553 is merged; we keep them open until then.

**Comment by erikquinn** [comment]
OH! It _has_ been merged. My bad. Usually they're all set to auto-close.

Un-reopening (aka closing again) :laughing:

**Comment by n8rzz** [comment]
Yeah, my fault.  I used the wrong term in the PR. `completes` instead of `resolves`
