### ISSUE TITLE
Erroneously alphanumeric callsigns

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#49]
Example file that is shown with alphanumeric flight numbers, and shouldn't have them (bad):
```
{
  "icao": "JBU",
  "name": "JetBlue",
  "callsign": {
    "name": "JetBlue",
    "length": 3,
    "alpha": false
  },
  "fleets": {
    "default": [
       ["A320", 130],
       ["A321", 27 ],
       ["E190", 60 ]
    ]
  }
}
```

Example of one that doesn't have alphanumeric flight numbers, and shouldn't have them (good):
```
{
  "name": "FedEx Express",
  "callsign": {
    "name": "Fedex",
    "length": 4
  },
  "fleets": {
    "default": [
      ["A306", 68 ],
      ["A310", 8  ],
      ["B752", 119],
      ["B763", 32 ],
      ["B77L", 32 ],
      ["DC10", 49 ], 
      ["MD11", 58 ]
    ],
    "feeder": [
      ["C208", 241],
      ["AT43", 26 ],
      ["AT72", 21 ]
    ]
  }
}
```

---

>@n8rzz:
>@erikquinn likely due to this line in the `AirlineModel`: `this.flightNumberGeneration.alpha = _has(data, 'callsign.alpha');`

Originally reported in zlsa/atc#748.

**Comment by n8rzz** [comment]
this will be fixed with [n8rzz#243](https://github.com/n8rzz/atc/pull/251)
