### ISSUE TITLE
SpeechSynthesis not working on chromebook

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#50]
The voice that reads back commands given to aircraft is not working on chromebooks. It's unclear whether or not perhaps the speech synthesis api (external) is not compatible with chrome on chromebooks. It is known to work on Chrome and Safari on full desktop machines.

Originally reported in zlsa/atc#758.

**Comment by panther2** [comment]
20 months later I have tested again today on my Chromebooks - running latest stable CrOS - and now it works!
