### ISSUE TITLE
Always draw historical position dots

### ISSUE THREAD

**Issue by n8rzz** [openscope/openscope#508]
There used to be several dots behind an aircraft that represented previous position.  Those dots are now gone in `develop`

**Comment by n8rzz** [comment]
previous position tracks are there, I was thinking they'd be there for aircraft outside controlled airspace.  it's never worked that way.

closing as invalid

**Comment by erikquinn** [comment]
Never realized that, actually. But we do want history dots regardless of where the aircraft is or what it is doing. Reopening as enhancement.
