### ISSUE TITLE
Erroneous warning of excessive localizer intercept angle

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#51]
Reports have been made that the warning for excessive localizer intercept angle is still being given inappropriately under certain conditions. More specifically, the cited example was at EDDH, via route `DH655..DH656..HOS`, and cleared for ILS runway 23 approach. Also mentioned was SAEZ.

Something is in fact broken here, because the course from `DH655` to `DH656` is directly in line with the localizer, and should not generate such a warning; yet, it does.

Originally reported in zlsa/atc#759.

**Comment by cake-pie** [comment]
Although the message about excessive intercept angle still exists in the code [here](https://github.com/openscope/openscope/blob/b80b03a9c9a780a4b6a22cbbec4ba11929773975/src/assets/scripts/client/game/ScoreController.js#L233-L238), it is not called anywhere. No detection mechanism for localizer intercept angle currently exists, having been removed no later than commit b323278 in #193 from when calls to `warnInterceptAngle()` were deleted from `AircraftInstanceModel.js` without any replacement.

**Comment by n8rzz** [comment]
Thank you for digging into this and thank you for the update!

**Comment by erikquinn** [comment]
Woof. It shouldn't just _not_ be doing it at all anymore either... 😄 

Created #2064 for that. :)
