### ISSUE TITLE
Remove mapping of -/+/= to zoom in/out/reset

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#510]
Use of `-`, `+` and `=` are used both for speed control as well as zooming the canvas. The latter is not needed, since we can scroll to achieve the desired zoom level.

Remove logic that uses these key events to trigger zooming.

**Comment by MisterHighQ** [comment]
Just requires removal of lines 353 - 365 in src/assets/scripts/client/InputController.js

**Comment by BetterWarrior** [comment]
So it was your stupid suggestion that caused the pain of me, removing +- as zoom keys which many people in the world use or at least used as backup created the issue where me among others who use a laptop for whatever reason can't zoom via mouse wheel.
