### ISSUE TITLE
Hide strip bay at initial load

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#514]
The strip bay is open on initial load of the sim. Since they are generally secondary to the task at hand (plus considering the increased width of the new bay), I propose they are hidden away at first, and a line is added in the tutorial to explain how to show/hide the bay.

![image](https://user-images.githubusercontent.com/5103735/27047403-0242de4c-4f76-11e7-83d4-deb721ef14d9.png)
![image](https://user-images.githubusercontent.com/5103735/27047502-5b71e0bc-4f76-11e7-9753-9c8100bb1233.png)

---

Related: #515.

**Comment by n8rzz** [comment]
Hiding this on load makes me a little uneasy with respect to new users.  But, I suppose, adding it to the tutorial would make it a little more obvious.

**Comment by n8rzz** [comment]
rolled into #483, closing
