### ISSUE TITLE
Reverse arrow on strip bay handle when not hidden

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#515]
When the strip bay is shown, the direction of the arrow should be made to point the other way, indicating the direction it will go when clicked.

Current:

![image](https://user-images.githubusercontent.com/5103735/27047403-0242de4c-4f76-11e7-83d4-deb721ef14d9.png)
![image](https://user-images.githubusercontent.com/5103735/27047502-5b71e0bc-4f76-11e7-9753-9c8100bb1233.png)

---

Related: openscope/openscope#514

**Comment by n8rzz** [comment]
rolled into openscope/openscope#483, closing
