### ISSUE TITLE
MCP altitude being set to non-integer

### ISSUE THREAD

**Issue by n8rzz** [openscope/openscope#521]
occurred after `l 08r` on `feature/206` airport `LROP`

<img width="290" alt="screen shot 2017-06-14 at 4 43 02 pm" src="https://user-images.githubusercontent.com/3325985/27155882-4cc656aa-5120-11e7-84ae-0d124cb19b1d.png">

**Comment by n8rzz** [comment]
will be rolled in with #483

**Comment by erikquinn** [comment]
Reopening. The core issue is that the MCP altitude should not be getting set to any thing more precise than 100ft increments.
