### ISSUE TITLE
Departing aircraft intercepts other runway's initial fix for SIDs

### ISSUE THREAD

**Issue by PFunk49** [openscope/openscope#530]
Just now starting up at Copenhagen I have aircraft departing on runways 4 left and right. Aircraft taking off from 4R on a SIMEG departure immediately intercepts CH367 instead of CH360 ie. its intercepting the initial point it would for if it was departing 4L. This makes parallel departures annoyingly high maintenance. The absence of a fly runway heading command further compounds it.

-edited ODIN to SIMEG.

**Comment by erikquinn** [comment]
Will have to look at the airport file, because it may well be that.

In the meantime, you can do `fph cto` or `fh 040 cto` to prevent the result.

**Comment by Fechulo** [comment]
The procedures in the airport file follow the official charts. The SIMEG procedure (for both 04L and 04R) doesn't include the waypoint CH360 in the AIP, so it doesn't in-game either. Parallel departures are not allowed in EKCH, so the procedures aren't designed to support it. In real life, assuming the winds are the same as in the game, the runway configuration would be 04R for departures and 04L/12 for arrivals.

**Comment by PFunk49** [comment]
Well the departure then involves a weird left turn off runway heading to align with 4l. While parallel departures may not be normal it seems odd that if you had a landing aircraft the departure would have the airplane taking off into the track a go around would likely be into.

**Comment by Fechulo** [comment]
According to the charts, the go around procedure for 04L is a left turn to heading 347 away from all the departures. If I remember correctly, that initial waypoint is only used for departures to the northwest.

**Comment by PFunk49** [comment]
Then that makes sense.

**Comment by erikquinn** [comment]
closing as non-defect.
