### ISSUE TITLE
Tokyo Haneda (RJTT) Has No Inbound Traffic

### ISSUE THREAD

**Issue by doofus** [openscope/openscope#538]
There is no inbound traffic for RJTT.  Only departures.

**Comment by n8rzz** [comment]
A lot of our airports are currently being updating.  There were some changes to the api a few months ago, and now departures/arrivals are structured a little differently.  Some airports were converted rather hastily.  We are now going through them and cleaning up as much as possible.

`RJTT` has yet to be tackled but it is on the list!

**Comment by doofus** [comment]
OK, that answers a lot of questions.  I hope to lend a hand when I get bit more time.

**Comment by n8rzz** [comment]
Sounds good, we're always looking for help.  

If you do decide to lend a hand, please review the documentation located here: https://github.com/openscope/openscope/tree/develop/documentation

Also feel free to join us on [slack](http://slack.openscope.co)
