### ISSUE TITLE
EDDH: Fix `ABMAL` arrival spawn pattern conflicts

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#55]
Aircraft on the ABMAL arrival will occasionally have conflicts and losses of separation. Efforts should be made to amend the spawn patterns in the aircraft file, such that they do not create conflicts that set the user up to lose points without a chance to prevent it.

Related to zlsa/atc#774.

**Comment by erikquinn** [comment]
This is probably possible with all EDDH arrivals, due to the speed which is set at 350KIAS. Some aircraft probably are not quite able to comply, and that is what causes the degredation of separation over time.

**Comment by Fechulo** [comment]
All issues with EDDH were fixed with [refactor/829](https://github.com/openscope/openscope/pull/830)
