### ISSUE TITLE
Aircraft do not always reach target altitudes

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#56]
Aircraft will sometimes stop their climbs/descents near, but not AT the targeted altitude.

This can cause issues like that observed in #773, where attempts to compare that altitude against other values can lead to an incorrect conclusion by the simulator, and the wrong things are applied to the situation. We don't want that!

One option would be to add a helper function that could compare values with an acceptable level of error to filter out these false negatives, but that hardly seems necessary. The way the current physics work, there's no reason the aircraft should be stopping at an altitude of 10000.00011920929 when they are targeting 10000.

Originally reported in zlsa/atc#777.

**Comment by Dabea** [comment]
This issue should have been resolved in  n8rzz/feature/ATC-181.  I also unable to create the error in the current Develop branch of OpenScope.

Also #244 in i had noted 
	"resolves both n8rzz/atc#254 and zlsa/atc#777 by removing -+.02 variance"

I believe we can close this bug.

**Comment by erikquinn** [comment]
I concur. Closing.

**Comment by n8rzz** [comment]
![do-you-concur](https://cloud.githubusercontent.com/assets/3325985/23106346/a7e3f804-f6b1-11e6-9533-7ea1ce48d27c.jpg)
