### ISSUE TITLE
EIDW: Aircraft reach end of route before leaving airspace

### ISSUE THREAD

**Issue by scott-j-smith** [openscope/openscope#566]
Per @n8rzz Nate's request, breaking up the issues from case #554 and this one is for Issue 3 from that case as follows:

Departing aircraft penalized for leaving the control area without clearance (-25 point penalty). Is this a new feature that controllers need to be aware of? Are the changes documented somewhere? I'm not seeing any new commands in the Wiki page, just one deleted (Fix). I assumed that once the flight was issued the "CAF" command, and then the "CVS" en route it would proceed on its merry way. Example: Flight N749NX (after running a few minutes past the point of the screen shot 1 below)

**Response from @Fechulo :** 
I believe this is an issue that's being worked on? @n8rzz could confirm. The problem is that some of the SID's end inside the airspace. When the aircraft reach the final fix and continue on their heading, so when they leave the airspace, they aren't flying to a fix, causing a penalty.

**Response from @n8rzz :** 
To point #3, its actually the other way around. Some procedures end outside of controlled airspace and were incurring a penalty. This case was fixed in this latest release. The way @Fechulo describes it, though, could also be a problem.  :thinking:
If so, that deserves it's own issue.

**New Update from me today :** 
This does seem to be airport related.  I was playing Boston Logan (another non-WIP airport) and did not have the same issue.  Departures were given the "caf" then "w 22r" commands, followed by "to", then "cvs" and nothing else.  They continued on their merry way and I was given the 10 point credit upon crossing out of the zone.
**Edit:**  I spoke too soon!  The 6th departure flight that left the airspace threw up the warning.  I think it was flight NKS3758 on the SSOX4 SID?  See 2nd screen shot below

![image](https://user-images.githubusercontent.com/22403776/28235592-1eabb270-68df-11e7-8808-9168f511d9aa.png)

![image](https://user-images.githubusercontent.com/22403776/28235839-8c035b48-68e4-11e7-9fb2-c19a508dd3ae.png)

**Comment by erikquinn** [comment]
The routes in the spawn patterns should be extended so they at least clear the airspace boundary before they run out of waypoints. So after the SIDs, we should be hooking into airways, or going direct to some more common fixes, etc.

**Comment by erikquinn** [comment]
@matt5611 in #575:
>As title suggests, departing aircraft leaving controlled airspace without clearance.
>
>E.G. departing via OLONO on published SID Ray 28... issued via CAF & CVS commands. No further instructions given after Taxi and Take-off... When aircraft arrives at OLONO the player is penalised for incorrectly leaving controlled airspace.
>
>Note: this is NOT limited only to OLONO but the vast majority of outbound points.
>
>Departing aircraft to the north, will exit, and then proceed to turn to heading ~160 and re-enter... the subsequent re-exit causing penalisation to player.
>
>Aircraft arriving from the North East will KOGAX... after which some seem to have an issue with the left turn to the next point (fly-over) and will exit controlled airspace on their STAR, re-enter no more than 10 seconds later as the turn back to the SW for the next STAR tracking point.
>
>All arriving aircraft left on STAR's tracking to the waypoints near DW814 (east of aerodrome), caused as aircraft miss the fly-over waypoint or take longer than anticipated to turn, interrupting their tracking to the subsequent waypoints, causes exit of controlled airspace, again the player is penalised.
>
>In normal playing, it is not unusual to receive -1000 points in 15 minutes purely by departing aircraft on SID's, and leaving aircraft to fly STAR's (with vertical separation), purely because of aircraft leaving CTA.
