### ISSUE TITLE
Improper Landings

### ISSUE THREAD

**Issue by scott-j-smith** [openscope/openscope#568]
Per @n8rzz Nate's request, breaking up the issues from case #554 and this one is for Issue 5 from that case as follows:

Found another bug. Was playing same airport again today, and sometimes I see a flight seem to land way past the runway, and sometimes well before it, but no errors posted in the game. Example: BCY289 (screen shot below). In the pic it is landing just to the left of the the "10" runway number label near the center of the screen, which is well past the end of RWY 28. Could be a graphic display / refresh issue? Is this a known issue? I'm using Google Chrome with the latest updates.

**Response from @n8rzz :** 
well that is not as designed. :frowning_face:

![image](https://user-images.githubusercontent.com/22403776/28235698-0b212666-68e1-11e7-8352-a07c951252d0.png)

**Comment by erikquinn** [comment]
This is really just a symptom of some big problems we have with course tracking, which will be addressed with #38. Added this as a note in there. 

Closing as duplicate.
