### ISSUE TITLE
aircraftInstanceModel.fms has a circular dependency with aircraftInstanceModel.fms.my_aircraft.fms

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#57]
_From @n8rzz on October 5, 2016 3:58_

`aircraftInstanceModel.fms` has a property `my_aircraft` which is a reference to the parent aircraft class.  By including this entire class, this also brings with it the `fms` property and it's `my_aircraft` property and so on and so on.

This is a circular dependency that _will_ adversely effect performance and could potentially cause the browser to crash.

_Copied from original issue: n8rzz/atc#16_

**Comment by erikquinn** [comment]
_From @n8rzz on November 11, 2016 13:15_

This task will very likely identify places for refactor in order to remove the circular dependency. In that event, create new issues when those needs have been identified.  If the circular dependency can be easily resolved, do so under this ticket.

**Comment by erikquinn** [comment]
_From @n8rzz on January 15, 2017 4:47_

will likely be invalidated by n8rzz/atc#256

**Comment by n8rzz** [comment]
this is fixed as part of openscope/openscope#139

**Comment by erikquinn** [comment]
Completed under #139.
