### ISSUE TITLE
Aircraft not proceeding direct new fix after full reroute

### ISSUE THREAD

**Issue by scott-j-smith** [openscope/openscope#570]
Sometimes when I give a reroute command with a valid route, the planes to not immediately turn to the first fix in the route.  I have to give the direct (dct) command to make the start the route.  I've seen this 100% of the time in KBOS (command "rr noley..wyane..vocus..zumol").  I also see it playing VHHH (command "rr tamar..atena..hamok..sampu..plove..river..vh512..vh513), however only for arrivals on the STAR that comes in from MANGO to COLEY -- it works fine for arrivals on the other STARs.  I realize VHHH is still in WIP under v5.2.1 so I don't know if that matters or not...

**Comment by erikquinn** [comment]
If the aircraft is not on an `LNAV` heading mode, this would happen. Perhaps they are on headings at the time this is observed? If so, it would be performing as expected. Else could you confirm that it is in the process of going to a fix when the reroute is given, and they still fail to turn to the first specified point?

**Comment by scott-j-smith** [comment]
Hi Erik, 

I am not sure what you are saying, or how to verify if they are in LNAV mode or on a fix or not to be honest. 

If it helps, I don't issue any commands to them prior to the reroute command in any of the examples I mention.  I let them follow the STAR until they get to a point where I want to reroute them, then issue the RR command.  So I guess if they are not in the right mode, it must be a problem with the airport config files?

Cheers,
Scott

**Comment by erikquinn** [comment]
It's just a note for future me :wink: Nate or I will have a look sometime and try to see what's going on.

**Comment by erikquinn** [comment]
@scott-j-smith Using KBOS on [https://openscope-dev.herokuapp.com/](https://openscope-dev.herokuapp.com/), I am not seeing anything wrong with using the command `rr noley..wyane..vocus..zumol`; they are all turning direct to `NOLEY` for me.

Could you provide some more details about how we can reproduce the issue so we can take a closer look?
