### ISSUE TITLE
Rename some FMS methods related to holding

### ISSUE THREAD

**Issue by scott-j-smith** [openscope/openscope#571]
Hi again,

Still playing KBOS, and that flight I mentioned in case #569 actually came into control below FL100 in time to turn it.  I issued the reroute command ("rr noley..wyane..vocus..zumol) and then the hold command until it could descend low enough to continue the approach ("hold noley d 40").   By the time it was low enough to continue, other flights were getting too close so I tried to divert this one by getting it to head northwest ("fh 320").   But it wouldn't break out of the HOLD!  I tried then getting it to continue on the assigned route ("pd noley" then "pd wyane"), but that didn't work either.

I give up.  :-)

Scott

![image](https://user-images.githubusercontent.com/22403776/28235895-34dc177c-68e6-11e7-9159-1ab8be04c946.png)

**Comment by erikquinn** [comment]
Note: Looks like they ignore heading commands, but they pay attention to being told to `pd` a fix.

**Comment by scott-j-smith** [comment]
Just to clarify, the pd command didn't work for me either (see initial report).  nothing worked.  It just kept holding.

**Comment by erikquinn** [comment]
The described bug is no longer observed on develop.

Will be hijacking this issue for some very minor renaming refactors I found necessary while looking into the issue before realizing it wasn't broken anymore.
