### ISSUE TITLE
Splash screen shows old GitHub repository

### ISSUE THREAD

**Issue by sam-irl** [openscope/openscope#583]
Not a pressing issue, as the old repo has a link to the new one. Just a thing to fix if anyone has the time.

**Comment by indianbhaji** [comment]
Someone created a new splash screen, forgot who but it could be incorporated into that

**Comment by n8rzz** [comment]
Good thought, however, this will be invalidated by #294

**Comment by indianbhaji** [comment]
@n8rzz that is the exact splash screen I was referring to haha
