### ISSUE TITLE
EGKK: All SID/STARs have multiple suffixes

### ISSUE THREAD

**Issue by sam-irl** [openscope/openscope#588]
Looking at the console, I believe that multiple routes have been defined.
![image](https://user-images.githubusercontent.com/29643177/28460900-d0b03906-6dd9-11e7-8d1c-dfc6a8fc1480.png)

**Comment by indianbhaji** [comment]
No problem here, it will be sorted as all airports will be reviewed so they meet the new standards

**Comment by n8rzz** [comment]
We are also supporting suffixes in a completely different way now, which differs from how suffixes were implemented when this route was originally written.
