### ISSUE TITLE
Simplify creation of arrival aircraft

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#59]
_From @n8rzz on October 10, 2016 0:25_

current workflow could be simplified.  the current process is:

``` javascript
ArrivalBase.preSpawn()

AircraftController.aircraft_new(options)
- airlineModel = window.airlineController.airline_get(options.airline);

AirlineModel.generateAircraft(options);

AirlineModel._generateAircraft(options);
- options.callsign = window.aircraftController.aircraft_callsign_new(options.airline);
- options.icao = this.chooseAircraft(options.fleet);
- aircraftModel = window.aircraftController.aircraft_model_get(options.icao.toLowerCase());

AircraftModel.generateAircraft(options);

AircraftModel._generateAircraft(options);
- options.model = this;
- const aircraft = new AircraftInstanceModel(options);
- prop.aircraft.list.push(aircraft);
```

There is a lot of back and forth here that could be simplified.  This should all be accomplished from within the `AircraftController.aircraft_new()` method.  Making all the various calls from within that single class instead of passing an options object around to 4 different class methods.

_Copied from original issue: n8rzz/atc#27_

**Comment by erikquinn** [comment]
_From @n8rzz on January 13, 2017 4:29_

n8rzz/atc#243

**Comment by n8rzz** [comment]
finished here: https://github.com/n8rzz/atc/issues/243
