### ISSUE TITLE
Make data block STARs style with timeshare

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#604]
Improve upon the current data blocks by adding what they call the "timeshare". The second line of the data block rotates between displaying two sets of information: the altitude and speed, and then the scratchpad and aircraft type.

The scratchpad only supports three alphanumeric characters, and should be defaulted to showing the aircraft destination. If departures could show their first fix, that would be handy, but more thought would be needed on how to achieve this given the various situations aircraft can be in, as we continue our quest to minimize how often we consider any given airplane an `arrival` or `departure`, since those terms are relative.

**Comment by n8rzz** [comment]
http://vstars.metacraft.com/Assets/Files/vSTARS%20Controller%27s%20Guide.pdf
