### ISSUE TITLE
Remove polygons at/below sea level from terrain files

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#607]
Some terrain files contain polygons at elevation 0 (sea level). These are not necessary, and create clutter that makes it seem as if terrain is present, when it truly is not. Terrain files for all active airport must be amended, and the resulting qGIS files also updated in the `airport-modeling` repository.

**Comment by Marcel510** [comment]
I've checked the terrain files for elevation 0: No occurrences, can be closed I think.
