### ISSUE TITLE
KSEA: Minor update

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#608]
- [ ] add all FAFs and fixes along localizers

**Comment by PFunk49** [comment]
Any idea how I can actually instruct arriving aircraft to proceed direct to a fix on the final approach course? Every time I try it it tells me its invalid.

**Comment by Fechulo** [comment]
@PFunk49 I encourage you to join our [slack channel](http://slack.openscope.co/), where we can communicate easily!

**Comment by Fechulo** [comment]
Addressed by #908 
Closing
