### ISSUE TITLE
Refine Sprint Process Checklists

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#614]
Follow-up to openscope/openscope#418 (feature #511). Some things have gone slightly awry with the checklist that weren't expected. Will need a closer look to get everything going properly.

- [x] Non-continuous numbering
- [x] `Deploy v1.2.3` sha on `master` must be merged back into `develop` at some point (null diff).
    - At `ARCH - Prepare CHANGELOG`? At end of release procedure?
- [x] Fix invalid tag pushing command to `git push origin tagName`
- [x] allow expansion of branch naming conventions

![img_20170810_125225](https://user-images.githubusercontent.com/5103735/29182340-83ea239a-7dcc-11e7-986c-fdf02f197b04.jpg)

**Comment by n8rzz** [comment]
>Deploy v1.2.3 sha on master must be merged back into develop at some point (null diff).

@erikquinn what do you mean here?  Are you talking about the tag that is created?  If so, tags are branch agnostic and cannot be _merged in_ to any other branch.  They are effectively a snapshot of the repo at a particular point in time.

**Comment by erikquinn** [comment]
No, the merge commit when we merge release into master. That needs to make its way into develop eventually in order for them to be "even".

**Comment by n8rzz** [comment]
Yep, those two merges should happen at the same time; one to master and one to develop.

**Comment by erikquinn** [comment]
@n8rzz Exactly. Used to be that was how it went, but somehow amongst some changes, it got messed up a little. Took the time to draw out exactly what we should be doing on a extra long break today :smiley:
