### ISSUE TITLE
Update instances of `prop` to use `this`

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#62]
_From @n8rzz on October 21, 2016 3:24_

Update direct usages of `prop` inside classes.  Instead of a class setting class properties to `prop` use `this`.

However, for now, we must maintain the references to the original `prop` values so we don't break everything.

the current workaround is:
```javascript
const aircraft = {};

export default class Aircraft {
    constructor() {
        this.aircraft = aircraft;
        prop.aircraft = aircraft;
    }
```

This way we can maintain the original props, but still use class properties in the usual way.

---

There are also references to `prop` values from other classes sprinkled throughout, those are not being refactored [yet] with this issue.

_Copied from original issue: n8rzz/atc#43_

**Comment by erikquinn** [comment]
_From @n8rzz on November 7, 2016 23:11_

work started on branch `feature/ATC-43`

**Comment by erikquinn** [comment]
_From @n8rzz on November 19, 2016 22:19_

`gameController` updated with n8rzz/atc#96

**Comment by n8rzz** [comment]
this will be handled incrementally as part of other tasks.  

closing
