### ISSUE TITLE
Speed on strips does not update

### ISSUE THREAD

**Issue by Fechulo** [openscope/openscope#622]
Browser: Chrome
Airport: All

#### Issue Description
When the speed command is given to an aircraft, the target speed on the aircraft's strip does not change

#### Steps to reproduce
- Give any aircraft a speed instruction
- Observe unchanged aircraft strip

**Comment by erikquinn** [comment]
Working as designed. #14 will be the new way that sort of stuff would be recorded (if at all).

Closing.
