### ISSUE TITLE
CAF doesn't register in scoring

### ISSUE THREAD

**Issue by Van-atVT** [openscope/openscope#626]
in EIDW, An aircraft was given: caf to cvs, when they reach point of radar exit it gives a deduction, is there some other command I'm supposed to use for them to cleanly transfer out of coverage?

occurs on the following non WIP airports:
EIDW
MDSD

![screenshot 4](https://user-images.githubusercontent.com/30939758/29237186-ff030892-7ee6-11e7-8e10-342eb562a09d.png)
![screenshot 2](https://user-images.githubusercontent.com/30939758/29237187-ff037b56-7ee6-11e7-8224-80e96811f8e7.png)
![screenshot 3](https://user-images.githubusercontent.com/30939758/29237188-ff06f768-7ee6-11e7-805a-4a6481ad290f.png)

**Comment by Fechulo** [comment]
@Van-atVT Nope, you're doing everything right. It's a known issue we're working on.

**Comment by Van-atVT** [comment]
I read a little into the issues and stuff and found its the same as #566 and is on the docket for 8/31. Thanks! @Fechulo
