### ISSUE TITLE
Update UI theme colors to match new default theme

### ISSUE THREAD

**Issue by n8rzz** [openscope/openscope#630]
With openscope/openscope#15 almost merged, there are some other modules that need their colors updated.

<img width="956" alt="screen shot 2017-08-15 at 6 38 23 am" src="https://user-images.githubusercontent.com/3325985/29314770-1cf85258-8185-11e7-89f7-c6179e022c26.png">

specifically the borders on the modals and the active state for the control buttons.  

_Work on this should not start until openscope/openscope#481 has been completed and merged_

**Comment by erikquinn** [comment]
#481 resolved, unblocking.
