### ISSUE TITLE
Abstract inline fix object out of ArrivalBase

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#64]
_From @n8rzz on November 1, 2016 20:36_

These lines are problematic:
```javascript
for (let i = 0; i < options.fixes.length; i++) {
    this.fixes.push({ fix: options.fixes[i] });
}
```

`this.fixes` has a very specific use and having these inline objects is somewhat confusing.  This needs improvement.

_Copied from original issue: n8rzz/atc#56_

**Comment by erikquinn** [comment]
_From @n8rzz on January 13, 2017 4:28_

n8rzz/atc#243

**Comment by n8rzz** [comment]
finished here: https://github.com/n8rzz/atc/issues/243
