### ISSUE TITLE
Establish guidelines for (and adjust) airports' difficulty rating

### ISSUE THREAD

**Issue by Fechulo** [openscope/openscope#655]
Currently the airport difficulty is decided entirely by the airport creator and there are no guidelines or rules to standardize these levels. It just feels like the difficulty means nothing and is not consistent across all airports. 

I'm thinking something like giving each level a range of aircraft per hour, so for example, if an airport has between 3-10acph it should be categorized as `'beginner'`. If the airport has some challenging characteristics then the level could be reviewed. I don't know, just an idea. `¯\_(ツ)_/¯`

Other thoughts and ideas are welcome!

**Comment by erikquinn** [comment]
Makes sense to me... So really like we're rating the _volume_ of traffic rather than the _difficulty_ of the position. I like it!

**Comment by Fechulo** [comment]
So I made a simple spreadsheet with the current traffic levels of all non-wip airports and categorized them as `beginner`/`easy`/`medium`/`hard` depending on the traffic level:
![traffic levels](https://user-images.githubusercontent.com/13125311/33234133-0da78d7a-d219-11e7-9312-75f3bf720c6f.PNG)
Feel free to take a look at the spreadsheet [here](https://docs.google.com/spreadsheets/d/13iWEDFARNO3MdZ6SBqib38ZDijFE-h37RrCjI_Tgc5I/edit?usp=sharing). Thoughts?
