### ISSUE TITLE
Slight misalignment in airport selection dialog

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#659]
Browser: All
Airport: N/A

#### Issue Description
Something in openscope/openscope#628 (feature #481) seems to have accidentally undone some minor adjustments to some `airport-list` classes' css, and now there is some slight misalignment as a result. Will need to re-implement those values in the new less files.
![image](https://user-images.githubusercontent.com/5103735/29799952-581ff678-8c35-11e7-8699-d4e6ee992bd2.png)

**Comment by n8rzz** [comment]
Interesting. Probably just an extra padding for that active class.

**Comment by erikquinn** [comment]
Nah, that's all fine like that, it's the goofy little diamond marker that's misaligned.

**Comment by erikquinn** [comment]
Resolved by #673. Closing.
