### ISSUE TITLE
Decouple data loads from creation of instances

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#66]
_From @n8rzz on November 10, 2016 2:34_

All of the data we need is available once we know the current airport.  Why not load _all_ the airlines and _all_ the aircraft types into collections that can then be referenced when a new aircraft spawns.

load airport -> load airlines -> load aircraft for airlines (airline fleets) -> begin spawning departures/arrivals

_Copied from original issue: n8rzz/atc#78_

**Comment by erikquinn** [comment]
_From @n8rzz on November 11, 2016 5:6_

![atc init](https://cloud.githubusercontent.com/assets/3325985/20204972/49031ae2-a79a-11e6-8dbe-0c68c70d9ba8.jpg)

**Comment by felixscheffer** [comment]
What's the state of this ticket?

@n8rzz  @erikquinn

**Comment by n8rzz** [comment]
Hmm, I feel like we do this now minus the aircraft pool part. This issue may have been created when we only loaded the necessary airlines and aircraft for a particular airport.

**Comment by erikquinn** [comment]
Yeah it basically is doing this now, I think this can be closed. Feel free to reopen if not.
