### ISSUE TITLE
Flight strips out of proportion

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#664]
Browser: Chrome
Airport: All

#### Issue Description
Flight strips have become out of proportion, due to their being too tall. Regardless of the strips contents, it must maintain its dimensions. When the route overflows, it will need to be truncated; this is a separate issue (#633). In the meantime, overflow beyond the dimensions  of any field may simply be hidden.
![image](https://user-images.githubusercontent.com/5103735/29850026-a20f1480-8cf8-11e7-9472-cd5ba8263c1e.png)

---

Related: #633.

**Comment by n8rzz** [comment]
somewhere along the lines the order of `js-stripView-flightRules` and `js-stripView-cid` was reversed.  the flightRules element is floated to the right and actually needs to come before the CID element in the DOM.  As it is now, the flightRules element is last, thus, on its own line even though it's floated to the right.

**Comment by erikquinn** [comment]
Resolved by #665. Closing.
