### ISSUE TITLE
How do I test my airport in localhost with XAMPP?

### ISSUE THREAD

**Issue by willfrd** [openscope/openscope#671]
Browser: All

Airport: None

Approximate play time before issue: None

#### Issue Description
I am developing GCRR V2 (updated SID's + added coastline + airport outline +approach lines), I have remaining the STAR's and to do it I need to use XAMPP with the newest version of openscope (v5.3.0) due to the changes in the STAR structure, but I am not able to find the file I need to execute with XAMPP in order to test my airport in the newest vesion, before it used to be an index.html in the main folder, everything is so changed and now I have falled far far behind :-| .  How do you do I do it? Thanks :)

Screenshot of what I have until now:
![gcrr v2 beta](https://user-images.githubusercontent.com/20045335/29935303-2aca8ff6-8e76-11e7-8e59-d4d9bc2f66ff.png)

#### Steps to reproduce
¿?

**Comment by indianbhaji** [comment]
@willfrd Hi, join our slack at http://slack.openscope.co/ and we can help you on the spot

**Comment by willfrd** [comment]
Closing, thanks guys.
