### ISSUE TITLE
Add test that ensures all airport files in load list are valid json

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#677]
It would be great to have a test that tries to load all the airport JSONs dictated by the load list, and then fail if any of them are not valid JSON data.

**Comment by n8rzz** [comment]
@erikquinn this would be pretty easy to do with some node scripts.  how do you envision this to work?  Run after our tests and `throw` when it pukes?

**Comment by erikquinn** [comment]
I thought it would be run along with `npm run test` and fail throwing the name of the offending file. That way a PR that turns on an airport that has a syntax error shows a failing test in CI, and brings their attention to it.
