### ISSUE TITLE
Remove wind vane from CanvasController

### ISSUE THREAD

**Issue by n8rzz** [openscope/openscope#678]
~~Currently the wind vane, and supporting logic, lives within the `CanvasController`.  This should be abstracted to a standalone view component (like the `StripView`, etc) built with html/css or simple svg.~~

Remove wind vane concerns from `CanvasController`

**Comment by erikquinn** [comment]
We may even consider changing the wind vane itself, to make the wind more clear. There is probably frequent confusion such as `well the stick is pointing to about 320. does that mean the wind is blowing toward 320? Or from it?` Honestly, I don't remember which one it is with how it is implemented, which is probably a sign that we could be doing it differently.

Even a standard text wind readout may be acceptable? Like a portion of the METAR... :thinking: 
`KIAD 050052Z 17008KT 10SM CLR 23/19 A2987 RMK AO2 SLP111 T02330194`
`WIND 17008KT`

**Comment by n8rzz** [comment]
Perhaps not visually elegant but it's clear

**Comment by willfrd** [comment]
Maybe creating a more realistic wind dial?
I can't speak for other countries but in Spain atc use a wind dial that is like this:
![wind dial 1](https://user-images.githubusercontent.com/20045335/30057012-00559d14-922d-11e7-957c-e2e4717ceeab.jpg)
(Sorry for the quality of the photo but there arne't that many photos arround)
It would be more realistic... but I don't really know how which number indicated the wind, direction, variability...

**Comment by n8rzz** [comment]
With the new `AirportInfoView`, the wind vane is now duplicative and should be removed
