### ISSUE TITLE
Terrain is hard to see with new scope theme

### ISSUE THREAD

**Issue by sam-irl** [openscope/openscope#688]
Browser: All

Airport: All

Approximate play time before issue: N/A

#### Issue Description
_please include any console errors and/or screenshots_ 
The height of the terrain is hard to see with the new colour theme.

#### Steps to reproduce
- Select an airport with terrain

**Comment by n8rzz** [comment]
https://codepen.io/n8rzz/pen/dVgVRW?editors=1100
