### ISSUE TITLE
Prevent hotkeys from repeating command on successive presses

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#689]
When using hotkeys to aid in command entry, multiple presses of the hotkey will yield multiple entries:
```
Pressing [right arrow] [right arrow] 2 5 0:
AAL123 t r t r 250
```

It would be nice if we could recognize that a command is already entered, and avoid continuing to append to the command, since the above command will return a red response, due to the aircraft not understanding the first of the two commands (`t r ` is not understood, and `t r 250` is accepted).

**Comment by cake-pie** [comment]
Duplicate #1724
