### ISSUE TITLE
Departures should climb at optimal speeds. Violating Vne now.

### ISSUE THREAD

**Issue by chksix** [openscope/openscope#693]
Browser: Firefox/Chrome

Airport: All?

Approximate play time before issue:

#### Issue Description
Aircraft are accelerating to unrealistic speeds at low altitudes when leveling off on a SID.
Normal climb speed should be 250 KIAS below FL100 then 280-300 KIAS above FL100.
Currently I see planes speeding up to 620 KTAS while flying at FL110. Wings would fall off.

#### Steps to reproduce
- Watch any departure when they have left your control without assigned airspeed.

**Comment by erikquinn** [comment]
Hi @chksix!

You are right, the climb characteristics are a bit wonky. When they do not have any speed restriction from ATC or their SID, they will just accelerate to Vne (whatever is defined as `speed.maximum` in the aircraft's type definition file). And this acceleration does not take into account vertical speed either... meaning aircraft will speed up just as quickly regardless of whether they are descending, level, or climbing. Obviously that's not how it is in reality :wink:

So there is room to improve, though I would say that they are not actually exceeding Vne. Keep in mind also that the data block shows groundspeed, which, given a large tailwind and 10k or higher altitude, will be significantly (50+ kts) faster than the indicated airspeed, which is allowed to go up to Vne.

We definitely have room for improvement in this area though. :+1:

**Comment by chksix** [comment]
Hi erik!
Cheers for your reply! I hope you have time to continue work on this excellent sim :)

/Pierre

**Comment by erikquinn** [comment]
Created #714. Closing.
