### ISSUE TITLE
SpawnPatterns at KSDF must be extended outside airspace

### ISSUE THREAD

**Issue by chksix** [openscope/openscope#699]
Browser:Firefox/Chrome

Airport:KSDF

Approximate play time before issue:0

#### Issue Description
SID from KSDF should have a top altitude of 5000 ft set according to the RL charts at Airnav.com
CRRGO departure throws me an error if the departure crosses the fix below FL100.

#### Steps to reproduce
- Assign a departure to FL50 and receive penalty when leaving unauthorized after CRRGO

**Comment by Fechulo** [comment]
@chksix Thank you for reporting! The error you're seeing actually has nothing to do with the altitude of the SID. Basically, it's because aircraft on the CRRGO departure leave the airspace without a route (it's my fault 😬)
