### ISSUE TITLE
Command line overlaps with toggle buttons

### ISSUE THREAD

**Issue by Fechulo** [openscope/openscope#704]
Browser: All

Airport: n/a

Approximate play time before issue: n/a

#### Issue Description
The command line overlaps with some of the toggle buttons. 

![command line](https://user-images.githubusercontent.com/13125311/30520424-c652668e-9ba4-11e7-86cd-74d5d8d0564a.gif)

#### Steps to reproduce
- Hold down any key on the command line until the text overlaps with the toggle buttons

**Comment by n8rzz** [comment]
whoops :man_facepalming:
