### ISSUE TITLE
Ensure "last airport" exists before attempting to load it

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#709]
During initialization of the app, check local storage for `localstorage[STORAGE_KEY.ATC_LAST_AIRPORT]` (the one we will subsequently attempt to load). If it is _not present in the load list_, that means there will be no airport file to load, and the app will never make it through the initialization process. If this is the case, reset the local storage (either the last airport value to the default airport), or all of the values... whatever it takes to be _sure_ that users that had an airport cached that no longer exists will not have the site stuck in a state where it can never complete the load without manually flushing the cache.

**Comment by n8rzz** [comment]
I thought we had a default value in there for cases when localStorage check comes back `undefined`?  It seems not, or at least seems to not be implemented correctly ☹️

**Comment by erikquinn** [comment]
we may? which would mean this would be very easy since the framework would then be in place. What we need to resolve this particular problem would be to deal with when previously available airports are removed for whatever reason. For example, EHAM is broken. Someone who last played the game a long time ago while it was available, if the site is still cached, the value is `EHAM`, and that forces the app to load the airport `EHAM`, which doesn't exist, so KA-BOOM

**Comment by n8rzz** [comment]
I see where you're going there.  So we should also check that the stored airport is also available.

**Comment by n8rzz** [comment]
The original solution implemented by this issue in #713 is incorrect and has caused #741.  I have created #744 to address this.
