### ISSUE TITLE
Centralize window methods to class constructors and create class property

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#71]
_From @n8rzz on November 15, 2016 4:25_

for a class that uses a method on another class that is attached to the `window`

- [ ] add a class property for each window class: `window.airportController` becomes `this.airportController`
- [ ] centralize window methods to topmost parent class and pass needed window methods to children on demand

---

This is the next step in moving away from window methods.  The endGame here is to instantiate all of the parent classes with everything they need, without any assistance from the `window`.

_Copied from original issue: n8rzz/atc#98_

**Comment by erikquinn** [comment]
_From @n8rzz on November 22, 2016 19:26_

this might need some more testing, performance takes a hit with `timewarp = 50` and an aircraft is selected.

**Comment by erikquinn** [comment]
_From @n8rzz on January 13, 2017 4:37_

made big strides here with n8rzz/atc#243

**Comment by n8rzz** [comment]
This is basically done now via work from several merged PRs
