### ISSUE TITLE
Remove lint errors for event handler functions that don't use the event argument

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#710]
Some event handler functions currently don't use the event itself for anything. Therefore, eslint is showing errors because the argument should either be used or not taken. But in this particular case, it is wise to capture the event just so we know it is available, even though we occasionally may not need it.

Please add individual eslint comments for each of these instances such that cause eslint to ignore them so they are considered legal.

**Comment by n8rzz** [comment]
>Please add individual eslint comments for each of these instances such that cause eslint to ignore them so they are considered legal.

Don't do that.  We can use this issue to update our `.eslint` rules to allow for this.

**Comment by erikquinn** [comment]
Here's what we came up with on slack:

`no-unused-vars: ["error", { "argsIgnorePattern": "event" }]`

See the `no-unused-vars` rule for further:
[https://eslint.org/docs/rules/no-unused-vars#argsignorepattern](https://eslint.org/docs/rules/no-unused-vars#argsignorepattern)

This should globally suppress the errors for unused arguments called `event`. :shipit:

**Comment by n8rzz** [comment]
will be covered under #744 (#746)
