### ISSUE TITLE
Game Options not being stored correctly

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#711]
Browser: Chrome
Airport: All

#### Issue Description
openscope/openscope#690 (refactor #670) appears to have caused some issues with the local storage of game options. As can currently be seen on the dev server, game options are not preserved, and are defaulted to the _first_ option in the list, rather than the default specified in `gameOptionConstants.js`.

#### Steps to reproduce
- Clear cache and load dev server
- Observe that the default values are not honored
- ~~Change some settings and refresh~~
- ~~Observe that the changes to options are not preserved~~

**Comment by n8rzz** [comment]
@erikquinn did we resolve this?  Or is this in reference to options like `terrain` or `restricted areas` visibility options?

**Comment by erikquinn** [comment]
@n8rzz no, this is new, for the options menu (not the toggle buttons). Not sure if it was #690 that did it or something after though. And I just re-checked, somehow I had the second half wrong: the settings _are_ preserved on refresh. But they are initially set to the first option in the list of values, and not the default value specified in the constants file.
