### ISSUE TITLE
Remove `version` command

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#721]
The `version` command is using `prop.version`, which is no longer maintained, so when it attempts to log the version number, it instead says:

![image](https://user-images.githubusercontent.com/5103735/30752460-588462ee-9f8a-11e7-85f6-8e435179f238.png)

The only place the version number is stored now is in `package.json`, which ends up in `layout.hbs` and `loadingView.hbs`. Somehow we should get this command printing the correct version number.

**Comment by n8rzz** [comment]
do we really need this command anymore?  I mean we print that information on build within the html:

<img width="264" alt="screen shot 2017-09-22 at 1 54 18 pm" src="https://user-images.githubusercontent.com/3325985/30759878-917b681e-9f9d-11e7-95ef-fd2d6a5f961a.png">

**Comment by erikquinn** [comment]
I give zero :hankey:s about the command myself.

**Comment by n8rzz** [comment]
Oh good, we're on the same page then.
