### ISSUE TITLE
Settings modal doesn't add active class to control icon

### ISSUE THREAD

**Issue by n8rzz** [openscope/openscope#724]
Browser: all

Airport: n/a

Approximate play time before issue: n/a

#### Issue Description
The `settings` control icon should receive an `active` css class when the modal is open.

**Comment by erikquinn** [comment]
There's also some funny business with the popup itself too. See the `UiController.closeAllDialogs()` that gets run on pressing escape. I couldn't get the settings to close while the others would. Open up airport selection, tutorial, and settings and then press escape, you'll see two go away but settings stays. I thought I remembered that the active class was maybe going to the wrong element.

**Comment by felixscheffer** [comment]
Regarding the second issue mentioned by @erikquinn:

The settings dialog does not exist in the DOM by the time `init()` is running, i.e.
`this.$optionsDialog = this.$element.find(SELECTORS.DOM_SELECTORS.OPTIONS_DIALOG);`
does not select anything.
