### ISSUE TITLE
Using STAR command to change aircraft's assigned STAR throws errors

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#73]
_From @n8rzz on November 16, 2016 4:9_

See zlsa/atc#730.

_Copied from original issue: n8rzz/atc#104_

---

Blocked by #193.

**Comment by erikquinn** [comment]
_From @n8rzz on November 16, 2016 5:27_

The star command should:
- if no STAR yet assigned, append a new Leg at the end of fms.legs, containing the specified STAR
- if the last Leg in the fms that has a type of "star", replace it with a new Leg of the specified STAR

The reroute command should:
- Wipe all waypoints out of the fms and re-generate them according to the provided route

**Comment by erikquinn** [comment]
_From @n8rzz on November 26, 2016 4:59_

when issuing `${CALLSIGN} star QUINN.BDEGA2.KSFO` to an arriving aircraft at ksfo, the route is successfully updated, however, errors are thrown due to speed being `null` in the `currentWaypoint`.

**Comment by erikquinn** [comment]
_From @n8rzz on November 26, 2016 23:2_

this might actually be as simple as updating the indicies stored in the `current` property. perhaps after a new star is inserted, we need to call a `_resetCurrentIndicies()`  method or something?  

To be honest, I'm not a fan of that property and would _love_ to remove it some day but it doesn't make sense to do that now.

**Comment by n8rzz** [comment]
possibly fixed by openscope/openscope#139

**Comment by erikquinn** [comment]
Rolled into #139.
