### ISSUE TITLE
Options dialog dropdowns have wrong background color

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#740]
If you squint really hard, you'll see that the drop-down boxes are bluey behind them rather than grayey like the rest of the dialog. Make the bluey into grayey.

![image](https://user-images.githubusercontent.com/5103735/30950237-9ac50736-a3e9-11e7-9209-e5be8b0a4d67.png)

**Comment by n8rzz** [comment]
had to expand the image to see what you're talking about there.  yeah, ick.  should just bee a css change for that.

**Comment by erikquinn** [comment]
Resolved by #749. Closing.
