### ISSUE TITLE
'No such aircraft' response is not red

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#742]
Browser: Chrome
Airport: All

#### Issue Description
`No such aircraft, say again` is not red, and it should be.

#### Steps to reproduce
- Press enter in aircraft command bar with nothing in it.

**Comment by n8rzz** [comment]
Is this a bug?  This response has not been red before (or hasn't been for a while).  Prod has this response in the default gray.

**Comment by erikquinn** [comment]
Yeah it's been like that for a while. But it really should be red.

**Comment by erikquinn** [comment]
Resolved by #748. Closing.
