### ISSUE TITLE
Logic for checking existence of a localStorage icao should be moved from index.js

### ISSUE THREAD

**Issue by n8rzz** [openscope/openscope#744]
The original solution implemented in openscope/openscope#713 is incorrect.  I should have caught it in the PR, but I missed it.  That's my fault.

The original solution had us checking for an airports existence in the `AirportController` within the `index.js` file on initial load.  This will not work.  `index.js` is the initial JS file the creates the entire app and when it runs the `AirportController` does not yet exist.  

This has now created issue #741.

The solution was correct in spirit, it just needs to happen in a different place later on in the initialization lifecycle.

**Comment by sam-irl** [comment]
Fixed in #753
