### ISSUE TITLE
couldn't read isHold of undefined

### ISSUE THREAD

**Issue by sam-irl** [openscope/openscope#752]
Browser: 61.0.3163.100 (Official Build) (64-bit)

Airport: EIDW

Approximate play time before issue: 5 minutes

#### Issue Description
_please include any console errors and/or screenshots_ 
First aircraft entered EIDW airspace, crashed. os version 5.4.1
![that isn t great](https://user-images.githubusercontent.com/29643177/31051434-be6a01c8-a62d-11e7-84b7-58f0c9a975f7.png)

#### Steps to reproduce
- play EIDW
- Wait for arrival to enter airspace

**Comment by n8rzz** [comment]
first place to check for that would be an invalid or improperly formed fix definition in the airport file.

**Comment by erikquinn** [comment]
I'm unable to reproduce this on the production site (v5.5.0). Had about 30 arrivals enter the airspace without any issue. 😕

**Comment by sam-irl** [comment]
@erikquinn it's possible this was fixed in v5.5.0 and I missed it. Probably just need to clear the cache.
