### ISSUE TITLE
Abstract current waypoint altitude and speed setting

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#77]
_From @n8rzz on November 20, 2016 2:12_

The following block is repeated multiple times in the fms, this needs to be abstracted.

```javascript
const curr = this.currentWaypoint;
if (prev && !curr.altitude) {
    curr.altitude = prev.altitude;
}

if (prev && !curr.speed) {
    curr.speed = prev.speed;
}

if (!curr.heading && curr.navmode === 'heading') {
    curr.heading = prev.heading;
}
```

_Copied from original issue: n8rzz/atc#124_

**Comment by erikquinn** [comment]
_From @n8rzz on November 22, 2016 16:11_

**must be merged after n8rzz/atc#53 **

**Comment by erikquinn** [comment]
_From @n8rzz on December 13, 2016 4:12_

`feature/ATC-124` branch created, however, this work is a low priority

**Comment by erikquinn** [comment]
_From @n8rzz on January 15, 2017 4:46_

will likely be invalidated by n8rzz/atc#256

**Comment by n8rzz** [comment]
invalidated by openscope/openscope#139

**Comment by erikquinn** [comment]
Completed under #139.
