### ISSUE TITLE
Make older history dots less opaque

### ISSUE THREAD

**Issue by n8rzz** [openscope/openscope#771]
Position history dots should fade as they age, this was implemented at some point and I must have inadvertently refactored that out.

<img width="110" alt="screen shot 2017-10-07 at 7 34 29 pm" src="https://user-images.githubusercontent.com/3325985/31312896-b93f7160-ab96-11e7-88da-b2945e82909f.png">

_blocked by #726_

**Comment by erikquinn** [comment]
In ARTS, STARS, DSR, and ERAM (all the US systems), they actually do not fade, and simply disappear when beyond the specified length, as is the current implementation. This was actually a conscious change made by me, not a mistake by you. 😃 

That said, if anybody really _wants_ the fading dots, we could always make that an option of themes.

**Comment by n8rzz** [comment]
Oh good, I'm glad I didn't break it. 

I would lean towards not adding an option.  Changing opacity (or alpha in canvas) is a performance killer. 

Closing.
