### ISSUE TITLE
Add Leg to modelSourcePool

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#78]
_From @n8rzz on November 20, 2016 2:31_

_Copied from original issue: n8rzz/atc#126_

**Comment by erikquinn** [comment]
_From @n8rzz on November 25, 2016 19:2_

adding `Leg` into `modelSourcePool` causes tests to fail because `Leg` needs methods attached to the `window`.  This will not be able to be completed until n8rzz/atc#127 has been completed/

**Comment by n8rzz** [comment]
invalidated by openscope/openscope#139

**Comment by erikquinn** [comment]
Completed under #139.
