### ISSUE TITLE
Refactor fms param out of Leg

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#79]
_From @n8rzz on November 20, 2016 4:11_

_Copied from original issue: n8rzz/atc#127_

**Comment by erikquinn** [comment]
_From @n8rzz on January 13, 2017 4:35_

n8rzz/atc#256

**Comment by n8rzz** [comment]
invalidated by openscope/openscope#139

**Comment by erikquinn** [comment]
Completed under #139.
