### ISSUE TITLE
Add AIRAC airport file key and system command

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#793]
We need a way to share with the users the AIRAC version of the airport file they're using, or at least to record it for our own purposes of keeping them fairly up to date.

We can add a `airac` key to all airport files (and airport format documentation!) that we store in the `AirportModel`. A simple system command could then output the AIRAC number in use for the given airport. That way, if users are confused about why they can't use the procedures from current charts, we can all see the chart sets with which the airport is _currently_ equipped. :smiley:

More than anything, I think this will do a lot for our sanity in maintaining our library of airports. When we see an airport still rocking AIRAC 1704 and the current is 1711, we will :grimacing: and :wrench: it!

**Comment by indianbhaji** [comment]
Excellent! 😁

**Comment by Fechulo** [comment]
Sounds good! I like it :+1:

**Comment by filipjonckers** [comment]
good point - a simple "airac": "1711" will do
