### ISSUE TITLE
Remove Monarch Airlines (MON/ZB)

### ISSUE THREAD

**Issue by indianbhaji** [openscope/openscope#801]
Monarch Airlines was a British airline with headquarters in Luton and bases in Birmingham, Leeds, Gatwick and Manchester. Monarch placed an order for 45 of Boeing's 737 MAX-8 aircraft for delivery in 2018, which would replace its fleet of A320s and A321s.

Monarch entered administration on the 2nd of October 2017, ceasing operations immediately after they were denied renewal of their ATOL certificate (disabling their ability to sell package holidays). 110,000 people were left stranded overseas and it was left to the CAA to sort out repatriation efforts. It is the largest airline in British history to have collapsed.

**Comment by sam-irl** [comment]
Never forget.

**Comment by indianbhaji** [comment]
@sam-irl I agree D:
