### ISSUE TITLE
Hold in STAR procedure isn't working

### ISSUE THREAD

**Issue by Marcel510** [openscope/openscope#836]
I'm trying to use a Hold in a STAR but it doesnt work:

```
"BLM": {
            "icao": "BLM2G",
            "name": "Basle-Mulhouse",
            "entryPoints": {
                "BLM": ["BLM"]
            },
            "body": [["ZH677", "A120+|S250"], ["@GIPOL", "A70+|A100-|S230"]],
            "rwy": {
                "10": [],
                "14": [],
                "16": [],
                "28": [],
                "32": [],
                "34": []
            },
            "draw": [
                ["BLM", "ZH677", "GIPOL"]
            ]
}
```

The aircraft is just flying direct GIPOL, but doesn't enter the GIPOL hold.

**Comment by n8rzz** [comment]
🤔 

are you seeing any console errors?  do you have this in a branch within this repo so we could try it out?

**Comment by Marcel510** [comment]
"The following fixes have yet to be defined in the "fixes" section: @GIPOL"
#839

**Comment by felixscheffer** [comment]
In `_calculateTargetedHeadingHold` `outboundHeading` is NaN causing the aircraft to maintain the current heading instead of holding.
