### ISSUE TITLE
Strips: Flight Plan Altitudes for inbound traffic don't make sense

### ISSUE THREAD

**Issue by Marcel510** [openscope/openscope#862]
Airport: Almost all

#### Issue Description
[Screenshot](https://image.prntscr.com/image/b-OVUKbZTI2MWTblZ1ebrw.png)
In this example UAL527 has a Flight Plan Altitude of FL180 which doesn't make sense since that's only the altitude the aircraft was spawned at. I'd suggest to randomly generate it within the aircrafts performance range.

**Comment by erikquinn** [comment]
A fair point. However, the concept of having what's printed on the strip being consistent with the filed cruise altitude is something we will want to keep. 

>I'd suggest to randomly generate it within the aircrafts performance range.

This is something we would achieve by having aircraft spawn at various cruise altitudes, and then descend along the STAR, which is currently already supported by using an array and two values for the altitude property of a spawn pattern, such as `"altitude": [12000, 34000]`, limited to the aircraft's service ceiling.

So we can kind of already achieve this, and will not be changing the strips away from reflecting the filed altitudes for each aircraft. We do appreciate the input though.

Closing.
