### ISSUE TITLE
Hold fixes (@) appear in missing fix caution

### ISSUE THREAD

**Issue by indianbhaji** [openscope/openscope#863]
Browser: Chrome

Airport: All

Approximate play time before issue: 0 mins

#### Issue Description
_please include any console errors and/or screenshots_ 
![image](https://user-images.githubusercontent.com/19408472/34920876-d9292024-f971-11e7-85f9-aef5184c3293.png)

#### Steps to reproduce
- Add a hold fix

**Comment by Marcel510** [comment]
Noticed the same here:
#836

**Comment by felixscheffer** [comment]
@indianbhaji  @Marcel510 
I can not reproduce this issue (with EGCC). Do you still get the error message in the console?

**Comment by Marcel510** [comment]
Resolved by #1065 
Closing
