### ISSUE TITLE
More customisation of callsigns

### ISSUE THREAD

**Issue by indianbhaji** [openscope/openscope#866]
Currently, callsigns are generated based on the length of callsign and whether they should be alphanumeric. 

In #code-help on Slack, it has been suggested that more customisation of the structures of callsigns should be available.

For example: 
`['###']` would generate a callsign with three numbers only (BAW286)
`['##AA']` would generate a callsign with two numbers and two letters (RYR62LA)
`['###', '##AA']` would generate callsigns with three numbers and two numbers and two letters.

**Comment by willfrd** [comment]
Great job @indianbhaji !! Hope to see this up soon ;-)
