### ISSUE TITLE
Restore support for present-position holding patterns

### ISSUE THREAD

**Issue by EvyEh** [openscope/openscope#873]
Browser:
Chrome
Airport:
KDTW
Approximate play time before issue:
15 minutes
#### Issue Description
_please include any console errors and/or screenshots_ 
Hold causes the aircraft to continue on current heading, all further commands are ignored. Assigning a new heading will cause the aircraft to say its heading is the new heading, but it will not actually change headings.

#### Steps to reproduce
- give an aircraft a hold command.

**Comment by EvyEh** [comment]
Note, giving a hold with a fix does work, only hold with no other commands causes the issue.

**Comment by binaryfunt** [comment]
For me, the aircraft continues to follow commands after being told `hold` but it responds with `unable to hold at unknown fix null`

**Comment by cake-pie** [comment]
Closing in favor of duplicate #1318 which has more discussion of implementation details
