### ISSUE TITLE
normalize casing

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#88]
_From @n8rzz on November 26, 2016 18:14_

There is a lot of `toUpperCase()` and `toLowerCase()` happening inline throughout the app.  This should be consistent across the app.

- [ ] Everything should be lowercase internally, input, output, search, etc.
- [ ] only `toUpperCase()` when it comes time to put specific data in the view

_Copied from original issue: n8rzz/atc#164_

**Comment by n8rzz** [comment]
This has been addressed by several merged PRs
