### ISSUE TITLE
Bottom bar shows "loading" after airport change

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#885]
Browser: Chrome
Airport: All

#### Issue Description
"Loading..." is displayed in the bottom right of the scope (over top of the bottom bar) when all loading should be complete.

#### Steps to reproduce
1. Clear cache and load openscope _fresh_
1. Change to any other airport via the airport selection dialog
1. Observe the "loading..." shown at the bottom right (and the lack of terrain*)
4. Refresh page, and observe the same airport comes back up, but without the "loading..."

*the terrain issue can be rectified by dragging or twice clicking the terrain toggle

![image](https://user-images.githubusercontent.com/5103735/36238472-6084b2a4-11c8-11e8-94ca-0c90a8455320.png)

**Comment by n8rzz** [comment]
Oh gross.  I thought I’d completely removed that ages ago.

**Comment by indianbhaji** [comment]
That’s actually a bug? I thought it was just something wrong with the airport files
  

  
  

  
  
>

**Comment by erikquinn** [comment]
For a while I wasn't sure either. But they all have it, and it goes away on reload, so it's got to be something with the logic used to figure out whether its "loading" or "done loading"...
