### ISSUE TITLE
Typo in Warning Text using 5.7.0 (prod)  - Minor issue

### ISSUE THREAD

**Issue by scott-j-smith** [openscope/openscope#888]
Browser: Chrome

Airport: Any

Approximate play time before issue:  Immediate

#### Issue Description
The red warning text for alerting that a plane is already taxied and waiting for departure has a typo.  It says "taxiied" instead of "taxied".   It sounds funny when the voice synthesizer reads it back though.  :-)  

![image](https://user-images.githubusercontent.com/22403776/36337903-a1af62e4-136f-11e8-920f-716b15ee1be5.png)

#### Steps to reproduce
- Easy to reproduce - start an airport, taxi any aircraft to any runway, and as soon as it shows up tell it to taxi again.

**Comment by sam-irl** [comment]
accidental closure

**Comment by erikquinn** [comment]
Rolled into #872. Closing.
