### ISSUE TITLE
Develop REST api for user commands

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#90]
_From @n8rzz on November 27, 2016 17:35_

_NOTE: this is a work in progress._

#### request
```
{
    commands: [string]
}
```

#### response
* 200 
* 400
* 500

_Copied from original issue: n8rzz/atc#170_

**Comment by CutmanCometh** [comment]
@erikquinn 
I know this ticket is almost six years old at this point, but this piqued my interest.
What is the use case that was envisioned for tis ticket?

**Comment by erikquinn** [comment]
No idea. @n8rzz opened the original issue.

**Comment by 3tractorrides** [comment]
The main idea was to get something centralized so the sim could be run on a server. This was a very early attempt at that. The eventual endgame her was to be able to support multiplayer. Or, more specifically handoffs to other humans. 

Being older and wiser I don’t think REST is a good approach for this, so we can probably close this as won’t do.

**Comment by n8rzz** [comment]
The main idea was to get something centralized so the sim could be run on a server. This was a very early attempt at that. The eventual endgame her was to be able to support multiplayer. Or, more specifically handoffs to other humans. 

Being older and wiser I don’t think REST is a good approach for this, so we can probably close this as won’t do.
