### ISSUE TITLE
Divergent Vector Separation (Feature Request)

### ISSUE THREAD

**Issue by owendelong** [openscope/openscope#915]
Browser: Any

Airport: Any

Approximate play time before issue: Varies with traffic and controller actions

#### Issue Description
ATC has a very useful tool available to it, especially when climbing and descending aircraft through the same altitude, called "Divergent Vector Separation".

Imagine you have an aircraft you need to descend from 8000+ to 4000 and one which is climbing from some lower altitude to 8000+. One is on a heading of 030 and the other on a heading of 060. If you extend lines along the longitude of each aircraft, those extended lines cross behind the tails and not in front of the noses. In this case, the aircraft are diverging.

In the 7610.65, a controller is allowed to pass these aircraft through the same altitude with less than 3 miles lateral separation so long as they remain on a divergent vector. (Since the aircraft are diverging, there is no risk of collision.

#### Steps to reproduce
Feature Request

**Comment by erikquinn** [comment]
This _should be implemented_ already? Follows 5-9-7 I think it was, on "Passing or Diverging". Note that 15 degree headings are the minimum divergence for same direction diverging traffic. And in crossing or opposite courses, some "has passed the projected course of the other" type stuff comes into play. 

But at least, we should verify that side-by-side a/c on assigned headings diverging by 15 degrees do not generate a separate loss once established on those headings. I can check some time this weekend if nobody beats me to it.

**Comment by erikquinn** [comment]
Looks like they are using the ground track instead of assigned heading to calculate the heading difference, but other than that it's working correctly. Will substitute for heading because that's the rule: "assigned headings that diverge by at least 15 degrees" so they are considered separated. Otherwise, all other situations are actually being handled correctly.
