### ISSUE TITLE
Create CommandAircraft class to handle execution of aircraft commands

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#92]
_From @n8rzz on December 10, 2016 4:43_

- [x] Create class that accepts an `AircraftInstanceModel` and a `CommandParser` object as parameters
- [x] move `run` methods to this class
- [x] update refs to `this` with aircraft
- [ ] address TODOs and FIXMEs
- [ ] simplify where possible
- [ ] abstract where possible
- [ ] consolidate where possible (DRY)
- [ ] add tests

_Copied from original issue: n8rzz/atc#181_

**Comment by n8rzz** [comment]
finished here: https://github.com/n8rzz/atc/issues/181

remaining work will be covered under #145
