### ISSUE TITLE
Upper airspace

### ISSUE THREAD

**Issue by MartinW2002** [openscope/openscope#921]
Have you considered adding upper airspace?

**Comment by erikquinn** [comment]
Good evening @MartinW2002! And sorry for the delayed response. 😄 Would you mind elaborating what you mean? Is `upper airspace` in reference to high-altitude en route airspace, or do you mean being able to have a complex altitude structure to the airspace, where our airspace extends between varying altitudes in different areas?

**Comment by MartinW2002** [comment]
I'm referring to high-altitude en route airspace, where route structure becomes les relevant since most traffic flights `free route`.

**Comment by erikquinn** [comment]
It's a bit of a long-term goal of ours to add some more love for the en route side of things. There's some work to be done before that is possible though.

I _have_ taken some initial baby steps in that direction though recently! Have a look at PR #937 :smile: 

Will close this issue now to clean up. Feel free to continue commenting here, and we will respond when receiving the notifications. Just want to clear it out of our inbox of cards needing to be sorted and prioritized for work.

Closing.
