### ISSUE TITLE
KDCA SID issues, points deduction

### ISSUE THREAD

**Issue by JPmAn24** [openscope/openscope#927]
Browser: Google chrome

Airport: KDCA

Approximate play time before issue: any

#### Issue Description
Any of the SIDs at DCA that go over R-6608(a, b, and c) don't gain altitude before flying through the No-Fly zone. 

#### Steps to reproduce
- clear a plane for any of the SIDs that go over R-6608 i.e. CLTCH1.MAULS
- airplane goes through the R-6608 after leaving 7000, making me unable to redirect it.

**Comment by Fechulo** [comment]
Hey @JPmAn24 Sorry for the late response 😬 
Does this still occur if aircraft are told to climb via the SID? (i.e. `cvs` command)

**Comment by JPmAn24** [comment]
Yes, it does. I always (being used to it) enter "caf to cvs" every time the runway is cleared by the previous aircraft.

**Comment by Fechulo** [comment]
I haven't been able to reproduce this, all aircraft climb high enough to fly over the restricted area. If that's not the case, then it should be up to the controller to prevent, which isn't a problem, since it all happens within the airspace.

**Comment by JPmAn24** [comment]
I am currently redirecting aircraft around the airspace via the navfixes "HIGPO" and "GILFF" then direct back to the SID.

**Comment by Fechulo** [comment]
Ok, having done some more testing, I've noticed the vast majority of aircraft that aren't climbing high enough in time are PSA Airlines CRJs so the easiest solution would be to remove the airline from the conflicting spawnPatterns.

**Comment by erikquinn** [comment]
The CRJs are doing 2000fpm according to the aircraft files..  is that seriously not enough to top the airspace? Something seems very fishy
