### ISSUE TITLE
Aircrafts are skipping a fix

### ISSUE THREAD

**Issue by Marcel510** [openscope/openscope#935]
Airport: OTHH (#857)

#### Issue Description
![Screenshot](https://i.imgur.com/9Fl9N7v.png)
The route of the aircraft should be ELEDA-MEBTI-BOSUP-... 
But after ELEDA the aircraft skipping MEBTI and turns inbound BOSUP.

#### Steps to reproduce
That's applicable to the following SIDs: BATHA1E, BUNDU1E, NAMLA1E, SALWA1E
(At the current version of the airport MEBTI defined as a fly-over fix in order to prevent this)

**Comment by felixscheffer** [comment]
Related to #1034

```
export const calcTurnInitiationDistance = (speed, bankAngle, courseChange) => {
    const turnRadius = calcTurnRadius(speed, bankAngle);

    return turnRadius * tan(courseChange / 2) + speed;
};
```

Due to `tan(courseChange / 2)` course changes close to 180 degrees will end up with a huge turn initiation distance.
