### ISSUE TITLE
Airport Revival: Dubai International Airport 

### ISSUE THREAD

**Issue by indianbhaji** [openscope/openscope#938]
Reintroduce Dubai International Airport

Looks like this is part of the Middle East push for next release (considering we have Abu Dhabi and Doha in line for the next release)

**Comment by jdouglas77** [comment]
is it done yet?

**Comment by Fechulo** [comment]
@jdouglas77 Adding an airport to the sim takes a lot of work and time from several people. @indianbhaji has been working very hard on this airport, but it will be a while until it is added back into openScope. For the moment, you can look at the deployment for this airport [here](https://openscope-dev-pr-962.herokuapp.com/), but bear in mind that the airport may not be stable at this point, so expect errors.

**Comment by indianbhaji** [comment]
@jdouglas77 Only an airport guide to do. Will be available next month, as I previously said.

**Comment by jdouglas77** [comment]
yep i tried it out, works perfectly, only issue is that the holding system
needs reworking...

**Comment by Marcel510** [comment]
What exactly ia the issue with the holding system? For me it works pretty good

**Comment by jdouglas77** [comment]
@Marcel510 its not an OMDB problem, its a openscope problem, the Re rout command is to long and hard to do in busy airspace and sometimes A/C don't necessarily hold along there own routes, so when i want to have 2 holding areas in OMDB as waypoints KEBOG and LOVOK i can't, its alright but makes it a lot more challenging at busy times!
