### ISSUE TITLE
Land command doesn't work

### ISSUE THREAD

**Issue by Fechulo** [openscope/openscope#947]
Browser: Chrome

Airport:
Seen in KBOS, though I presume it's happening everywhere

Approximate play time before issue: n/a

#### Issue Description
Land command isn't working at all
no console errors

#### Steps to reproduce
guide any aircraft to the ILS
instruct them to land using the land command e.g. `AAL123 land 22L`
aircraft reads back `AAL123, say again, say again`

**Comment by Fechulo** [comment]
This is intentional, closing

**Comment by erikquinn** [comment]
Will still be addressed with a PR containing updates to documentation and the red response message which should have been included when the change was made.

Reopening.

**Comment by erikquinn** [comment]
Resolved by #948. Closing.
