### ISSUE TITLE
Arrivals don't always descend to controllable altitudes

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#953]
Browser: Chrome
Airport: KDCA

#### Issue Description
Aircraft do not always descend to within the vertical boundaries of our airspace. In cases where there is no STAR to descend via, the aircraft will descend to the top of the airspace. However, when there IS a star with descent information, but it doesn't force them down into _our_ airspace, they are stuck above where we can control. They should always be forced down to an altitude where we can do something with them, whether descending via STAR, or whether descending manually.

#### Steps to reproduce
- At KDCA, observe the arrivals from the south level off at 90 when our airspace tops out at 70.

**Comment by sam-irl** [comment]
closed in #954
