### ISSUE TITLE
Aircraft Tags not disapearing. 

### ISSUE THREAD

**Issue by Schluppi** [openscope/openscope#967]
Browser:
Google Chrome and Firefox
Airport:
All

Approximate play time before issue:
0
#### Issue Description
_please include any console errors and/or screenshots_ 
The plane tag box fills up with departure planes, after handoff they do not dissapper from the box/tab.
![unbenannt](https://user-images.githubusercontent.com/39242942/39969575-1de5844a-56de-11e8-9134-1a343ef6c93e.PNG)

#### Steps to reproduce
- Just work down planes till the Plane Tag space ist completey filled with departure planes

**Comment by Marcel510** [comment]
Already covered by #906

**Comment by Schluppi** [comment]
@Marcel510 Ok, didn't see that then :)

**Comment by erikquinn** [comment]
Yep, will definitely be toward the top of the list of things to fix when we get a chance. Thanks for the report @Schluppi!

Closing as duplicate.
