### ISSUE TITLE
N-# Aircraft have wrong callsign

### ISSUE THREAD

**Issue by JPmAn24** [openscope/openscope#968]
Browser: Google chrome

Airport: KABQ

Approximate play time before issue: 

#### Issue Description
I don't know if this happens with other countries, but if you turn on the sound, the callsign for "N" is "default" (example: N238HG = "Default Two-Thirty-Eight Hotel Golf")

#### Steps to reproduce
- Go to any US airport that has GA
- Do anything with said GA airplane

**Comment by erikquinn** [comment]
Ruh roh!
