### ISSUE TITLE
Simulator continues running after the simulator pausing and loses focus

### ISSUE THREAD

**Issue by indianbhaji** [openscope/openscope#995]
Browser: Chrome 66.0.3359.181 (Official Build) (64-bit)

Airport: all

Approximate play time before issue: n/a

#### Issue Description
If you pause the simulator using the pause button on the bottom, the screen is greyed out with a play button appearing in the middle. However, if the tab loses focus, you return to see that the simulator is running, instead of the grey screen and play button as before.

#### Steps to reproduce
- pause the game
- alt-tab out or go to another tab
- return to the simulator tab
- the simulator is running

**Comment by n8rzz** [comment]
Hmm, I feel like we did this on purpose because the pause logic is a little weird.

**Comment by erikquinn** [comment]
Resolved by #1336. Closing.
