### ISSUE TITLE
LKPR airport guide not added to airport-guide-directory.md

### ISSUE THREAD

**Issue by Marcel510** [openscope/openscope#996]

**Comment by jakcharvat** [comment]
Oh no. 🤦‍♂️ I might have forgotten that. I can fix that when I get back from vacation in about 12 days, or if someone does it before then, fine by me 😉

**Comment by Marcel510** [comment]
I'll do it, it's just adding one line 😉 👍

**Comment by erikquinn** [comment]
Resolved by #997. Closing.
